.travis.yml
=> Add Travis CI control file.

provision.sh
Details:
- Fixed typo in provision.sh
=> Fixed vagrant setup typo.

README.rst, setup.cfg
Details:
- Fixed links in README.rst
- Fixed links in setup.cfg
=> Fixed github links in documentation.

README.rst
=> Added links to RTD documentation to README.rst.

CONTRIBUTING.rst
=> Improved description of git sign-off line in CONTRIBUTING.rst.

.travis.yml
=> Disabled Travis notification emails.

docs/intro.rst
=> Improved description of supported environments.

README.rst
Details:
- Add 'Latest pypi version' status image.
- Add 'Download per Month' status image.
=> Added more status images to README.rst

setup.cfg
Details:
- Updated summary, author, author-email,
maintainer, maintainer-email and
Development Status field.
=> Updated several fields in setup.cfg

Makefile
Details:
- Activate twine upload rule.
- Remove Windows installable from dist_files.
=> Update build handling in Makefile.

zhmcclient/_logging.py
Ready for review and merge (use `make builddoc` to review the documentation).
=> Improved documentation for logging.

zhmcclient/_resource.py
=> Fixed docs for missing parameter in BaseResource.get_property().

zhmcclient/_timestats.py
=> Sorted the operations in TimeStats display.

tests/test_lpar.py
Details:
- Added Unit Tests for Lpar operations.
- Fixed issue #8
=> Fixes #8: Added Unit Tests for Lpar class.

tests/test_activation_profile.py
Details:
- Added Unit Tests for Profile Activation operations.
- Fixed issue #9
=> Fixes #9: Added Unit Tests for Profile Activation class.

tests/test_partition.py
Details:
- Added Unit Tests for Partitions operations.
- Fixed issue #7
=> Fixes #7: Added Unit Tests for Partition class.

README.rst
=> Update  README.rst.

docs/intro.rst
=> Added an 'Issue reporting' section to the Intro chapter.

docs/development.rst, docs/index.rst
Ready for review and to be merged.
=> Added 'Development' chapter to the documentation.

tests/test_resource.py, zhmcclient/_resource.py
Details:
- Added __str__ and __repr__ to BaseResource class.
- Added unit test.
=> Add string representation of BaseResource.

README.rst
Details:
- Added alt text to all badges that did not have it yet.
- Removed '?badge=latest' from URL in docs badge.
- Reordered badges to be more logical.
- Changed title of "Installation" section linked to in "Install" section to what it really is.
- Added link to Pypi version (=stable) of the documentation to the Documentation section.
=> Minor improvements in README.rst

README.rst
Ready to be reviewed and merged.
=> Changed link to Installation section in README to be to Pypi/stable version

README.rst, docs/intro.rst
Details:
- Updated example program in README.rst.
=> Simplify quickstart example

docs/resources.rst, examples/example8.py, tests/test_nic.py, zhmcclient/__init__.py, zhmcclient/_nic.py, zhmcclient/_partition.py
Details:
- Add NicManager class.
- Add Nic class.
- Add Unit Tests for NicManager and Nic.
- Add NicManager to Nic class.
- Add NIC to documentation reference.
- Add NIC example (example7.py).
=> Add NIC support

docs/index.rst
Details:
- Update index.rst to be the same header like
in README.rst
=> Update documentation header

tests/test_partition.py, zhmcclient/_partition.py
Datails:
- Dump Partition
- Perdform PSW Restart
- Mount ISO Image
- Unmount ISO Image
=> Add more partition operations

docs/development.rst
=> Fixes #46: Added Repository section to Development chapter

zhmcclient/_adapter.py, zhmcclient/_port.py
=> Made documentation of Port / PortManager consistent with other resources

docs/appendix.rst, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
=> Fixed doc links to resource types.

docs/development.rst
=> Docs: Added section for releasing to PyPI.

tests/test_cpc.py, zhmcclient/_cpc.py
This speeds it up on an EC12 from 35..45 sec to 0.1 sec.
Please review.
=> Optimized dpm_enabled implementation for better performance.

tools/cpcinfo, zhmcclient/_resource.py
Please review.
Details:
- Added a script 'tools/cpcinfo' that displays information about CPCs.
- In support of that script, added a 'prop()' method for resources that allows specifying a default value in case the property does not exist.
=> Added cpcinfo tool and prop() method for resources.

.travis.yml
=> Added pypy Python to Travis CI environments.

tools/cpcinfo
=> Fixes #86: Issue where cpcinfo -a raised TypoError on Python 3.

docs/appendix.rst
Please review.
Details:
- Added sub-sections for each resource scope.
- Clarified terminology for resource, resource representation.
- Minor updates to resource definitions.
- Simplified introduction for resource model.
=> Docs: Updated resource model.

docs/appendix.rst, docs/changes.rst, docs/development.rst, docs/index.rst, docs/intro.rst
The changes since 0.4.0 in the new "Change log" section are supposed to be up to date.
Please review.
=> Docs: Added change log section.

docs/intro.rst
=> Simplified install from repo and enabled it for users without github key

docs/changes.rst, docs/development.rst, tests/unit/test_exceptions.py, tests/unit/test_session.py, zhmcclient/_exceptions.py, zhmcclient/_session.py
This PR addresses the ParseError portion of issue #94.
The other parts will be addressed separately.
This PR is based on PR #95, so the first commit has already been reviewed as part of its review.
Details:
- Added line and column properties ot ParseError, which are parsed from the message string.
- In the low level HTTP methods in the Session class, making sure that ParseError gets raised if the returned JSON cannot be decoded.
- Extended the unit test cases for ParseError to test the additional line and col properties.
- Extended the unit test cases for Session to test some cases of invalid JSON being returned.
=> Improved ParseError and its use.

zhmcclient/_session.py
Details:
- Problem was introduced with MR #96 (commit 42633c88).
- Generate new result_object after updating result.
=> Fixes #99: KeyError: 'status' when running example5.py

examples/example5.py
=> Updatd example5 to allow for CPC being in 'service-required' state.

zhmcclient/_partition.py
Signed-off-by: Juergen Leopold leopoldj@de.ibm.com
=> Fixes #101: Fix documentation of field Partition.hbas

docs/notebooks/03_datamodel.ipynb, docs/notebooks/04_error_handling.ipynb
Please review.
Details:
- In tutorial 3, specified HMC userid as a variable in the code instead of asking for it. Clarified terminology for properties by referencing them as 'resource properties'.
- Added tutorial 4 about error handling.
=> Further improvements in tutorial 3 and new tutorial 4.

.github/ISSUE_TEMPLATE.md, tests/unit/test_activation_profile.py, tests/unit/test_adapter.py, tests/unit/test_client.py, tests/unit/test_cpc.py, tests/unit/test_hba.py, tests/unit/test_lpar.py, tests/unit/test_port.py, tests/unit/test_virtual_function.py
Please review particularly the content of the issue template.
=> Added issue template.

docs/appendix.rst, tests/unit/test_exceptions.py, zhmcclient/_client.py, zhmcclient/_exceptions.py
Details:
- Added min and max API version as arguments.
- Extended exception testcases accordingly.
- Added a new type 'HMC API version' to the special types section of the documentation.
- Changed Client.version_info() documentation to use the new 'HMC API version' type.
=> Improved VersionError exception class.

docs/changes.rst
=> Updated change log.

docs/changes.rst, setup.cfg, tools/cpcdata
Please review
Usage: 
`tools/cpcdata --help`
=> Added a 'cpcdata' tool for showing CPC info in a data center.

docs/changes.rst
=> Updated change log for 0.8.0 release.

docs/changes.rst
=> Started v0.9.0 development.

docs/changes.rst, examples/example1.py, examples/example2.py, examples/example3.py, examples/example4.py, examples/example5.py, examples/example6.py, examples/example7.py, examples/example8.py
For details, see commit message or run the examples.
=> Improved the examples.

docs/changes.rst
=> Updated change log for 0.9.0 release.

docs/changes.rst
=> Start v0.10.0 development

README.rst
=> Add Appveyor status badge

design/fake-client.rst
Please review.
The sibling PR #143 provides a first implementation of the design.
=> Design for mocking support for zhmcclient

docs/changes.rst, zhmccli/_cmd_hba.py
=> Fix unrecognized field ('adapter-port')

docs/appendix.rst, docs/changes.rst, docs/intro.rst, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
Details:
- Added a new section 'Setting up the HMC' in the Introduction chapter.
- Added a section 'Authorization requirements' for each method that has specific requirements.
=> Added documentation of authorization requirements

docs/changes.rst, zhmcclient/_notification.py
=> Updated change log; Declared NotificationReceiver as experimental

docs/changes.rst
=> Update change log for 0.10.0 release

docs/changes.rst
=> Started development of v0.11.0

zhmcclient/_manager.py, zhmcclient/_notification.py, zhmcclient/_timestats.py
=> Docs: Minor formatting fixes for return values in docs

setup.cfg
=> Added Python 3.6 to PyPI metadata

Makefile, tools/cpcdata, tools/cpcinfo
Details:
- Added tools/cpcinfo and tools/cpcdata scripts to the 'check' make target.
- Fixed the flake8 errors that were raised as a result.
=> Fixes #192: Added tools to check target and fixed flake8 errors

docs/changes.rst, requirements.txt
=> Fixes #199: Added minimum version 4.0.0 to 'decorate' dependency.

docs/changes.rst, tests/unit/test_session.py, zhmcclient/_exceptions.py, zhmcclient/_session.py
=> Fixes #207: Added support for tolerating HTML response content

docs/changes.rst
=> Updated change log for 0.11.0 release.

docs/changes.rst
=> Start development of v0.12.0

docs/changes.rst, zhmccli/_cmd_adapter.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_vfunction.py
=> Fixes #213: In CLI, added support for -y option

.travis.yml, Makefile, appveyor.yml, docs/changes.rst, tox.ini
=> Added OS-X to Travis CI environment

zhmcclient_mock/_hmc.py
=> Fixes #233: Fixed typo in description of FakedHmc

.travis.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/development.rst, minimum-constraints.txt, requirements.txt
=> Improved description of Pypi release process

.travis.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt, tests/unit/zhmcclient_mock/test_hmc.py
This change improves the testcases in order to help debugging issue #239.
Even though there may still be an issue that is not addressed by this PR, this PR can be merged.
=> Improved testcases for object-id/element-id in mock support

.travis.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/intro.rst, minimum-constraints.txt, requirements.txt
=> Fixes #234: Added description for internet-less installation

docs/changes.rst, zhmccli/_cmd_lpar.py
=> Fixes #226: Add load-parameter to 'zhmc lpar load'

docs/changes.rst
=> Updated change log for 0.12.0 release.

.github/ISSUE_TEMPLATE.md
Details:
- Added fields for HMC version and CPC version.
=> Improved issue template

docs/changes.rst, zhmcclient/_session.py
This PR is proposed as the final solution to issue #249. See the discussion in that issue.
=> Fixes #249: Restricted read retries to just HTTP GET

docs/changes.rst, docs/concepts.rst, zhmcclient/_manager.py
This change makes the documentation of the lookup methods of manager classes (find(), findall(), list()) more specific, and also improves the 'Filtering' concepts chapter.
This is hoped to help with the uncertainties that lead to issue #261.
=> Improved description of filter arguments

docs/changes.rst, zhmcclient/_cpc.py
=> Fixes #277: Incorrect result of Cpc.dpm_enabled for z13 in classic mode

docs/changes.rst, tests/unit/test_adapter.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_cpc.py, zhmcclient/_resource.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
Please review and merge (this PR is on top of PR #278).
=> Improvements and fixes in mock support

docs/changes.rst, tests/unit/test_adapter.py, tests/unit/test_exceptions.py, tests/unit/test_manager.py, tests/unit/test_resource.py, tests/unit/zhmcclient_mock/test_hmc.py, zhmcclient/_adapter.py, zhmcclient/_exceptions.py, zhmcclient/_manager.py, zhmcclient/_resource.py, zhmcclient/_timestats.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py
This change was made in order to improve the ability to debug the real objects at the API and the faked objects of the mock support. See the commit message for details.
=> Improved repr() and str() in various places

docs/changes.rst
=> Updated change log for 0.13.0 release.

zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py
=> CLI: Fixed TypeError with find_partition(), find_lpar().

zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_hba.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py, zhmcclient_mock/_hmc.py
**Note:** This PR is needed for the function tests of the zhmc Ansible modules.
=> Fixed shallow copy errors for input properties of resources.

zhmcclient/_adapter.py, zhmcclient/_partition.py, zhmcclient_mock/_urihandler.py
Details:
Implement following commands:
- Change Crypto Type
- Increase Crypto Configuration
- Change Crypto Domain Configuration
- Decrease Crypto Configuration
=> Add Crypto Support for Partitions

docs/changes.rst, zhmcclient_mock/_urihandler.py
=> Change log for crypto support, documented missing mock support.

docs/changes.rst, zhmcclient/_partition.py
=> Added waiting for desired status to Partition.start().

docs/changes.rst, tests/unit/test_exceptions.py, zhmcclient/_exceptions.py, zhmcclient/_manager.py
=> Improved NoUniqueMatch exception to show matching resources.

tests/unit/test_activation_profile.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py
=> Fixed errors in unit testcases for ActivationProfile

zhmcclient_mock/_urihandler.py
=> Improved misleading exception message in mock support.

tests/unit/test_adapter.py, tests/unit/test_manager.py, tests/unit/test_port.py, tests/unit/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
This PR is now ready for review and merging (Its dependent PR #327 is now merged).
=> Fixes #261: Improved performance of lookup by object-id

zhmcclient/_partition.py
=> Fixed JSON serialization issue in increase/decrease_crypto_config()

zhmcclient_mock/_hmc.py
=> Mock: Fixed FakedBaseResource init when properties are empty

zhmcclient/_manager.py
=> Fixed optimized lookup by object-id

tests/unit/test_adapter.py, zhmcclient/_adapter.py
=> Fixed card type of Crypto Express 5s adapter.

docs/changes.rst, tests/unit/test_activation_profile.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
The testcase migration changes will depend on this change.
=> Fixed updating the name-to-URI cache when renaming.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Mock: Several fixes in URI handler for CPC Export WWPN List.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Mock: Added URI handler for CPC Export / Import Profiles.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Mock: Added checking for status conflicts for Partition.start/stop().

appveyor.yml
=> Reduced test variations for Appveyor CI.

zhmcclient_mock/_urihandler.py
Will be needed by the test migration PR #352.
=> Mock: Fixed partition.start/stop() result.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
Only mock support - no external functionality changes.
=> Mock: Cleanup and improvements in URI handler.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #359.
=> Fixes #320: Mock: Added support for Change Crypto Type of Adapter.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #359.
=> Mock: Fixed fields check in URI handler of increase/decrease crypto.

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #359.
=> Fixes #317: Mock: Added support for HBA Reassign Port operation.

docs/notebooks/04_error_handling.ipynb, docs/tutorial.rst, zhmcclient/_exceptions.py
=> Improved the tutorial 04 error handling.

docs/changes.rst, zhmcclient/_logging.py
=> Fixes #341: Fixed AttributeError in log module for jupyter/interactive.

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PRs #359 and #360 and #361.
=> Mock: Improvements and testcases for partition crypto ops.

docs/changes.rst, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #359.
=> Fixes #319: Mock: Added support for Get Connected VNICs operation.

docs/changes.rst
=> Updated change log for 0.14.0 release.

docs/changes.rst
=> Started 0.15.0 release.

dev-requirements.txt, docs/appendix.rst, docs/changes.rst, docs/general.rst, docs/resources.rst, examples/example_hmccreds.yaml, examples/metrics.py, requirements.txt, zhmcclient/__init__.py, zhmcclient/_client.py, zhmcclient/_metrics.py, zhmcclient/_session.py
Details:
- Add MetricsContext and MetricsContextManager class.
- Add Metrics resource to documentation.
- Add metrics example.
=> Add Metrics support to the API

tools/cpcdata
=> Improved the tools/cpcdata script.

docs/changes.rst, zhmccli/_cmd_metrics.py, zhmccli/_helper.py, zhmcclient/_metrics.py, zhmcclient/_session.py
Details:
- Fixed TypeError for issue #372 in most CLI commands (e.g. cpc list).
- Fixed several sorting issues in metrics CLI.
=> Fixes #372: CLI: Fixed several Python 3 errors.

.gitignore, Makefile
=> Optimized build of distribution archives.

.travis.yml, Makefile, docs/changes.rst, docs/cli.rst, docs/general.rst, zhmcclient/_lpar.py
=> Minor fixes in documentation.

docs/intro.rst
=> Docs: Fixed supported environments in intro.

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Updated package requirements.

CODE_OF_CONDUCT.md, docs/development.rst
=> Add 1.4 of Contributor Covenent Code of Conduct

docs/development.rst
=> Fix Code of Conduct link

docs/development.rst
=> Update link to 'How to Get Your Change Into the ...'

docs/changes.rst
=> Updated change log for 0.15.0 release.

docs/changes.rst
=> Started 0.16.0 release.

.codeclimate.yml
For changes, see commit message.
=> Customized codeclimate.

README.rst
This change adds a Code Climate generated
grade point average (or GPA) badge to the README file.
GPA is an academic grading system used to indicate
overall performance.
=> Add Code Climate Badge

docs/changes.rst
=> Updated change log for 0.16.0 release.

docs/changes.rst, zhmccli/_cmd_nic.py, zhmccli/_cmd_vfunction.py
=> Fixes #416: Access to partition from nic and vfunction via respective manager

.travis.yml
The real test is whether cron-triggered Travis runs on master run fine now, once this PR is merged.
=> Fixed empty PIP_CMD in cron-triggered Travis runs.

docs/changes.rst, tests/unit/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
This PR will be the basis for multiple PRs about migration to py.test.
=> Added CPC and Partition status checks to mock support where missing + cleanup

docs/changes.rst, docs/mocksupport.rst, tests/unit/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #435
Details are in the commit message.
=> Improved mock support to return HTTP 400 instead of raising ValueError

docs/changes.rst, docs/mocksupport.rst, tests/unit/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #438.
It will be used by other PRs, hence setting the priority flag.
Details in the commit message.
=> Extended InvalidResourceError in mock support.

docs/appendix.rst, docs/changes.rst, docs/general.rst, tests/unit/test_utils.py, zhmcclient/__init__.py, zhmcclient/_metrics.py, zhmcclient/_utils.py
This PR contains stuff that is needed by two other (large) PRs. It has been created in order to have these two PRs depend on this PR, instead of one depending on the other.
=> Added timestamp related utility functions.

docs/appendix.rst, docs/changes.rst, docs/general.rst, docs/mocksupport.rst, tests/unit/test_utils.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/__init__.py, zhmcclient/_metrics.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Important:** This PR is on top of PR #421.
This PR is now complete, ready for review and merge. For details, see the commit message.
=> Added mock support for metrics.

tests/unit/test_activation_profile.py, tests/unit/test_partition.py
=> Added tests for null props to Partition + Image Act. Profile

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmccli/_cmd_session.py, zhmcclient/_session.py
Ready for test, review and merge.
=> Fixes #422: Fixed in zhmc CLI that session create used existing session ID.

docs/changes.rst, tests/unit/test_session.py, zhmcclient/_session.py, zhmcclient_mock/_session.py
=> Added '__repr__()' to 'Session' and 'FakedSession' classes.

docs/changes.rst, tests/unit/test_client.py, tests/unit/test_exceptions.py, zhmcclient/_exceptions.py
**Note:** This PR is on top of PR #431.
Note that there is one incompatible change in `HTTPError`.
=> Migrated _client,_exceptions modules to py.test; changes to exceptions

tests/unit/test_resource.py
Details in the commit message.
=> Test BaseResource: Improved assertion info, consistent URIs.

docs/changes.rst, tests/unit/test_hba.py, zhmcclient/_hba.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #440.
=> Migrated HBA unit tests to py.test; Small fixes to Hba.

docs/changes.rst, tests/unit/test_nic.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PR #440.
=> NIC: Migrated unit test to py.test, Changes in mock support

tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
This is the permenant fix for issue #441 (which was circumvented in PR #442).
=> Fixes #441: Fixed TypeError in unit test of metrics mock support

docs/appendix.rst, docs/changes.rst, docs/intro.rst
Now ready for review and merge.
=> Docs: Fixed HMC API version and API book ref. for z14

docs/changes.rst
=> Updated change log for 0.17.0 release.

docs/changes.rst
=> Started 0.18.0 release.

docs/changes.rst
**Note:** This PR is on top of PR #453.
=> (#3) Start 0.19.0

.travis.yml, Makefile, appveyor.yml, docs/changes.rst, tests/unit/common/test_utils.py
**Note:** This PR is on top of PR #459.
=> (#5) Fixes and improvements in Makefile

.travis.yml, Makefile, appveyor.yml, docs/changes.rst, tests/unit/common/test_utils.py, tests/unit/test_utils.py
**Note:** This PR is on top of PR #455.
=> (#6) Disabled the unit test functions that just print datetime info

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_cpc.py, zhmcclient_mock/_urihandler.py
=> Added support for CPC energy management operations.

Makefile, docs/changes.rst, tests/unit/zhmcclient/test_logging.py, zhmcclient/_logging.py
=> Small improvement in setup of zhmcclient logging

tests/function/test_activation_profiles.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py
Next step towards more function tests.
=> Extended mock by class and child res; added FT for Act.Profiles

.travis.yml
=> Travis for OS-X: Fixed changed Python install and added py2 run

Makefile
=> Supressed makefile init error messages

examples/metrics.py, zhmcclient/_metrics.py
Note: This change only fixes the coding error, but does not yet fix issue #476 (adding test cases for the metrics support).
=> Fixes #478: Fixed TypeError in metrics support; improved metrics example

tests/unit/zhmcclient/test_metrics.py, zhmcclient/_metrics.py, zhmcclient_mock/_hmc.py
Note: Some test cases are still TODO, leaving them for a future update. They have an according TODO marker and are marked as skipped for pytest.
=> Fixes #476: Added unit tests for _metrics module, Fixed metrics mock support

minimum-constraints.txt
=> Using == instead of === in minimum constraints file

Makefile
=> Fix use of double brackets in make shell()

docs/changes.rst
=> Updated change log for 0.19.0 release.

.travis.yml, docs/conf.py
=> Added debug info for package version issue to Sphinx build

docs/changes.rst, docs/concepts.rst, docs/conf.py, zhmcclient/_notification.py
=> Docs: Resolved Sphinx build warnings

Makefile
=> Improved Makefile with extra check for empty package version

Makefile
=> Made makefile consistent with zhmccli and fixed minor errors

appveyor.yml
=> Fixed Git rebase in Appveyor CI

Makefile, docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmcclient/_logging.py
**Note:** This PR is on top of PR #492.
=> Lowered version reqs for dependent packages.

Makefile, docs/changes.rst, docs/intro.rst
**Note:** This PR is on top of PR #492.
=> Docs: Improved docs for installing without Internet and selecting target Python env

docs/conf.py
Needs to merge to trigger RTD build, so this PR is using the fast path.
=> Added more debug information to docs/conf.py to analyze package version issue on RTD

docs/conf.py
Another one, this time with a tag at HEAD, which is the error case on RTD.
Again taking the fast path.
=> More debug info and a test tag.

docs/changes.rst
=> Updated change log with missing entry about appveyor changes

docs/changes.rst
=> Release 0.19.11

docs/changes.rst
This starts 0.20.0 again, this time based upon the released 0.19.11 version.
=> Restart 0.20.0

docs/development.rst
=> Streamlined and extended 'how to release' section in docs

docs/changes.rst, docs/development.rst
=> Fixed release description for RTD stable builds

tests/unit/zhmcclient/test_manager.py, tests/unit/zhmcclient/test_nic.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_virtual_switch.py
=> Consolidated internal nic_/partition_object() methods to resource_object()

tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py
=> Enhanced faked resources to automatically set parent prop.

.travis.yml, appveyor.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, setup.cfg
=> Added support for Python 3.7

dev-requirements.txt, docs/conf.py, docs/general.rst, docs/resources.rst, minimum-constraints.txt
This one is best reviewed by looking at the docs output (Methods and Attributes lists in each class documentation).
=> Added methods and attributes lists to class docs.

docs/changes.rst, tests/unit/zhmcclient/test_adapter.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_adapter.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Added Adapter.change_adapter_type() operation

dev-requirements.txt, docs/conf.py, minimum-constraints.txt
=> Fixed Sphinx build on Python 3.7 with AutoAutoSummary extension

tests/unit/zhmcclient/test_notification.py, tests/unit/zhmcclient/test_session.py, zhmcclient/_constants.py, zhmcclient/_notification.py, zhmcclient/_session.py
Add support for specifying the used JMS/STOMP and HMC ports.
=> Support for specifiying ports

examples/metrics.py
=> Fixed metrics example by adding sleep

docs/changes.rst
=> Release 0.21.0

zhmcclient/_session.py
=> Fixed incorrect HMC method in a comment on 202 processing

docs/development.rst
=> Docs: Updated how to release a version

docs/changes.rst
=> Start 0.23.0

docs/changes.rst, zhmcclient/_partition.py
Does not yet contain test code.
=> Added support for zeroize single crypto domain

docs/changes.rst, examples/example_hmccreds.yaml, examples/list_storage_groups.py
=> Fixes #554: Fixed list_storage_groups.py example

tests/end2end/test_cpc.py
**Note:** This PR is on top of PR #557 - review only the last commit.
=> Added end2end testcases for CPCs

.travis.yml, Makefile, zhmcclient/_logging.py, zhmcclient/testutils/hmc_definition_fixtures.py
=> Added logging support to end2end tests

docs/changes.rst, zhmcclient/_session.py
=> Fixes #560: Fixed blanking out of passwords and session tokens in log

docs/changes.rst
=> Start 0.24.0

.gitignore, Makefile, appveyor.yml, docs/intro.rst, tools/package_version.py, tools/python_version.py, tools/retry.bat, tox.ini
=> Fixes #412: Major rework to use correct Python in Appveyor CI and other minor fixes

Makefile, appveyor.yml, tox.ini
=> Fixed support for CygWin in Appveyor

appveyor.yml
=> Fixed CygWin environment in Appveyor CI

Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, tests/end2end/test_cpc.py, zhmcclient/testutils/cpc_fixtures.py, zhmcclient/testutils/hmc_definition_fixtures.py
This addresses a first part of issue #574.
=> Improved end2end test support for zhmcclient users

docs/changes.rst, examples/show_os_messages.py, zhmcclient/_notification.py
=> Improved show_os_messages.py example

docs/changes.rst, zhmcclient/_session.py
=> Blanked out the session ID value in the log record for logging off

docs/changes.rst, zhmcclient/_session.py
=> Fixes #576: Changed exception raised when login user is not authorized

docs/changes.rst, tests/unit/zhmcclient/test_utils.py, zhmcclient/_utils.py
=> Added timezone support to zhmcclient.datetime_from_timestamp()

docs/changes.rst, tests/unit/zhmcclient/test_notification.py, zhmcclient/_notification.py
=> Added support for multiple notification topics in NotificationReceiver

docs/changes.rst
=> Release 0.24.0

docs/changes.rst
=> Start 0.25.0

docs/appendix.rst, docs/changes.rst, docs/intro.rst
=> Docs: Added 2.14.1 to Bibliograohy and Introduction

docs/changes.rst
=> Release 0.25.0

docs/changes.rst
=> Start 0.26.0

docs/changes.rst
=> Start 0.25.1

docs/changes.rst
=> Updated change log for fix with os_ipl_token parm

docs/changes.rst, setup.cfg
=> Promoted dev status of package on Pypi from alpha to beta

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient/testutils/hmc_definitions.py
=> Fixes #605: Migrated from yamlordereddictloader to yamlloader

minimum-constraints.txt
=> Fixed minimum package versions

.travis.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed PyYAML version issues on Python 3.4 and above

zhmcclient/_notification.py
=> Improved internal documentation for notification module

examples/example_hmccreds.yaml, examples/show_os_messages.py
=> Improved show_os_messages example with break based on message ID

dev-requirements.txt, minimum-constraints.txt, requirements.txt
=> Updated development deps in general and to fix issues on Python 3.4

docs/changes.rst, zhmcclient/_partition.py
Rolls back PR #634 into 0.26.1.
=> 0.26: Fixes #629: Fixed AttributeError in partitions.list_storage_groups()

docs/changes.rst, zhmcclient/_partition.py
=> Fixed AttributeError in partitions.list_storage_groups()

docs/changes.rst, docs/development.rst
=> Docs: Fixed description to start a new version

docs/changes.rst, docs/intro.rst
=> Fixed missing egg=zhmcclient in install frpom repo URL

docs/changes.rst, docs/intro.rst, zhmcclient/debuginfo.py
Rolls back PR #646 into 0.26.1.
=> 0.26: Added an easy way to print debug information for inclusion into issues

.travis.yml, Makefile, docs/intro.rst, tox.ini, zhmcclient/debuginfo.py
Rolls back PR #648 into 0.26.1.
=> 0.26: Improved and fixed debuginfo; using it in make

.travis.yml, Makefile, docs/intro.rst, tox.ini, zhmcclient/debuginfo.py
=> Improved and fixed debuginfo; using it in make

docs/changes.rst, examples/discover_storage_group.py, examples/example_hmccreds.yaml, zhmcclient/_storage_group.py
=> Fixes #623: Added discovery and connection report methods to StorageGroup

docs/changes.rst, zhmcclient/_version.py
=> Start 0.26.2

appveyor.yml, docs/changes.rst
=> Test: Fixed missing ffi.h file on CygWin when testing

.travis.yml, docs/changes.rst
=> Test: Running coveralls for all Python versions

docs/appendix.rst, docs/changes.rst
=> Fixed and added links to HMC books in Bibliography

dev-requirements.txt, docs/changes.rst, docs/conf.py, minimum-constraints.txt
=> Changed the theme of the documentation on RTD from classic to sphinx_rtd_theme

.travis.yml
=> Travis: Added jobs for s390x and ppc64le CPU architectures

dev-requirements.txt, minimum-constraints.txt
These changes partly come from experiences in other Python projects, which I am collecting in the https://github.com/andy-maier/cookiecutter-python repo..
=> Fixed dependencies for development

setup.py
=> Fixed broken Documentation link shown on Pypi

docs/conf.py, tests/common/utils.py, tests/end2end/test_activation_profiles.py, tests/end2end/test_cpc.py, tests/end2end/test_hmc_credentials_file.py, tests/end2end/test_hmc_definitions.py, tests/end2end/test_partition_lifecycle.py, tests/end2end/test_storage_group.py, tests/unit/tests/common/test_utils.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_idpool.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_utils.py
=> Third chunk of Pylint issue resolutions that were not errors

docs/changes.rst, tests/installtest/test_install.sh
=> Fixed issue where virtualenv on pypy3 created env one level higher

docs/changes.rst, tests/unit/zhmcclient/test_adapter.py, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_cpc.py
=> Added z15; Improved max partition detection

docs/changes.rst, zhmcclient/_version.py
=> Start 0.28.0

README.rst
=> Fixed Github Actions badge

minimum-constraints.txt
=> Fixed issue with new pip on coveralls link dependency

docs/changes.rst, docs/intro.rst
=> Docs: Added z15 to supported environments

docs/changes.rst, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_partition.py, zhmcclient_mock/_urihandler.py
=> Added partition.start_dump_program()

docs/changes.rst
=> Fixed change log for previous commit

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints.txt
See commit messages for details.
=> Recent updates from cookiecutter-python project

.pylintrc
=> Pylint: Ignored new issue 'consider-using-generator'

.pylintrc
=> Expanded Pylint naming rules

.github/workflows/test.yml
=> GitHub Actions: Pinned Ubuntu to 18.04 for Python 3.4

docs/changes.rst, zhmcclient/_exceptions.py, zhmcclient/_session.py
=> Improved logging and exc display for HTTP errors

docs/changes.rst, zhmcclient/_cpc.py, zhmcclient/_manager.py, zhmcclient/_metrics.py, zhmcclient/_session.py, zhmcclient/_utils.py, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient/testutils/hmc_definitions.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
=> Cut off low-level exceptions from traceback chain

docs/changes.rst, zhmcclient/_metrics.py
**Note: This PR is on top of PR #720**
This PR is related to issue https://github.com/zhmcclient/zhmc-prometheus-exporter/issues/113.
=> Improved the information in assertion errors in the metrics support

tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient/test_storage_group.py
=> Marked missing tests; changed test skipping to use pytest.skip

docs/appendix.rst, docs/changes.rst, docs/index.rst, docs/intro.rst, docs/resources.rst, zhmcclient/_storage_group.py
=> Docs: Fixed missing methods/attr tables; other small fixes

.github/workflows/test.yml
=> Moved Actions test run to SUN 04:00 UTC

docs/development.rst
=> Docs: Fixed incorrect repo link/name in development section

docs/changes.rst, zhmcclient/_exceptions.py, zhmcclient/_metrics.py
=> Improved the handling of resource not found errors during metrics processing

docs/changes.rst, zhmcclient/_session.py
=> Fixed HMC logging that was broken by an earlier commit

setup.py
=> Added link to Change Log to Pypi links

.github/workflows/notify.yml
No review needed - needs to be merged to activate.
=> Added notify workflow for posting test results to Slack

.github/workflows/notify.yml
=> Added setup instructions to notify workflow

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient version 0.29.0.
=> Release 0.29.0

docs/changes.rst, zhmcclient/_version.py
=> Start 0.30.0

README.rst
=> Fixed change log link in README

dev-requirements.txt, docs/changes.rst, docs/conf.py, docs/general.rst, docs/resources.rst, minimum-constraints.txt
=> Docs: Migrated from homegrown summary tables to autodocsumm

docs/changes.rst, docs/resources.rst, tests/unit/zhmcclient/test_capacity_group.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/__init__.py, zhmcclient/_capacity_group.py, zhmcclient/_cpc.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Added support for DPM Capacity Groups

docs/changes.rst, zhmcclient/_lpar.py
=> Added parameters to Lpar scsi methods; Fixed docs on default of Lpar scsi method

requirements.txt
=> Fixed install via setup.py on Python 2.7, 3.4, 3.5

docs/changes.rst, zhmcclient/_lpar.py
=> Fixed StatusTimeout when activating an LPAR

.github/workflows/test.yml, docs/changes.rst, requirements.txt, zhmcclient/_version.py
=> Release 0.30.0

docs/changes.rst, zhmcclient/_version.py
=> Start 0.31.0

README.rst, setup.py
=> Added py39 to supported envs; Changed README doc links to latest

docs/changes.rst, zhmcclient/_version.py
=> Start 0.31.1

docs/changes.rst, zhmcclient/_version.py
=> Release 0.30.1

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed install error for "pywinpty" on py27/windows

docs/changes.rst, tests/unit/zhmcclient/test_exceptions.py, zhmcclient/_exceptions.py, zhmcclient/_notification.py
=> Fixed and improved handling of JMS errors in NotificationReceiver

docs/changes.rst, tests/unit/zhmcclient/test_exceptions.py, zhmcclient/_exceptions.py, zhmcclient/_notification.py
Rolls back PR #771 into 0.30.2
=> 0.30: Fixed and improved handling of JMS errors in NotificationReceiver

docs/development.rst
=> Minor fixes in development docs for releasing a version

docs/changes.rst, zhmcclient/_session.py
=> Improved exception handling for HMC certificate failures

docs/changes.rst, zhmcclient/_session.py
**Note: This change should be tested to see if the error reoccurs, before it gets merged.**
=> Validated string type in request/reponse logging

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 0.31.0.
=> Release 0.31.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.0.0

docs/changes.rst, examples/metrics.py, zhmcclient/_metrics.py
=> Examples: Fixed errors in and improved metrics examples

docs/changes.rst, examples/metrics.py, zhmcclient/_metrics.py
Rolls back PR #789 into 0.31.1.
=> 0.31: Examples: Fixed errors in and improved metrics examples

tests/unit/zhmcclient/test_manager.py, tests/unit/zhmcclient/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_task.py, zhmcclient/_unmanaged_cpc.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_utils.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py
=> Cleanup: Moved the BaseManager methods to _utils module

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_console.py, zhmcclient/_manager.py, zhmcclient_mock/_urihandler.py
=> Added support for Console.list_permitted_partitions/_lpars()

docs/changes.rst, zhmcclient/_version.py
=> Renamed version 1.0.0 to 0.32.0

docs/changes.rst, zhmcclient/_lpar.py, zhmcclient/_partition.py
Rolls back PR #797 into 0.31.1.
=> 0.31: Docs: Fixed/added authorization reqs for Partition and Lpar methods

.pylintrc, docs/changes.rst, tests/end2end/test_partition_lifecycle.py, tests/end2end/test_storage_group.py, zhmcclient/_utils.py
=> Fixed issues raised by new Pylint version 2.9.1

.pylintrc, docs/changes.rst, tests/end2end/test_partition_lifecycle.py, tests/end2end/test_storage_group.py, zhmcclient/_utils.py
Rolls back PR #804 into 0.31.1.
=> 0.31: Fixed issues raised by new Pylint version 2.9.1

docs/changes.rst, zhmcclient/_version.py
No review needed, since this release just fixes docs errors.
=> Release 0.31.1

docs/changes.rst, zhmcclient/_console.py, zhmcclient/_manager.py
=> Optimized console to be locally built

zhmcclient/_manager.py
=> Improved recently added find_local()

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/intro.rst, minimum-constraints.txt, requirements.txt, setup.py, tox.ini, zhmcclient/_version.py
=> Dropped support for Python 3.4

docs/changes.rst, zhmcclient/_console.py
=> Fixed Keyrror when accessing se-version in list_permitted_xxx()

docs/changes.rst, tests/unit/zhmcclient/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py
No more open TODOs at this point.
=> Made read/write of properties dict in resource objects thread-safe

docs/changes.rst, zhmcclient/_version.py
=> Start 1.1.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.0.1

docs/changes.rst, setup.py
**Note: This PR is on top of PR #822 - do not merge before that one is merged**
=> Fixed maturity level from 4 (Beta) to 5 (Production/Stable)

docs/changes.rst, setup.py
**Note: This PR is on top of PR #823  - do not merge before that one is merged**
=> 1.0: Fixed maturity level from 4 (Beta) to 5 (Production/Stable)

docs/changes.rst, zhmcclient/_version.py
With fix for maturity level.
Kathir agreed to the release in Slack. No further review needed.
=> Release 1.0.1

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_cpc.py, zhmcclient_mock/_urihandler.py
Particular review point: Structure of the `auto_start_list` parameter of `Cpc.set_auto_start_list()`
=> Added support for the 'Set Auto-Start List' operation

docs/changes.rst
=> Added previous Lpar.stop() fix to change log

docs/changes.rst, zhmcclient/_version.py
=> Release 1.0.2

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed Sphinx doc build error on Python 2.7

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #853 into 1.0.4.
=> 1 .0: Fixed Sphinx doc build error on Python 2.7

docs/changes.rst, zhmcclient/_client.py
=> Fixed description of Client.get_inventory()

docs/changes.rst, zhmcclient/_cpc.py
=> Added Cpc.import_dpm_configuration() method

docs/changes.rst, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_task.py, zhmcclient/_unmanaged_cpc.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_utils.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py
=> Defined HMC resource class names centrally

docs/changes.rst, examples/example_hmccreds.yaml, examples/export_dpm_config.py, tests/unit/zhmcclient/test_exceptions.py, zhmcclient/_cpc.py, zhmcclient/_exceptions.py, zhmcclient/_utils.py
This PR needs to wait for discussion with the DPM team before being merged.
Nevertheless, it is ready for review and serious use.
=> Added Cpc.export_dpm_configuration() method

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of version 1.1.0.
Change log: https://github.com/zhmcclient/python-zhmcclient/blob/release_1.1.0/docs/changes.rst
=> Release 1.1.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.1.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.2.0

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt, setup.py, tests/installtest/test_install.sh, tox.ini, zhmcclient/_metrics.py, zhmcclient/_session.py
=> Added support for Python 3.10

Makefile, docs/changes.rst
Needed for Python 3.10 support.
=> Removed the ability to build the Windows executable

dev-requirements.txt, minimum-constraints.txt
=> Increased min version of virtualenv to fix issue on py27

Makefile, docs/changes.rst, tests/example_hmc_definitions.yaml, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient/testutils/hmc_definitions.py
=> End2end tests: Added verify_cert; Changed TESTHMCDIR to TESTHMCFILE

tests/end2end/test_activation_profiles.py, tests/end2end/test_cpc.py, tests/end2end/test_partition_lifecycle.py, tests/end2end/test_storage_group.py
=> End2end tests: Converted all tests to use HMC definition file

Makefile, tests/end2end/test_activation_profiles.py, tests/end2end/test_cpc.py
=> End2end tests: Improved CPC find/list tests

tests/end2end/test_activation_profiles.py, tests/end2end/test_cpc.py, zhmcclient/testutils/cpc_fixtures.py, zhmcclient/testutils/hmc_definition_fixtures.py
=> End2end tests: Improved CPC fixtures and used them

tests/end2end/test_activation_profile.py, tests/end2end/test_cpc.py, tests/end2end/utils.py
=> End2end tests: Moved common test functions into a new utils module

tests/end2end/test_activation_profile.py, tests/end2end/test_cpc.py, tests/end2end/test_hmc_credentials_file.py, tests/end2end/test_hmc_definitions.py, tests/end2end/test_partition.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_volume.py, tests/end2end/utils.py
=> End2end tests: Improved storage group/volume tests

Makefile, zhmcclient/testutils/hmc_definitions.py
=> End2end tests: Added coverage; simplified TESTHMC/FILE defaults

tests/end2end/test_nic.py, tests/end2end/test_storage_volume.py
=> End2end tests: Added NIC tests

.coveragerc.end2end, .gitignore, Makefile
=> End2end tests: split end2end coverage report from unit report

tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_volume.py
=> End2end tests: Added rename tests

docs/changes.rst, zhmcclient/_hba.py, zhmcclient/_nic.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_virtual_function.py
=> Fixed missing update of parent uris property in element delete

docs/changes.rst, zhmcclient/_hba.py, zhmcclient/_nic.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_virtual_function.py
=> 1.1: Fixed missing update of parent uris property in element delete

tests/end2end/test_activation_profile.py, tests/end2end/test_cpc.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_volume.py
=> End2end tests: Skipping testcase when no DPMs of desired type are provided

Makefile, tests/end2end/test_cpc.py, tests/end2end/test_hmc_definitions.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/utils.py, tests/example_hmc_definitions.yaml
=> End2end tests: Several fixes and improvements

tests/end2end/test_hba.py, tests/end2end/utils.py
=> End2end tests: Added tests for HBAs without stomgmt feature

tests/end2end/test_adapter.py, tests/end2end/test_hba.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_volume.py, tests/end2end/utils.py
=> End2end tests: Added tests for adapters; fixes

tests/end2end/test_capacity_group.py
=> End2end tests: Added tests for capacity groups

tests/end2end/test_port.py
=> End2end tests: Added tests for adapter ports

tests/end2end/test_ldap_server_definition.py, tests/end2end/utils.py
=> End2end tests: Added tests for LDAP Server Definitions; added TestWarning

tests/end2end/test_capacity_group.py, tests/end2end/test_cpc.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_port.py
=> End2end tests: Fixes in CPC, LDAP, CapGrp testing

tests/end2end/test_port.py, tests/end2end/test_storage_volume.py
=> End2end tests: Fixes for ports, storage volumes

tests/end2end/test_password_rule.py
=> End2end tests: Added tests for password rules; LDAP Srv Def editorial

tests/end2end/test_cpc.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py
=> End2end tests: Added tests for users, patterns, roles, tasks; Fixed auth handling

tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py
=> End2end tests: Added tests for virtual functions + switches

tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_virtual_function.py
=> End2end tests: Fixes in user/pattern/vfunc tests

docs/changes.rst, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, zhmcclient/_storage_volume_template.py
=> End2end tests: Added tests for storage grp/vol templates

tests/end2end/test_user.py
=> End2end tests: Replaced creation of pwrule in user test with picking Basic

tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_hba.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_password_rule.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py
=> End2end tests: Randomized choice of object used for test

tests/end2end/test_lpar.py
=> End2end tests: Added tests for LPARs

tests/end2end/test_console.py
=> End2end tests: Added tests for the console

docs/changes.rst, zhmcclient_mock/_urihandler.py
=> Fixes in mock support for "Update LPAR Properties"

docs/changes.rst
=> 1.1: Fixed changelog for fixes in mock support for 'Update LPAR'

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #868 into 1.1.1.
=> 1.1: Increased min version of virtualenv to fix issue on py27

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, zhmcclient/_version.py
=> Release 1.1.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.1.2

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_cpc.py, zhmcclient_mock/_urihandler.py
=> Added support for activate/deactivate CPC in classic mode

Makefile, dev-requirements.txt, docs/changes.rst, docs/intro.rst, minimum-constraints.txt, tests/installtest/test_install.sh
=> Removed documentation and use of 'setup.py' commands

docs/changes.rst, docs/mocksupport.rst, zhmcclient_mock/_hmc.py
=> Doc fixes in mock support

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Mock support: Fixes for storage groups and added support for storage volumes

docs/changes.rst, docs/mocksupport.rst, zhmcclient_mock/_hmc.py
=> 1.1: Doc fixes in mock support

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> 1.1: Mock support: Fixes for storage groups and added support for storage volumes

docs/changes.rst, zhmcclient_mock/_urihandler.py
=> Mock support: Fixed operations on activation profiles in DPM mode

docs/changes.rst, zhmcclient_mock/_urihandler.py
Rolls back PR #925 into 1.1.2.
=> 1.1: Mock support: Fixed operations on activation profiles in DPM mode

zhmcclient_mock/_hmc.py
Rolls back PR #929 into 1.1.2.
=> 1.1: Mock support: Second fix for automatic mgmt of storage-volume-uris

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Mock support: Fixed list of properties returned by "List Adapters of CPC"

dev-requirements.txt, minimum-constraints.txt
=> Fixed version of pywinpty for Python >=3.5

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #935 into 1.1.2.
=> 1.1: Fixed version of pywinpty for Python >=3.5

dev-requirements.txt, docs/changes.rst
=> Fixed installation of pywinpty

dev-requirements.txt, docs/changes.rst
Rolls back PR #938 into 1.1.2.
=> 1.1: Fixed installation of pywinpty

README.rst, docs/changes.rst, docs/intro.rst
=> Docs: Faster example in readme and intro

docs/changes.rst, zhmcclient/_session.py
=> Fixed message of exceptions re-raised from request exceptions

design/lpar-status.md
Link to the LPAR status design document in this PR: https://github.com/zhmcclient/python-zhmcclient/blob/andy/lpar-status-design/design/lpar-status.md
=> Added design doc for LPAR status

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 1.2.0.
=> Release 1.2.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.3.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.2.2

docs/changes.rst, zhmcclient/_notification.py
=> Fixed handling of notifications with no content

docs/changes.rst, zhmcclient/testutils/hmc_definitions.py
This addresses items 2 and 3 from issue #950.
=> Improvements in end2end testing

docs/changes.rst, docs/development.rst, zhmcclient/testutils/cpc_fixtures.py, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient/testutils/hmc_definitions.py
This addresses item 1 from issue #950 .
=> Improved and fixed documentation for testing and HMC definition file handling

docs/changes.rst, zhmcclient/_notification.py
=> 1.2: Fixed handling of notifications with no content

docs/changes.rst
=> Fixed changelog from previous commit

docs/changes.rst, tests/end2end/test_user.py
=> End2end test: Made user test tolerant against missing password rule 'Basic'

tests/end2end/test_cpc.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_password_rule.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py
=> Cleaned up SE/HMC version checks in end2end tests

tests/end2end/test_cpc.py
=> Cleaned up CPC display in CPC end2end tests

tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py
=> Cleaned up CPC mode related skip messages in end2end tests

zhmcclient/testutils/_hmc_definition_fixtures.py
=> Increased read timeout in end2end tests to 300 sec

tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py
=> Cleaned up CPC skip messages

tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_hmc_definition_file.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_password_rule.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py, tests/end2end/utils.py
=> Minor improvements in end2end test messages and warnings

tests/common/utils.py, tests/end2end/test_hmc_definition_file.py
=> Minor improvements in end2end test messages; enabled test_hmcdef_check_all_hmcs

zhmcclient/testutils/_cpc_fixtures.py
=> Improved docs for CPC fixtures; removed one_cpc() fixture

tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py
=> Improved skips in end2end tests

setup.py
=> Fixed missing inclusion of testutils into package

docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 1.2.2.
=> Release 1.2.2

docs/changes.rst, examples/export_dpm_config.py, zhmcclient/_client.py, zhmcclient/_cpc.py
For details, see commit message
Please don't merge until all reviewers have reviewed.
=> Removed empty fields in exported DPM config; other inventory improvements

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 1.3.0.
=> Release 1.3.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.3.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.4.0

docs/changes.rst, tests/unit/zhmcclient/test_user.py, tests/unit/zhmcclient/testutils/test_hmc_definitions.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_resource_updater.py, zhmcclient/testutils/_hmc_definition.py, zhmcclient/testutils/_hmc_definition_fixtures.py, zhmcclient/testutils/_hmc_definitions.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
=> Fixed filepath AttributeError when using testutils with mocked envs

docs/changes.rst, tests/unit/zhmcclient/test_user.py, tests/unit/zhmcclient/testutils/test_hmc_definitions.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_resource_updater.py, zhmcclient/testutils/_hmc_definition.py, zhmcclient/testutils/_hmc_definition_fixtures.py, zhmcclient/testutils/_hmc_definitions.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1001 into 1.3.1
=> 1.3: Fixed filepath AttributeError when using testutils with mocked envs

docs/changes.rst, zhmcclient/_version.py
=> Start 1.3.2

docs/changes.rst, zhmcclient_mock/_urihandler.py
Rolls back PR #1013 into 1.3.2
=> 1.3: Improved mock support for password rules by creating default properties

docs/changes.rst, zhmcclient_mock/_urihandler.py
=> Added default properties to UserRole creation

docs/changes.rst, zhmcclient_mock/_urihandler.py
Rolls back PR #1020 into 1.3.2.
=> 1.3: Added default properties to UserRole creation

docs/changes.rst, zhmcclient/_user_role.py
Rolls back PR #1015 into 1.3.2
=> 1.3: Fixed permission_add/remove methods in UserRole

tests/unit/zhmcclient/test_user_role.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Fixed default properties of UserRole creation in mock support

docs/changes.rst, zhmcclient/_version.py
=> Release 1.3.2

docs/changes.rst, examples/list_cpcs.py
=> Added an example script 'list_cpcs.py'

docs/changes.rst, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Improved mock support for Create Partition operation

docs/changes.rst, zhmcclient/_session.py
Rolls back PR #1033 into 1.3.3.
=> 1.3: Improved waiting for job of asynchronous operation

docs/changes.rst, zhmcclient/_session.py
=> Improved waiting for job of asynchronous operation

docs/changes.rst, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1035 into 1.3.3
=> 1.3: Added missing properties in mock support for partitions

docs/changes.rst, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Added missing properties in mock support for partitions

docs/changes.rst, zhmcclient/_version.py
=> Release 1.3.3

docs/changes.rst, zhmcclient/_version.py
=> Start 1.3.4

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_lpar.py, zhmcclient_mock/_urihandler.py
=> Added mock support for Lpar.scsi_load/dump()

Makefile, docs/changes.rst, docs/intro.rst, zhmcclient/__init__.py, zhmcclient/_debug_info.py, zhmcclient/_logging.py, zhmcclient/_utils.py
=> Improved debug info; Cleaned up zhmcclient namespace

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_lpar.py, zhmcclient_mock/_urihandler.py
=> Added NVME Load/Dump support for LPARs (classic mode)

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
=> Release 1.4.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.4.1

.pylintrc
=> Pylint: Increased max num ber of instance attrs

.pylintrc
=> 1.4: Pylint: Increased max num ber of instance attrs

.github/workflows/test.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed a flake8 AttributeError by pinning importlib-metadata

docs/changes.rst, zhmcclient/_virtual_storage_resource.py
=> Fixed AttributeError in the VirtualStorageResource.adapter_port property

docs/changes.rst, zhmcclient/_virtual_storage_resource.py
Rolls back PR #1060 into 1.4.1.
=> 1.4: Fixed AttributeError in the VirtualStorageResource.adapter_port property

docs/changes.rst, tests/end2end/test_adapter.py, zhmcclient/_adapter.py
Needed for https://github.com/zhmcclient/zhmccli/issues/110
=> Added method Adapter.list_assigned_partitions()

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_lpar.py, zhmcclient_mock/_urihandler.py
=> Added Lpar.reset_normal() and added os_ipl_token to Lpar.reset_clear()

docs/appendix.rst
=> Added z16 documentation to appendix

.github/workflows/publish.yml, docs/changes.rst
=> Simplified package release process (2)

.github/workflows/publish.yml, docs/development.rst
=> Simplified release process (3)

.github/workflows/test.yml, docs/changes.rst
=> Accomodated Ubuntu 22.04 being default in Github Actions

.github/workflows/publish.yml, docs/development.rst
=> Fixes in development docs and publish workflow

dev-requirements.txt, minimum-constraints.txt
=> Fixed Python versions of pylint dependents

docs/changes.rst, docs/intro.rst
Note: This PR was triggered by issue https://github.com/zhmcclient/zhmccli/issues/332. The other zhmcclient projects have or will have PRs with the same change, after this PR has been reviewed and approved.
=> Docs: Added a section 'Setting up firewalls or proxies'

docs/appendix.rst, docs/intro.rst
TODOs:
* The discussion on the term "HMC GUI" needs to be resolved.
=> Added trouble shooting info for no connectivity

docs/changes.rst, zhmcclient/_version.py
As discussed in our call today, no further review needed.
=> Release 1.6.0

Makefile, minimum-constraints.txt, requirements.txt
=> Upgraded pip versions

Makefile, minimum-constraints.txt, requirements.txt
Rolls back PR #1099 into 1.6.1.
=> 1.6: Upgraded pip versions

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/intro.rst, extra-testutils-requirements.txt, minimum-constraints.txt, setup.py
=> Added check for missing dependencies; New extra 'testutils'

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/intro.rst, extra-testutils-requirements.txt, minimum-constraints.txt, setup.py
Rolls back PR #1099 into 1.6.1.
=> 1.6: Added check for missing dependencies; New extra 'testutils'

.github/workflows/test.yml, .safety-policy.yml, Makefile, dev-requirements.txt, minimum-constraints.txt
=> Added safety to Makefile and Actions test workflow

.github/workflows/test.yml, docs/changes.rst
=> Added missing test environments to weekly tests

.github/workflows/test.yml, .safety-policy.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Addressed safety issues and required it to pass

Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Added more tools to and fixed exit code of check_reqs dependency checking

.safety-policy.yml
=> Addressed new safety issues reported on 3/17

minimum-constraints.txt
=> Added dependency to nose needed by notebook 4.3.1

docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 1.7.0 to Pypi.
=> Release 1.7.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.7.1

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints.txt, setup.py, tox.ini
=> Added support for Python 3.11

docs/development.rst
No review needed - the same change was reviewed as part of PR https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/304
=> Improved and fixed developer description of releasing/starting a version

.whitesource
=> Removed disabling of issue creation by whitesource Mend

minimum-constraints.txt
=> Upgraded min version of mistune to 0.8.4

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Does not yet address the coveralls delivery issue.
=> Addressed safety issues

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1139 into 1.7.1
=> 1.7: Addressed safety issues

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints.txt
Rolls back PR #1138 into 1.7.1.
=> 1.7: Fixed coveralls issues with KeyError and HTTP 422 Unprocessable Entity

docs/changes.rst, tests/unit/zhmcclient/test_console.py, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient/test_password_rule.py, tests/unit/zhmcclient/test_task.py, tests/unit/zhmcclient/test_unmanaged_cpc.py, tests/unit/zhmcclient/test_user.py, tests/unit/zhmcclient/test_user_pattern.py, tests/unit/zhmcclient/test_user_role.py, zhmcclient/_console.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_password_rule.py, zhmcclient/_task.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py
**Note: This PR contains an incompatible change. Please review the change log for that.**
=> Changed default for full_properties=False in list()

docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmcclient/_session.py
=> Changed urllib3.Retry.method_whitelist to allowed_methods

Makefile, docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmcclient/_session.py
=> PACKAGE_LEVEL in .done files; Added more files to clobber

Makefile, docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmcclient/_session.py
Rolls back PR #1148 into 1.7.1.
=> 1.7: PACKAGE_LEVEL in .done files; Added more files to clobber

docs/changes.rst
=> Fixed RTD issue with OpenSSL by adding config file

.readthedocs.yaml
=> Fixed previous PR for RTD build - added config file

examples/list_partitions_partial_and_full.py
This PR was split out of PR #331 in order to be able to compare the elapsed times with and without PR #331.
=> Added example script list_partitions_partial_and_full.py

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Fixed depedency issues

docs/changes.rst, requirements.txt, zhmcclient/_session.py
=> Fixed urllib3 minimum version

docs/changes.rst, requirements.txt, zhmcclient/_session.py
Rolls back PR #1168 into 1.7.3.
=> 1.7: Fixed urllib3 minimum version

docs/changes.rst, zhmcclient/_version.py
=> Release 1.7.3

docs/changes.rst, tests/end2end/test_adapter.py, zhmcclient/_adapter.py
* Is "sibling" an appropriate term for the other adapters on the same card
=> Added list_sibling_adapters() method to Adapter class

docs/appendix.rst, docs/changes.rst, docs/resources.rst, tests/end2end/test_group.py, tests/end2end/utils.py, tests/unit/zhmcclient/test_group.py, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_group.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
* Should the `groups` property providing the GroupManager object be in the Client object (as currently in this PR) or in the Console object?
=> Added support for Group resources

docs/appendix.rst, docs/changes.rst, docs/concepts.rst, docs/resources.rst, tests/end2end/test_certificates.py, tests/end2end/test_console.py, tests/end2end/test_cpc.py, tests/end2end/utils.py, zhmcclient/__init__.py, zhmcclient/_activation_profile.py, zhmcclient/_certificates.py, zhmcclient/_client.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_utils.py, zhmcclient/_version.py
No review needed - has been reviewed on internel repo
=> Merge changes for z16 GA1.5

minimum-constraints.txt, requirements.txt
=> Fixed pyrsistent 0.15.0 issue on Windows with py27 min

docs/changes.rst, zhmcclient/_version.py
Please approve the release of version 1.8.0 to Pypi.
=> Release 1.8.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.9.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.8.1

docs/changes.rst, zhmcclient/_session.py, zhmcclient_mock/_session.py
These fixes are needed for issues https://github.com/zhmcclient/zhmccli/issues/421 and https://github.com/zhmcclient/zhmc-prometheus-exporter/issues/336.
=> Fixed session logon, logoff and automatic renewal

docs/changes.rst, zhmcclient/_session.py, zhmcclient_mock/_session.py
Rolls back PR #1184 into 1.8.1.
=> 1.8: Fixed session logon, logoff and automatic renewal

docs/changes.rst, zhmcclient/_version.py
=> Release 1.8.1

.github/workflows/test.yml, docs/changes.rst
=> Circumvented the removal of Python 2.7 from setup-python

.github/workflows/test.yml, docs/changes.rst
Rolls back PR #1191 into 1.8.2.
=> 1.8: Circumvented the removal of Python 2.7 from setup-python

.safety-policy.yml, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Addressed safety issues from 6/2023

docs/changes.rst, zhmcclient/_session.py
=> Fixes for HMC restart and session logoff

docs/changes.rst, zhmcclient/_session.py
Rolls back PR #1195 into 1.8.2.
=> 1.8: Fixes for HMC restart and session logoff

docs/changes.rst, zhmcclient/_version.py
=> Release 1.8.2

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1199 into 1.8.3
=> 1.8: Fixed safety issues 7/2023

.github/ISSUE_TEMPLATE/bug_report.md, docs/changes.rst
=> Fixed bug issue template by correcting command to display debug data

docs/changes.rst, tests/unit/zhmcclient/test_notification.py, zhmcclient/_exceptions.py, zhmcclient/_notification.py
Needed for the OS Message Forwarder.
=> Added dynamic subscription mgmt to NotificationReceiver

docs/development.rst
=> Fixed link to 'publish' workflow in release description

docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Fixed PyYAML install issue since release of Cython 3

docs/changes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #1209 into 1.9.1.
=> 1.9: Fixed PyYAML 5.4 install issue since release of Cython 3

.safety-policy.yml
=> Fixed safety issues from 7/17

.safety-policy.yml
Rolls back PR #1211 into 1.9.1
=> 1.9: Fixed safety issues from 7/17

docs/development.rst
=> Fixed link in release docs

docs/changes.rst, examples/example_hmc_inventory.yaml, examples/example_hmc_vault.yaml
=> Fixed missing entries for example mocked environments in example vault file

tests/end2end/test_hmc_inventory.py
=> Disabled end2end test test_hmcdef_check_all_hmcs()

docs/changes.rst, zhmcclient/_console.py, zhmcclient/_cpc.py
=> Added support for upgrading HMC and SE

docs/changes.rst, zhmcclient/_client.py
=> Fixed new issue reported by flake8 6.1.0

docs/changes.rst, zhmcclient/_client.py
Rolls back PR #1222 into 1.9.2.
=> 1.9: Fixed new issue reported by flake8 6.1.0

docs/changes.rst, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_certificates.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_group.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_metrics.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_session.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py, zhmcclient_mock/_session.py
=> Added resource class and name to HMC log entries

docs/changes.rst, docs/resources.rst, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_cpc.py
=> Support for STP configuration of CPCs

docs/changes.rst, zhmcclient/_version.py
=> Start 1.10.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.11.0

docs/changes.rst, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Fixed zhmcclient_mock support for LDAP Server Definitions

docs/changes.rst, zhmcclient/_notification.py
=> Fixed SubscriptionNotFound exception message

docs/changes.rst, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
=> Implemented mock support for bulk operations

docs/changes.rst, tests/unit/zhmcclient/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_certificates.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_group.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_task.py, zhmcclient/_unmanaged_cpc.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_utils.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py
This is needed for https://github.com/zhmcclient/zhmc-ansible-modules/issues/651
=> Support for requesting additional properties in list() methods

docs/changes.rst, tests/unit/zhmcclient/test_virtual_function.py, tests/unit/zhmcclient/test_virtual_switch.py, zhmcclient/_manager.py
=> Optimized list() methods with full properties using bulk operations

docs/changes.rst, tests/common/utils.py, tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_certificates.py, tests/end2end/test_partition.py, tests/end2end/test_virtual_switch.py, tests/end2end/utils.py, tests/unit/zhmcclient/test_activation_profile.py, tests/unit/zhmcclient/test_adapter.py, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient/test_virtual_switch.py, zhmcclient/_activation_profile.py, zhmcclient/_console.py, zhmcclient/_manager.py, zhmcclient_mock/_urihandler.py
=> Fixed and improved support and tests for list() with additional_properties

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed safety issues from 2023-09-15; Added ruamel.yaml dev dependency

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1267 into 1.11.1
=> 1.11: Fixed safety issues from 2023-09-15; Added ruamel.yaml dev dependency

docs/changes.rst, zhmcclient_mock/_urihandler.py
=>  Improved mocked Hipersocket adapters

docs/changes.rst, tests/end2end/test_lpar.py, tests/end2end/test_partition.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
Adds the code and end2end tests, but no mock support.
=> Added support for 'List OS Messages' in DPM+classic mode

tests/end2end/test_adapter.py, zhmcclient/_console.py, zhmcclient/_manager.py
=> Added Console.list_permitted_adapters()

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed safety issues up to 2023-10-05

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1287 into 1.11.3.
=> 1.11: Fixed safety issues up to 2023-10-05

docs/intro.rst, zhmcclient/_certificates.py, zhmcclient/_console.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
=> Fixed doc build errors and warnings

docs/intro.rst, zhmcclient/_certificates.py, zhmcclient/_console.py
Rolls back PR #1289 into 1.11.3.
=> 1.11: Fixed doc build errors and warnings

docs/changes.rst, examples/get_partition_properties_filter.py, tests/unit/zhmcclient/test_adapter.py, tests/unit/zhmcclient/test_resource.py, zhmcclient/_partition.py, zhmcclient/_resource.py, zhmcclient_mock/_urihandler.py
**Note: This PR is on top of PR https://github.com/zhmcclient/python-zhmcclient/pull/1285 - review only the commit with the same title as this PR**
=> Added example script for partition.pull_properties()

.github/workflows/test.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, setup.py, tox.ini
=> Added support for Python 3.12

tests/end2end/utils.py
Needed for an upcoming PR that adds end2end testcases for LPARs.
Major review points:
* Description of status value meanings in `pull_lpar_status()`: https://github.com/zhmcclient/python-zhmcclient/pull/1302/files#diff-cb055a90f6c2a554d629e2c22aaec5309385084fee4cfa346b067c228f004395R804
=> End2end tests: Logging support; LPAR related support

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
=> Fixed waiting for LPAR status in Lpar.activate()

.github/workflows/test.yml
=> Changed Python 3.7 test runs to use minimum package levels

docs/changes.rst, zhmcclient/_version.py
=> Release 1.11.3

docs/changes.rst, zhmcclient/_version.py
=> Start 1.11.4

tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
=> Fixed status to wait for in SSC activation

tests/end2end/test_lpar.py, tests/end2end/utils.py
=> Improved end2end testcases for LPAR activate

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Addressed safety issues up to 2023-11-05

.safety-policy.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #1331 into 1.11.5.
=> 1.11: Addressed safety issues up to 2023-11-05

docs/changes.rst, tests/unit/zhmcclient/test_exceptions.py, zhmcclient/_exceptions.py
This will be needed for the ibm_zhmc Ansible collection.
=> Support for passing a message directly to the NotFound exception

tests/unit/zhmcclient/test_exceptions.py
This is needed to fix the Travis runs on the other PRs.
=> Fixed a unit test for the NotFound exception

design/lpar-status.md
A direct link to the updated document is: https://github.com/zhmcclient/python-zhmcclient/blob/andy/update-activate-load/design/lpar-status.md
=> Updated design description of LPAR activation/load for new 2.16 features

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_session.py, zhmcclient/_storage_group.py
=> Added job mgmt; Removed async support in Cpc.import/export_profiles()

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
=> Added Lpar.start()

docs/changes.rst, zhmcclient/_version.py
=> Release 1.12.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.12.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.13.0

docs/changes.rst, zhmcclient/_version.py
The original PR targeted the wrong branch - retrying.
=> Start 1.12.1 - try2

.safety-policy.yml, minimum-constraints.txt, requirements.txt
Rolls back the corresponding change (which did not have a PR) from master.
=> 1.12: Safety issues from 2023-11-20

.safety-policy.yml, docs/changes.rst
=> Safety issues up to 2023-11-22

docs/changes.rst, zhmcclient/_console.py, zhmcclient/_cpc.py
=> Added support for retrievel of firmware from an FTP server

docs/changes.rst, zhmcclient/_console.py, zhmcclient/_cpc.py
Rolls back PR #1342 into 1.12.1.
=> 1.12: Added support for retrievel of firmware from an FTP server

docs/changes.rst, zhmcclient/_version.py
=> Release 1.12.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.12.2

.safety-policy.yml, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1358 into 1.12.2
=> 1.12: Addressed safety issues up to 2023-11-26

docs/changes.rst, zhmcclient/_session.py
Rolls back PR #1365 into 1.12.2.
=> 1.12: Tolerate restarts while waiting for job completion

docs/changes.rst, zhmcclient/_version.py
=> Release 1.12.2

docs/changes.rst
No review needed - this updates the change log with the change in PR #1346.
=> Added change log entry for added session_credential property

docs/changes.rst, tests/end2end/test_activation_profile.py, tests/end2end/utils.py
=> Fixed end2end testcase 'test_actprof_crud()'

zhmcclient/_cpc.py
For discussion which way to go, see issue #1373.
=> Changed ec_levels parm of Cpc.install_and_activate()

docs/changes.rst, tests/common/utils.py, tests/end2end/test_auto_update.py, tests/end2end/utils.py, tests/unit/zhmcclient/test_manager.py, tests/unit/zhmcclient/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_certificates.py, zhmcclient/_group.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_virtual_function.py
* The incompatibilities listed in the change log
This PR was tested with the end2end tests on T224 (DPM mode) and A01 (classic mode).
Result: On T224, all tests passed. On A01, some tests unrelated to the changes in this PR failed. Created issues #1375 and #1374 for those.
=> Regexp support for name filtering in find() and findall()

zhmcclient/testutils/_hmc_definitions.py
=> Fixed make end2end_show when specifying multiple HMCs in inv.file

docs/changes.rst, zhmcclient/_version.py
=> Release 1.13.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.14.0

docs/changes.rst, zhmcclient/_version.py
=> Start 1.13.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.12.4

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/conf.py, minimum-constraints.txt
=> Fixed Sphinx / sphinxcontrib-applehelp version issue

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/conf.py, minimum-constraints.txt
Rolls back PR #1397 into 1.13.1
=> 1.13: Fixed Sphinx / sphinxcontrib-applehelp version issue

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, docs/conf.py, minimum-constraints.txt
Rolls back PR #1397 into 1.12.4.
=> 1.12: Fixed Sphinx / sphinxcontrib-applehelp version issue

examples/list_partitions_filtered.py
=> Added example script for partiotn list with name filtering

docs/changes.rst, tests/unit/zhmcclient/test_manager.py, zhmcclient/_manager.py, zhmcclient/_utils.py
Rolls back PR #1403 into 1.13.1
=> 1.13: Undo regexp matching of name in find(); Fixed case insensitive regexp matching

docs/changes.rst, zhmcclient/_version.py
I will yank version 1.12.3 on Pypi after 1.12.4 is released.
=> Release 1.12.4

docs/changes.rst, zhmcclient/_version.py
I will yank version 1.13.0 on Pypi after 1.13.1 is released.
=> Release 1.13.1

docs/changes.rst, zhmcclient/_version.py
=> Start 1.13.2

Makefile, dev-requirements.txt
=> Fixed dependency issue with safety; Added minimum-constraints to targets

docs/changes.rst, tests/common/utils.py, zhmcclient/_console.py, zhmcclient/_manager.py, zhmcclient_mock/_urihandler.py
End2end tests:
* Ran make end2end on T224, which passed.
=> Fixed additional_properties in list_permitted_lpars() and mock support

docs/changes.rst, tests/common/utils.py, zhmcclient/_console.py, zhmcclient/_manager.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1410 into 1.13.2.
=> 1.13: Fixed additional_properties in list_permitted_lpars() and mock support

docs/changes.rst
=> Added missing change log entry for PR #1413

docs/changes.rst, zhmcclient/_console.py
Rolls back PR #1419 into 1.13.3.
=> 1.13: Fixed performance issue in list_permitted_lpars/partitions()

.github/workflows/test.yml, docs/changes.rst
=> Increased versions of GitHub Actions plugins for node 20

docs/changes.rst, tests/end2end/test_lpar.py, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_console.py, zhmcclient/_resource.py
Rolls back PR #1423 into 1.13.3.
=> 1.13: Added CPC related properties to list_permitted_lpars/partitions(); improved pull

docs/changes.rst, zhmcclient/_version.py
=> Release 1.13.3

docs/changes.rst, zhmcclient/_version.py
=> Start 1.13.4

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_cpc.py
=> Fixed the 'Cpc.delete_retrieved_internal_code()' method ec_level

docs/changes.rst, zhmcclient/_version.py
=> Release 1.13.4

docs/changes.rst, zhmcclient/_version.py
=> Start 1.13.5

docs/changes.rst, docs/development.rst, zhmcclient/_version.py
=> Release 1.14.0

.safety-policy-all.yml, .safety-policy-install.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed issue with ignoring unpinned reqs with safety 3.0 and made that minimum

docs/changes.rst, zhmcclient/_auto_updater.py, zhmcclient/_timestats.py, zhmcclient_mock/_idpool.py
=> Addressed new issues raised by Pylint 3.1

docs/changes.rst, zhmcclient/_auto_updater.py, zhmcclient/_timestats.py, zhmcclient_mock/_idpool.py
Rolls back PR #1454 into 1.14.1.
=> 1.14: Addressed new issues raised by Pylint 3.1

.safety-policy-install.yml, Makefile, docs/changes.rst, minimum-constraints-install.txt, minimum-constraints.txt
=> Improved safety run for install to use exact minimum versions

.github/workflows/test.yml, Makefile, docs/changes.rst, docs/development.rst
=> Safety run for all dependencies now must succeed when releasing

.safety-policy-all.yml, .safety-policy-install.yml, minimum-constraints.txt
=> Reduced safety ignore rules to minimum

dev-requirements.txt, extra-testutils-requirements.txt, minimum-constraints-install.txt, minimum-constraints.txt, requirements.txt
=> Clarified comments and removed licenses in req/constraints files

.safety-policy-all.yml, .safety-policy-install.yml
=> Clarified comments in safety policy files

minimum-constraints.txt
Rolls back PR #1467 into 1.14.1.
=> 1.14: Fixed missing deps of typer package

.github/workflows/test.yml, .safety-policy-install.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints-install.txt, minimum-constraints.txt, requirements.txt, tests/end2end/test_lpar.py, tests/end2end/utils.py, tests/installtest/test_install.sh, tests/unit/tests/common/test_utils.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_auto_updater.py, zhmcclient/_lpar.py, zhmcclient/_metrics.py, zhmcclient/_notification.py, zhmcclient/_partition.py, zhmcclient_mock/_urihandler.py
=> Fixed Python 3.5 issue, safety issues, new Pylint issues

.github/workflows/test.yml
=> Improved circumvention for pip cert issue on Python 3.5

.github/workflows/publish.yml, .github/workflows/test.yml, changes/1483.fix.rst
=> Upgraded Github actions plugin actions/github-script to v7

changes/1498.feature.rst, docs/notifications.rst, zhmcclient/_auto_updater.py, zhmcclient/_notification.py, zhmcclient/_utils.py
=> Added support for STOMP retry/timeout/heartbeat configuration

changes/1499.notshown.rst, tests/unit/zhmcclient/test_notification.py, zhmcclient/_auto_updater.py, zhmcclient/_notification.py, zhmcclient/_utils.py
=> Fixed checking for whether stomp.py uses Frames

changes/noissue.1.cleanup.rst, tests/unit/zhmcclient/test_utils.py, zhmcclient_mock/_urihandler.py
=> Fixed new issues reported by new flake8 7.0.0

Makefile, changes/1532.cleanup.rst, changes/1532.feature.rst, changes/1533.feature.rst, dev-requirements.txt, docs/development.rst, minimum-constraints-develop.txt
=> New make targets 'release' and 'start'; Dropped make target 'upload'

Makefile, changes/noissue.2.cleanup.rst
=> Dev: Changed the outdated 'py.test' command name to 'pytest'

changes/noissue.1.feature.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_inventory.yaml, tests/end2end/mocked_vault.yaml
No review needed - file is copied from zhmc ansible project.
=> Added z14 mock file to end2end tests

changes/noissue.5.notshown.rst, tests/end2end/mocked_hmc_z14.yaml
=> Fixed missing 'description' properties in test/end2end mock file for z14

changes/noissue.4.fix.rst, tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_console.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_password_rule.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py, tests/end2end/utils.py
=>  Mock: Consolidated the different assumptions in the zhmcclient mock support

changes/1548.fix.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml, zhmcclient_mock/_urihandler.py
=> Fixed errors in the mock support and its end2end_mock tests

changes/1248.feature.rst, tests/unit/zhmcclient/test_client.py, zhmcclient_mock/_urihandler.py
=> Mock support for "Get Inventory" operation

changes/noissue.5.fix.rst, minimum-constraints-install.txt, requirements.txt
=> Addressed safety issues up to 2024-06-21

changes/1541.feature.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Added mock support for Storage Group Templates and their Volumes

changes/noissue.1.cleanup.rst, changes/noissue.5.fix.rst, docs/changes.rst, zhmcclient/_version.py
=> Release 1.16.2

.readthedocs.yaml, changes/1559.notshown.3.rst
=> Third fix for RTD issue: Add requirements.txt to python.install config

.github/workflows/test.yml, changes/1526.feature.rst
=> Added 'make ruff' to test workflow

changes/noissue.6.notshown.rst, minimum-constraints-install.txt, requirements.txt
=> Fixed version of 'requests' package in dependencies (was too high)

changes/1567.cleanup.rst
=> Reduce versions in the generated docs

changes/1567.notshown.rst, docs/development.rst
=> Added release step to hide previous fix version on RTD

changes/1247.feature.rst, tests/end2end/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=>  Mock support for "Get Partitions Assigned to Adapter"

changes/1565.feature.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml, tests/end2end/test_virtual_storage_resource.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
=> Mock support for Storage Group VSRs

Makefile, changes/noissue.3.feature.rst
=>  Enabled checking for success of end2end_mocked again

changes/1581.fix.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml, tests/end2end/test_user_pattern.py, tests/unit/zhmcclient/test_user_pattern.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
=> Fixed mock support for create user pattern

Makefile, docs/development.rst
=> Improved 'make release' to allow repetiton in case of failures

minimum-constraints-develop.txt
=> Addressed safety issues for development up to 2024-07-11

changes/noissue.safety.fix.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
=> Addressed safety issues up to 2024-07-21

changes/noissue.safety.fix.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
Rolls back PR #1593 into 1.17.1.
=> 1.17: Addressed safety issues up to 2024-07-21

Makefile, base-requirements.txt, minimum-constraints-install.txt, pyproject.toml
=> Cleaned up Makefile

Makefile, base-requirements.txt, minimum-constraints-install.txt, pyproject.toml
Rolls back PR #1595 into 1.17.1.
=> 1.17: Cleaned up Makefile

changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt
=> Addressed safety issues; Added missing psutil dependency to dev

Makefile, changes/noissue.1.incompatible.rst
=> Changed make install to install in non-editable mode

Makefile, changes/noissue.3.cleanup.rst, changes/noissue.4.cleanup.rst, docs/development.rst
=> Dev: Relaxed the conditions when safety issues are tolerated

changes/noissue.5.cleanup.rst, docs/development.rst
=> Added release step to check and fix dependabot alerts

Makefile, docs/development.rst
=> Simplified publishing of a version

docs/development.rst
=> Simplified release/start instructions by removing shell variables

base-requirements.txt, changes/noissue.safety.fix.rst, minimum-constraints-install.txt, pyproject.toml
Rolls back PR #1609 into 1.17.1.
=> 1.17: Addressed safety issues

.readthedocs.yaml, zhmcclient/_version.py
=> Fixed RTD build issue

.readthedocs.yaml, zhmcclient/_version.py
Rolls back PR #1612 into 1.17.1.
=> 1.17: Fixed RTD build issue

changes/1611.fix.rst
No review needed - adds change log entry for PR #1612
=> Fixed RTD build (2) - added change log

changes/1611.fix.rst
Rolls back PR #1614 into 1.17.1.
=> 1.17: Fixed RTD build (2) - added change log

changes/1611.fix.rst, changes/noissue.1.17.1.notshown.rst, changes/noissue.1.cleanup.rst, changes/noissue.2.cleanup.rst, changes/noissue.safety.fix.rst, docs/changes.rst
=> Release 1.17.1

Makefile, docs/development.rst
=> Fixed creation of release start tag when starting a new version

Makefile
=> Fixed unintended authors update during release workflow

changes/noissue.1.17.2.notshown.rst
=> Start 1.17.2

changes/noissue.1.fix.rst, docs/development.rst
=> 1.17: Fixed make start description in docs for starting a new release

Makefile, docs/development.rst
=> Support for releasing a new minor version on earlier stable branch

.github/workflows/release_pr.yml, Makefile
In this stage, a new release_pr make target has been added for verifying the approach. The development documentation is unchanged at this point.
=> Further simplified releasing a version - verify approach

.github/workflows/release_pr.yml
=> Fix 10 for previous commit

.github/workflows/release_pr.yml
=> Use generated Github App token for PR creation

.github/workflows/release_pr.yml
=> Use PAT to create PR

.github/workflows/test.yml, base-requirements.txt, changes/noissue.1.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, pyproject.toml, requirements.txt
=> Added Python 3.13 test envs and addressed install issues on 3.13

.github/workflows/release_pr.yml
=> release_pr: changed github-token parameter to use generated token from app

.github/workflows/release_pr.yml
=> release_pr: fixed github-token parameter

changes/noissue.1.feature.rst, changes/noissue.2.feature.rst, tests/unit/zhmcclient/test_exceptions.py, zhmcclient/_exceptions.py
=> Added exception tests

changes/618.feature.2.rst, docs/general.rst, minimum-constraints-install.txt, requirements.txt, tests/common/http_mocked_fixtures.py, tests/unit/zhmcclient/test_exceptions.py, tests/unit/zhmcclient/test_os_console.py, zhmcclient/__init__.py, zhmcclient/_constants.py, zhmcclient/_exceptions.py, zhmcclient/_logging.py, zhmcclient/_os_console.py, zhmcclient/testutils/_hmc_definition_fixtures.py
=> Added OSConsole encapsulation class for WebSocket

changes/noissue.3.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
This fixes https://github.com/zhmcclient/python-zhmcclient/security/dependabot/25
=> Fixed dependabot issue #25

.safety-policy-develop.yml, .safety-policy-install.yml, changes/1505.feature.rst, changes/1506.feature.rst, changes/1543.feature.rst, changes/1543.fix.rst, changes/1611.fix.rst, changes/1660.fix.rst, changes/1665.fix.rst, changes/618.feature.2.rst, changes/618.feature.rst, changes/noissue.1.18.0.notshown.rst, changes/noissue.1.cleanup.rst, changes/noissue.1.feature.rst, changes/noissue.1.fix.rst, changes/noissue.1.incompatible.rst, changes/noissue.2.cleanup.rst, changes/noissue.2.feature.rst, changes/noissue.2.fix.rst, changes/noissue.3.cleanup.rst, changes/noissue.3.feature.rst, changes/noissue.3.fix.rst, changes/noissue.4.cleanup.rst, changes/noissue.5.cleanup.rst, changes/noissue.6.cleanup.rst, changes/noissue.safety.fix.rst, dev-requirements.txt, docs/changes.rst, minimum-constraints-develop.txt
=> Release 1.18.0

Makefile, changes/1689.fix.rst
=> Fixed incorrect check for start branch in 'make start_tag'

.github/workflows/publish.yml, Makefile, changes/noissue.2.fix.rst
=> Made creation of AUTHORS.md tolerant against not getting authors

.github/workflows/publish.yml, Makefile, changes/noissue.2.fix.rst
Rolls back PR #1694 into 1.18.1.
=> 1.18: Made creation of AUTHORS.md tolerant against not getting authors

Makefile, changes/noissue.3.fix.rst
=> Dev: Fixed missing removal of temp file in 'make start_branch'

Makefile, changes/noissue.3.fix.rst
Rolls back PR #1696 into 1.18.1.
=> 1.18: Dev: Fixed missing removal of temp file in 'make start_branch'

Makefile, changes/noissue.3.fix.rst
=> Fixed checks in make targets for releasing/starting

Makefile, changes/noissue.3.fix.rst
Rolls back PR #1698 into 1.18.1.
=> 1.18: Fixed checks in make targets for releasing/starting

Makefile
=> Document git shortlog issue in Makefile

Makefile, changes/noissue.2.fix.rst
=> Fix issue that without terminal the AUTHORS.md file was emptied

.github/workflows/publish.yml
=> Resolved packages_dir warning in publish workflow

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints-develop.txt
=> Fixed pydantic-core install failure

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1711 into 1.18.1.
=> 1.18: Fixed pydantic-core install failure

changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> Fixed safety issues up to 2024-11-28

README.md
=> Changed doc links in README to go to stable version

.github/workflows/test.yml, changes/noissue.6.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
See https://github.com/andfoy/pywinpty/issues/486.
=> Circumvented issue with installing pywinpty on Python 3.8

changes/noissue.7.fix.rst, zhmcclient/_session.py
=> Fixed incorrect HTTP method name in log messages for 403

changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> Fixed safety issues up to 2025-01-23

tests/end2end/test_partition_link.py
=> Updated partition link end2end tests to also clean up partitions at end

changes/noissue.checkreqs-dev.fix.rst, changes/noissue.safety.fix.rst, minimum-constraints-develop.txt
Rolls back PR #1762 into 1.19.1.
=> 1.19: Fixed safety issues; Fixed missing dependencies

base-requirements.txt, changes/noissue.safety.fix.rst, minimum-constraints-install.txt
=> 1.19: Fixed safety issues

AUTHORS.md, changes/1760.fix.rst, zhmcclient/_cpc.py
Rolls back PR #1761 into 1.19.
=> 1.19: Fix broken inventory error handling (#1761)

.github/workflows/publish.yml
=> Changed target Pypi to production Pypi

.github/workflows/publish.yml
=> Documented reqs for trusted publishing in publish workflow

changes/noissue.fcpvsr.fix.rst
The original PR without change log was #1759.
=> Added change log for test fix for FCP VSRs

changes/noissue.fcpvsr.fix.rst
The original PR without change log was #1787.
=> 1.19: Added change log for test fix for FCP VSRs

changes/1749.cleanup.rst, tests/end2end/test_partition_link.py
=> End2end test: Improved test method 'test_partlink_zzz_cleanup()'

changes/noissue.sessionrepr.feature.rst, zhmcclient/_session.py
=> Improved repr() of Session objects

changes/1750.cleanup.rst, tests/end2end/test_activation_profile.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/utils.py, zhmcclient/testutils/_hmc_definition_fixtures.py
=> Consolidated different ways to enable logging in end2end tests

changes/noissue.5.feature.rst, changes/noissue.6.feature.rst, zhmcclient/_session.py
=> Improved logging and error reporting for session logon

changes/1755.fix.rst, changes/noissue.1.19.2.notshown.rst, changes/noissue.fcpvsr.fix.rst, docs/changes.rst
=> Release 1.19.2

changes/noissue.1.20.1.notshown.rst
=> Start 1.20.1

.github/workflows/publish.yml, changes/noissue.2.fix.rst
=> Dev: Fixed permissions for creating GitHub release when releasing a version

changes/1803.feature.rst, changes/1803.fix.rst, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_metrics.py
=> Fixed use of list_permitted_adapters(); Added caching for list_api_features()

.github/workflows/publish.yml
=> 1.20.1: Fixed permission 'contents' in publish workflow

.github/workflows/publish.yml
Rolls forward PR #1807 into master
=> Fixed permission 'contents' in publish workflow

changes/noissue.1.20.2.notshown.rst
=> Start 1.20.2

Makefile
=> Added platform details to 'make platform'

Makefile
Rolls back PR #1813 into 1.20.
=> 1.20: Added platform details to 'make platform'

Makefile
=> Installing ld quietly

Makefile
Rolls back PR #1816 into 1.20.
=> 1.20: Installing ld quietly

.github/workflows/test.yml
=> Split display of env vars and platform details

changes/1827.fix.rst, changes/1828.deprecation.1.rst, changes/1828.feature.1.rst, changes/1828.feature.2.rst, changes/1828.feature.3.rst, changes/1830.feature.rst, docs/appendix.rst, docs/concepts.rst, tests/end2end/test_console.py, tests/end2end/test_cpc.py, tests/end2end/test_partition.py, tests/end2end/utils.py, tests/unit/zhmcclient/test_console.py, tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_partition.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1829 into 1.20.
No additional review eeded.
=> 1.20: Fixed and improved methods for FW/API features; Mock support API features

changes/noissue.marshmallow.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> Increased safety to 3.4.0 and updated its dependencies

changes/1713.fix.rst, changes/1827.fix.rst, changes/1828.deprecation.1.rst, changes/1828.feature.1.rst, changes/1828.feature.2.rst, changes/1828.feature.3.rst, changes/1830.feature.rst, changes/noissue.1.20.3.notshown.rst, changes/noissue.safety.fix.rst, docs/changes.rst
=> Release 1.20.3

changes/1844.fix.rst, zhmcclient/_lpar.py
=> Docs: Fixed statement about DPM in LparManager class

changes/noissue.1.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> Dev: Fixed Sphinx build issue by excluding snowballstemmer 3.0.0

changes/noissue.safety.fix.rst, minimum-constraints-develop.txt
=> Safety issues up to 2025-05-11

renovate.json
=> Added commit signing for PRs created by Mend Renovate

renovate.json
See https://github.com/renovatebot/renovate/discussions/35858#discussioncomment-13106205
=> Added commit signing for PRs created by Mend Renovate (2)

changes/noissue.renovate.fix.rst
=> Added change log entry for renovate changes

Makefile, changes/noissue.3.fix.rst
=> Fixed the dependencies in the Makefile

Makefile, changes/noissue.3.fix.rst
=> Fixed dependencies in Makefile

changes/noissue.1.feature.rst, zhmcclient/_session.py
Rolls back PR #1890 into 1.21.
=> 1.21: Improved the error message in connection related exceptions

changes/1888.fix.rst, zhmcclient/_constants.py
This PR needs to wait for validation before merging it.
=> Changed default read retries from 0 to 3

.safety-policy-develop.yml, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1878 into 1.21.
=> 1.21: Safety issues

dev-requirements.txt, minimum-constraints-develop.txt
=> Increased version of importlib-metadata

dev-requirements.txt, minimum-constraints-develop.txt
=> Increased docutils version

changes/noissue.47.fix.rst, dev-requirements.txt
=> Circumvented safety issue with import of typer module

Makefile, changes/noissue.2.fix.rst
=> Fixed quoting for TESTCASES env var in Makefile

changes/1969.cleanup.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt, tests/unit/zhmcclient/test_utils.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_metrics.py, zhmcclient/_utils.py
For details, see the commit message.'
=> Eliminated dependency on pytz

changes/noissue.63.cleanup.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
=> Removed dependency to "decorator" package

changes/1982.fix.rst, zhmcclient/_notification.py
=> Increased max size of notification handover queue

changes/noissue.39.rst, docs/general.rst
=> Added missing zhmcclient exceptions to the documentation

changes/1969.cleanup.rst, changes/1975.cleanup.rst, changes/1980.incompatible.rst, changes/noissue.45.fix.rst, changes/noissue.68.fix.rst, changes/noissue.74.fix.rst
=> Change log entries now link to Python elements

changes/1969.cleanup.rst
=> Fixed module links in change log

changes/noissue.128.cleanup.rst, zhmcclient/_constants.py
=> Improved documentation of constants for rt config defaults

Makefile, changes/noissue.devlog.feature.rst, changes/noissue.rtd.feature.rst, docs/changes.rst
=> Improved make deps & added change log entry for development change log

dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #2006 into 1.24.
=> 1.24: Added pydantic_core dependency
