README.rst
Details:
- Embedding Status Image for Travis Build Status Master.
- Embedding Status Image for readthedocs.org documentation.
=> Embedding Status Images in README.rst

docs/conf.py
This should now show the notebooks in the tutorial page in the notebook viewer on nbview.jupyter.org. 
=> Fixed links to Jupyter notebooks in tutorial section.

Makefile, tests/test_session.py, zhmcclient/_activation_profile.py, zhmcclient/_cpc.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
This PR removes the ignoring of the flake8 error code in `make check`, so that an issue-free flake8 is now enforced. Any future flake8 issues will cause the Travis CI build to fail.
Because PyLint messages are harder to map to good or bad, PyLint issues are still ignored in `make check`, and PyLint issues need to be resolved on a voluntary basis.
=> Fixed all flake8 issues and enforced issue-free flake8 in make check.

docs/operations.rst, zhmcclient/_activation_profile.py
This was forgotten when the support for activation profiles was added.
=> Enabled documentation for activation profiles and fixed minor markup issue

tests/test_resource.py, tests/test_session.py, zhmcclient/_resource.py, zhmcclient/_session.py
The `uri` property was added for two reasons:
- in order to avoid access to the private `_uri` instance variable in the unit tests.
- because it is a rather important attribute for the resource and was not available otherwise yet.
ready for review and merge
=> Addressed PyLint issues and added uri property to BaseResource class.

.travis.yml, README.rst
Details:
- Coveralls.io is service to publish your coverage stats online.
=> Added support for Coveralls.

tests/test_cpc.py, zhmcclient/_cpc.py
Details:
- All Managers (Lpar, Partition, Activation Profiles, ...)
are created independent of the CPC mode.
=> Remove internal DPM check.

docs/appendix.rst, docs/concepts.rst, docs/general.rst, docs/index.rst, docs/intro.rst, docs/resources.rst, zhmcclient/_version.py
Ready for review and merge. Best way to review is to build the documentation locally via `make builddoc`.
=> Restructured and improved the documentation.

requirements.txt, zhmcclient/_logging.py
This fixes the documentation (although code is changed).
Details:
- The documentation generated for methods or functions decorated with
the `_log_call` decorator is incorrectly generated with a prototype
of `*args, **kwargs`. This the prototype of the wrapper function
of the decorator. This has been fixed by switching from using
the `functools` package to using the `decorator` package.
See also http://stackoverflow.com/a/14448445/1424462
and https://pythonhosted.org/decorator/documentation.html#a-trace-decorator
=> Fixed incorrect args/kwargs prototype generated when using _log_call

docs/intro.rst
Details:
- Simplified description in the "What this package provides" section, adding links to z Systems and LinuxOne.
- Fixed incorrect "up to" statement in "Machine generations" column of HMC version table in "Supported environments" section.
- Added "Installation", "Examples" and "License" sections.
- Minor clarification in the "Versioning" section.
=> Updated Introduction chapter.

docs/resources.rst, examples/example8.py, examples/example_hmccreds.yaml, tests/test_adapter.py, zhmcclient/__init__.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py
Details:
- Add AdapterManager class.
- Add Adapter class.
- Add Unit Tests for AdapterManager and Adapter.
- Add AdapterManager to Cpc class.
=> Add Adapter support

docs/resources.rst, examples/example8.py, tests/test_hba.py, zhmcclient/__init__.py, zhmcclient/_hba.py, zhmcclient/_partition.py
Details:
- Add HbaManager class.
- Add Hba class.
- Add Unit Tests for HbaManager and Hba.
- Add HbaManager to Hba class.
- Add HBA to documentation reference.
- Add Hba example (example7.py).
=> Add HBA Support

docs/appendix.rst
This is a first step by creating a flat list of resource types with definitions, without linking to these entries yet.
Ready to be reviewed and merged.
Future work (in different PRs):
* Any mentioning of a resource type can link to the definition.
* We could draw a picture of the resource tree for DPM mode and classic mode.
=> Added Resource Model in Appendix.

docs/resources.rst, examples/example8.py, tests/test_virtual_function.py, zhmcclient/__init__.py, zhmcclient/_partition.py, zhmcclient/_virtual_function.py
Details:
- Add VirtualFunctionManager class.
- Add VirtualFunction class.
- Add Unit Tests for VirtualFunctionManager
and VirtualFunction.
- Add VirtualFunctionManager to Partition class.
- Add VirtualFunction to documentation reference.
- Add VirtualFunction example (example8.py).
=> Add Virtual Function Support

docs/resources.rst, examples/example8.py, tests/test_virtual_switch.py, zhmcclient/__init__.py, zhmcclient/_cpc.py, zhmcclient/_resource.py, zhmcclient/_virtual_switch.py
Details:
- Add VirtualSwitchManager class.
- Add VirtualSwitch class.
- Add Unit Tests for VirtualSwitchManager
and VirtualSwitch.
- Add VirtualSwitchManager to CPC class.
- Add Virtual Switch to documentation reference.
- Add Virtual Switch to example (example8.py).
- Add 'type' if available to __str__ of BaseResource.
=> Add Virtual Switch Support

tests/test_adapter.py, tests/test_hba.py, tests/test_nic.py, tests/test_partition.py, tests/test_virtual_function.py, zhmcclient/_adapter.py, zhmcclient/_hba.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_resource.py, zhmcclient/_virtual_function.py
Please review.
Details:
- Removed unnecessary check for full properties in list() for Adapter, Nic, Hba.
- Changed returned object from any create...() methods to be the resource object, filled with the input properties and the returned properties.
- Adjusted testcases to the changed return value.
What was NOT done:
- The full_properties property still exists, and is tested by the test cases. We could remove it in the future, but for now I left it in.
- I did NOT add any additional state w.r.t. the filled properties, because I think the only relevant information is whether the set is complete or not complete. Distinguishing between created (which does NOT just have the URI property filled, but also the input properties!) and the properties returned by list() did not seem necessary.
=> Fixes #50: Changed create...() to return resource object instead of URI.

tests/test_partition.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_client.py, zhmcclient/_cpc.py, zhmcclient/_exceptions.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_resource.py, zhmcclient/_session.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
Please review.
Details on documentation changes:
- Updated all references to specific sections of the HMC API book to be consistent, and to use section names that can be search in the HMC API book's PDF file.
- Updated descriptions of all resource modules (module level, manager classes, resource classes, and their methods and properties) to be consistent, and to improve the description quality.
Code changes:
- Renamed the 'properties' argument of `Partition.dump_partition()` to 'parameters', and adjusted the test case accordingly.
=> Improved documentation of resource modules and renaming of a method argument

docs/appendix.rst, docs/resources.rst, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_client.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
Please review. Only docs changes.
Details:
- Moved description of resource and manager base classes into appendix.
- Made terms in Resource Model glossary consistent and fixed any links between them.
- In all resource and manager descriptions, turned all references to resources into links to their entries in the resource model glossary.
- Removed `__init__()` methods of resource classes and manager classes from the documentation, because these objects are not supposed to be created by the user.
=> Updated documentation of resources classes, part 2.

tests/test_cpc.py
Details:
- Add unit test for start
- Add unit test for stop
- Add unit test for export_profiles
- Add unit test for import_profiles
=> Add more unit tests for CPC class

docs/resources.rst, examples/example8.py, tests/test_port.py, zhmcclient/__init__.py, zhmcclient/_adapter.py, zhmcclient/_port.py, zhmcclient/_resource.py
Details:
- Add PortManager class.
- Add Port class.
- Add PortManager to Adapter class.
- Add Adapter to documentation reference.
- Add Port to example (example8.py).
- Add 'class' if available to __str__ of BaseResource.
- Add Unit Tests for PortManager and Port.
=> Add Port Support

dev-requirements.txt, examples/example7.py, examples/example_hmccreds.yaml, tests/test_session.py, zhmcclient/_session.py
This PR is ready to be merged.
Details:
* Added the method `get_notification_topics()` which returns the per-session JMS destination names for the logged in user.
* Added example7 which demonstrates how a user can wait for completion of an asynchronous operation (stopping or starting a partition) using JMS notifications from the HMC.
=> Added get_notification_topics() and example7 for user wait for async op. completion

tests/test_nic.py, tests/test_partition.py, tests/test_virtual_switch.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_virtual_switch.py
Please review.
The code to create the `Partition` and `Nic` objects has now been consolidated into the respective resource modules, so that the `VirtualSwitch.get_connected_vnics()` method that needs them is now cleaner.
=> Fixes #62: Changed get_connected_vnics() to return Nic objects

README.rst
PyPI download statistics are broken at the moment, see for example [this issue](https://github.com/badges/shields/issues/716). Google BigQuery can be used instead, see [this article](https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html) and these [example bigqueries](https://gist.github.com/alex/4f100a9592b05e9b4d63).
This PR removes the PyPI downloads/months button and adds a BigQuery for querying the package downloads by version in the comment(!) of the README.rst file.
=> Removed downloads button in readme and added bigquery in comment.

tests/test_nic.py, tests/test_partition.py, tests/test_virtual_switch.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_virtual_switch.py
Reason: The HMC API book is inconsistent in its use of VNIC vs. NIC. For example, the 'Get Connected VNICs of a Virtual Switch' HMC operation uses the term 'VNICs' for the same objects the 'Create NIC' HMC operation uses 'NIC' for. Therefore, we should use one term ('NIC') consistently in the zhmcclient API.
This PR is on top of PR #65.
Please review and merge (after merging PR #65).
=> Renamed get_connected_vnics() to get_connected_nics()

docs/appendix.rst, tests/test_cpc.py, tests/test_hba.py, zhmcclient/_cpc.py, zhmcclient/_hba.py
Details:
- Added `get_wwpns()` to `Cpc` class, which performs HMC operation 'Export WWPN List', and extended the unit test cases for it.
- Added `reassign_port()` to `Hba` class, which performs HMC operation 'Reassign Storage Adapter Port', and extended the unit test cases for it.
- Added 'FCP Port' as a term to the resource model (docs only).
Please review.
=> Added more HBA/storage related methods.

requirements.txt, setup.cfg, tools/cpcinfo
Please review.
Details:
- Added tabulate and progressbar2 as prereqs in requirements.txt.
- Added tools/cpcinfo as a script in setup.cfg to get it installed into the PATH.
- Added a --version option to cpcinfo that displays its own/zhmcclient version and the Python version.
=> Several logistical cpcinfo fixes.

.travis.yml, Makefile, tox.ini
Please review.
Details:
- In order to detect missing prereqs in non-development mode, added an install test to Travis CI that installs the package before installing the development dependencies.
- As part of that, changed the `make install` processing to install the package using `pip install .` (from `python setup.py install`), and added an import test to `make install`.
- For the Tox test, it was not easily possible to test installation without also having the development prereqs installed, but added the install test anyway.
=> Added an install test to Travis CI and to Tox.

tests/test_exceptions.py, zhmcclient/_exceptions.py
This is in support of an HTTP error Elisabeth sees, and allows to find the operation in the HMC API book that documents the HTTP status code and reason code.
Please review.
=> Added HTTP method and URI to HTTPError information.

tests/unit/test_cpc.py, zhmcclient/_cpc.py
Please review.
This issue went by undetected because the mocked HMC responses in the unit tests made the same mistake as the code that was tested. This shows the importance of a real test.
Details:
- In the optimized implementation of dpm_enabled, the http_status and reason properties of HTTPError were incorrectly tested against strings. Fixed that by testing against integers.
- The mocked HMC responses defined in the unit tests had the same problem and returned strings for http_status and reason, which is why the problem went in, undetected. Fixed that also by changing the mocked responses to use integers.
=> Fixed HTTPError in dpm_enabled.

Makefile, docs/changes.rst, docs/notebooks/01_notebook_basics.ipynb, docs/notebooks/02_connections.ipynb, docs/notebooks/03_datamodel.ipynb, docs/notebooks/tututils.py
Please review.
Details:
- Improved notebook `01_notebook_basics` by explaining view-only vs. execute/modify, and by adding code sections about Python search path and current directory within the notebook environment.
- Improved notebook `02_connections` by showing how to turn off the InsecureRequestWarning messages, and by adding an operation that requires to be logged on.
- Wrote content for notebook `03_datamodel`.
- Added a utility module `tututils` in the notebooks directory, that currently has a function `make_client()` that logs on to the HMC and returns a Client object, in order to keep the code sections in the tutorials simpler.
=> Improved tutorial notebooks

docs/changes.rst, docs/development.rst
Please review.
This fixes the change log to reflect v0.5.0, and updates the how-to-release section to reflect the updating of teh change log better.
Because v0.5.0 is already released, I suggest to merge this into master.
=> Fixed change log to represent the already released v0.5.0.

docs/changes.rst, docs/development.rst, tests/unit/test_exceptions.py, tests/unit/test_session.py, zhmcclient/_exceptions.py, zhmcclient/_session.py
This PR addresses the AuthError and ConnectionError portion of issue #94.
The other parts will be addressed separately.
This PR is based on PRs #95 and #96, so the first two commits have already been reviewed as part of their review.
Details:
- In `AuthError`, added a `details` property that is the underlying exception, and that is set to an `HTTPError` object in case the error is triggered by a failed HTTP response.
- In `ConnectionError`, added a `details` property that is the underlying exception, and that is set to a `RequestException` object in case the error is triggered by a failed requests method.
- Extended the unit testcases for `AuthError` and `ConnectionError` to test the new `details` property.
- Fixed a bug in the unit test cases for HTTPError, that …
=> Improved the AuthError and ConnectionError exceptions and their use.

docs/changes.rst, docs/notebooks/tututils.py, tests/unit/test_activation_profile.py, tests/unit/test_port.py, tests/unit/test_session.py, zhmcclient/_partition.py
Details:
- In `Partition.dump_partition()`, wait_for_completion was always set to True, and the corresponding input argument was ignored.
- Fixed several pyLint issues.
=> PyLint fixes and a real fix in dump_partition().

tools/cpcinfo
Signed-off-by: Juergen Leopold leopoldj@de.ibm.com
=> Fix typo in help message of cpcinfo.

docs/changes.rst, zhmcclient/_session.py
So far,  the time statistics only records the actual async POST operation, i.e. the start of what happens in the background, and separately, all the GET operations that poll for job completion. This makes it hard to figure out what the elapsed time is for the entire operation.
This PR improves that by adding an entry in the time statistics for the overall operation consisting of the sequence of async POST plus all the GETs for polling.
=> Added time statistics entry for overall async operations.

tests/unit/test_activation_profile.py, tests/unit/test_adapter.py, tests/unit/test_client.py, tests/unit/test_cpc.py, tests/unit/test_hba.py, tests/unit/test_lpar.py, tests/unit/test_port.py, tests/unit/test_virtual_function.py
This PR fixes the new E305 issue reported by the new version of flake8 that is used in the Travis CI.
This PR needs to be merged quickly, because all other PRs will also run into this issue.
=> Fixed new Flake8 issue E305.

docs/appendix.rst, zhmcclient/_session.py
Details:
- A session object be created by a existing session id.
- Remove double assignment of _header and session_id.
=> Session object can be created with session id

docs/changes.rst, requirements.txt
Details:
- During 'pip install zhmcclient' and
building the package we run into IOError when
trying to install click-spinner 0.1.4.
There we pin click-spinner to version 0.1.3.
=> Fixed #120: Pin click-spinner to 0.1.3

Makefile, docs/development.rst
Details:
- Probably, the bug that an incorrect version was uploaded to Pypi was caused by having that version installed as a package in the virtual Python environment.
- Fixed that bug in the Makefile, by:
- Adding an 'uninstall' target that uninstalls the Python package from the current Python environment.
- Invoking that 'uninstall' target as part of the 'clobber' and 'upload' targets.
- As an additional safety net, added a check to the 'upload' target that rejects the attempt to upload development versions.
- As a second additional safety net, added a confirmation prompt in the 'upload' target that asks the user for confirmation.
- Updated the Pypi upload steps in the RTD documentation to state that a user confirmation is needed for 'make upload'.
=> Fixed incorrect package version for pypi upload.

docs/cli.rst, docs/index.rst, zhmccli/_cmd_cpc.py, zhmccli/_cmd_info.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_session.py, zhmccli/zhmccli.py
Details:
- Added a new chapter "Command line interface" to the RTD documentation.
- Shortened the help text of `zhmc --help`.
- Added a note in `zhmc --help` that its options are general options and can be specified on all (sub-)commands.
- Added a note in all other zhmc command help texts that the general options can be specified as well.
- Added a note to some help texts that some properties are ommitted  in table format (for those that defined a skip list).
- Switched order of sub-commands in partition command to be consistent.
=> Fixes #112: For zhmc CLI, added RTD documentation and improved help texts.

docs/changes.rst, requirements.txt, zhmccli/_helper.py, zhmccli/zhmccli.py
This PR removes the pinning of click-spinner to 0.1.3 and instead requires >=0.1.5, and at the same time it exploits the new abilities in 0.1.5 (ability to pause via stop/start, and automatic suppression when not on a tty).
=> Upgraded click-spinner to v0.1.5 and simplified its use

tests/unit/test_hba.py, tests/unit/test_resource.py, tests/unit/test_virtual_switch.py, zhmccli/__init__.py, zhmccli/_cmd_adapter.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_port.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vswitch.py, zhmccli/_helper.py, zhmccli/zhmccli.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_session.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
This PR is pretty much completely tested and ready for serious use.
zhmcclient library changes:
- Added support in the `BaseResource` class for optimized resource access by name. This includes:
- an instance variable `_uris` that is a cached mapping of resource names to resource URIs
- a new `find_by_name()` method that is automatically used by `findall()` and `find()` when called with 'name' as the single filter, but can also be called by the user.
- a `flush()` method that flushes the cached name-to-URI mapping. This is only needed when renaming resources.
- Added two required parameters to the init method of class BaseResource. This method is not part of the external API, so this is not an incompatible change.
zhmc CLI changes:
- Added support for all missing resource types for DPM …
=> Added support in CLI for remaining cmds; client improvements.

docs/appendix.rst, docs/changes.rst
This change also removes the update number from the book number (e.g. " SC27-2634-01" -> " SC27-2634"), because that is sufficient for it to uniquely identify the book for the desired HMC version.
Please review.
=> Fixes #131: Links to HMC API books in docs no longer require IBM ID.

.gitignore, docs/changes.rst, examples/cli/crud_partition.sh, examples/cli/example_zhmcrc.sh
Add example for CLI zhmc
Details:
- Example implements create, delete, updates
and list of a partition using the CLI.
- Example implements check of DPM mode.
- Example file provided for runtime configuration
information stored in zhmcrc.sh file.
- zhmcrc.sh added to gitignore file to
avoid accidentally release runtime information
to repository.
=> Add example for CLI zhmc

docs/changes.rst, examples/example1.py, examples/example2.py, examples/example3.py, examples/example4.py, examples/example5.py, examples/example6.py, examples/example8.py, tests/unit/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
Details from the commit message:
* This bug was introduced recently with the URI-to-name caching, which now causes the 'properties' attribute to be empty where it was not empty before.
* Fixed by maintaining the 'name' property in the 'properties' attribute whenever possible (i.e. available). This does not solve all situations, therefore updated the documentation of the 'properties' attribute to make users aware, and to recommend use of 'get_property()' or 'name' or 'uri', for accessing specific resource properties.
* Also, added assertions in `BaseResource.__init__()` that ensure that the uri and the name are consistent, if provided both ways (via direct argument and via the 'properties' dict).
* Updated the examples accordingly. They all runs again, now.
* In …
=> Fixes #137: Accessing properties['name'] may raise KeyError.

tests/unit/test_manager.py, zhmcclient/_manager.py
Before [1], manager.findall(name=..) returned an empty list
if nothing was found. This patch restores that initial behavior.
[1] https://github.com/zhmcclient/python-zhmcclient/commit/
ff6be0dfb81e47cf74b16336eb264d274b2eee22
closes #141
Signed-off-by: Andreas Scheuring <andreas.scheuring@de.ibm.com>
=> Fixing regression in findall(name=..)

zhmcclient/_lpar.py
lpar.load(): Added support for load-parameter field
The load parameter field is an optional field supported by the API for the load operation. It may be required by the system to sucessfully load an LPAR. For example, it might be used to determine which PLEX an LPAR belongs to.
Signed-off-by: Andrew Brezovsky (abrezovsky@gmail.com)
=> lpar.load(): Added support for load-parameter field

Makefile, appveyor.yml, tox.ini
This PR should already work in the Appveyor CI.
Please merge and establish Appveyor web service, then it can be tested.
Possibly needs an account on https://www.appveyor.com/, not sure.
Details in this PR:
- Added an appveyor.yml control file.
- Added pywin27 environment to tox.ini.
- Corrected commands listed in header of Makefile.
=> Added initial support for Appveyor CI.

tests/unit/test_timestats.py
Details:
* In test_timestats, improved the approach for checking time deltas such
that the assertion error now shows the actual and expected delta, instead
of just the mismatch between true and false.
* In test_timestats, increased the allowable time delta and the measured times
in order to accomodate the fact that `time.time()` which is used by the `TimeStats`
class, has only a 1/60 sec precision on Windows. This is a circumvention - the real
solution would be to use some other service that returns high precision  timings
on all supported operating systems.
=> Fixes #152: Fixed assertion error in TimeStats testing on Windows.

examples/example5.py
Name 'partition' is not defined when partition is not found.
Resolves #149
=> Fix error in example5.py

docs/changes.rst, docs/general.rst, tests/unit/test_manager.py, tests/unit/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
This PR adds support for filtering properties on the server side via filter query parameters. This is done transparently, for those properties that are supported. The rest of the properties is still filtered on the client side.
There are two incompatibilities:
* The support for server-side filtering caused an incompatibility for the `find()` and `findall()` methods: For String typed resource properties, the provided filter string is now interpreted as a regular expression that is matched against the actual property value, whereby previously it was matched by exact string comparison.
* The parameter signatures of the `__init__()` methods of `BaseResource` and `BaseManager` have changed incompatibly. These methods have always been  considered internal to the …
=> Added support for server-side resource filtering.

docs/changes.rst, zhmccli/_cmd_hba.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_vfunction.py
Fix for AttributeError: 'Partition' object
has no attribute 'cpc'
Resolves issue #161
=> Fix access 'cpc' from 'partition'.

Makefile, docs/index.rst, docs/mocksupport.rst, setup.cfg, tests/unit/zhmcclient_mock/test_hmc.py, zhmcclient/_adapter.py, zhmcclient_mock/__init__.py, zhmcclient_mock/_hmc.py
This is stage 1 of the mocking support according to the design described in PR #144. This stage provides a faked HMC. This stage is now complete and covers all resource types supported by the zhmcclient.
The stages have been split for easier reviewing. However, the two PRs should be merged at the same time once both have been approved.
A separate stage 2 in PR #160 will provide a faked Session object that links the zhmcclient package with the faked HMC.
Details:
- Added support for a faked HMC that provides a local in-memory representation of an HMC. Its API is intended to be used by a future faked Session object (which is the reason it is not compatible with the external zhmcclient API).
=> Mocking support for zhmcclient, stage 1: Faked HMC.

Makefile, docs/index.rst, docs/mocksupport.rst, setup.cfg, tests/unit/zhmcclient_mock/test_example.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_adapter.py, zhmcclient_mock/__init__.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
This is stage 2 of the mocking support according to the design described in PR #144. 
Stage 1 is provided in PR #159.
The stages have been split for easier reviewing. However, the stages should be merged together once both have been approved.
At this point, the implementation of stage 2 of the mock support does not yet cover all operations supported by the zhmcclient. Missing are:
* For DPM mode:
```
POST     /api/partitions/([^/]+)/operations/scsi-dump
POST     /api/partitions/([^/]+)/operations/psw-restart
POST     /api/partitions/([^/]+)/operations/mount-iso-image
POST     /api/partitions/([^/]+)/operations/unmount-iso-image
POST     /api/partitions/([^/]+)/hbas/([^/]+)/operations/reassign-
storage-adapter-port
POST     /api/virtual-switches/([^/]+)/operations/get-connected-vnics
```
* …
=> Mocking support for zhmcclient, stage 2: Faked Session (partially).

examples/example_hmccreds.yaml, examples/lpar_operations.py
Reason for this change was to have better displaying of the behavior that sometimes after LPAR activation, the status does not update for some time, or not at all.
Details:
- Added retry loops when retrieving status, until desired status is achieved.
- Changed refresh from pull_full_properties() to using list(), because we just want to use the 'status' property.
- Removed "cpcstatus" input parameter, because when the CPC name is provided, it does not really make sense to filter by status in addition.
=> Improved example lpar_operations

zhmcclient/_lpar.py, zhmcclient/_partition.py
Added support for open-os-message-channel HMC API operation to the
lpar and partition classes. This is the minimum level of support for interaction with
operating system messages. The message channel will stay open until the API
session is terminated. #148 
Signed-off-by: Andrew Brezovsky <abrezovsky@gmail.com>
=> Added open_os_message_channel() method to lpar and partition classes

docs/notifications.rst, examples/example_hmccreds.yaml, examples/show_os_messages.py, requirements.txt, zhmcclient/__init__.py, zhmcclient/_lpar.py, zhmcclient/_notification.py, zhmcclient/_partition.py
Please review.
Testcases are not yet part of this PR, but I wanted to get the API of the `NotificationReceiver` class reviewed as soon as possible.
Details:
- Added a NotificationReceiver class that is a general purpose JMS message / notification receiver.
- Added a chapter 'Notifications' to the documentation, describing the new class.
- Added an example show_os_messages.py that uses the new open_os_message_channel() method added in a previous commit, and the new notification receiver, to display the OS messages of a partition or LPAR.
=> Added a JMS notification receiver and examples for os messages.

.travis.yml, appveyor.yml, tox.ini
Please review.
Details:
- Added Python 3.6 environment to Travis control file.
- Enabled Appveyor control file to support multiple Python environments and added Python 3.4, 3.5, and 3.6 to it.
- Added 64-bit versions (of Python 2.7,3.4,3.5,3.6) to Appveyor control file.
- Disabled updating of Windows registry with Python install path.
=> Fixes #165: Added Python 3.6 to Travis CI and 3.4-3.6 to Appveyor CI

.travis.yml
Please review.
This PR mitigates the current issue that coveralls posts too many coverage comments, by invoking coveralls in the Travis control file only for python 2.7.
=> Mitigated multiple coveralls comments per Travis build.

tests/unit/test_notification.py, zhmcclient/_notification.py
Details:
- Added to the NotificationReceiver class that the notifications() method stops iterating and returns if the STOMP connection is disconnected (e.g. because close() was called).
- Added unit testcases for the _notification module.
=> Added termination of notification receiver and unit tests.

docs/changes.rst, docs/general.rst, examples/async_operation_polling.py, examples/jms_notifications.py, tests/unit/test_session.py, zhmcclient/_cpc.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_session.py
**Note the incompatible change of the return value of async methods.**
Motivation:
- This fixes a discrepancy between the documentation that states `None` is returned in case of `wait_for_completion=True`, and the code that returned the response of the 'Query Job Status' operation as a JSON object. See issue #178.
- Because the return value changes anyway, this change also improves the return value in case of `wait_for_completion=False`, by returning an object of a new `Job` class.
Details:
- Changed the return type of all methods on resource classes that invoke asynchronous operations (i.e. all methods that have a `wait_for_completion` parameter), as follows:
- For `wait_for_completion=True`, the JSON object in the 'job-results' field is now returned, or `None` …
=> Fixes #178, fixes #63: Redesigned return value of async. operation methods

README.rst, docs/intro.rst
Details for README file:
- Removed mentioning of 'python-zhmcclient' package because both the PyPI package and the Python package (namespace) are 'zhmcclient'.
- Clarified that doc link to pypi is latest version on pypi. That becomes a difference when people look at older versions on pypi.
- Improved the quickstart script (streamlined variable names, removed display of API version, moved disabling of warnings to the topi).
- Added example output of the quickstart script.
- Added CLI example, with example output.
Details for intro chapter:
- Improved the quickstart script (streamlined variable names, removed display of API version, moved disabling of warnings to the top).
- Added example output of the quickstart script.
- Added CLI example, with example output.
=> Docs: Improved README file and example in intro chapter

zhmcclient/_lpar.py, zhmcclient/_partition.py
send_os_message allows the client to send messages to the object's operating
system. The method takes in a string for the command and and optional boolean
to indicate a priority. The method returns nothing because the HMC API returns
a response with no content. A status code 409 is returned from the API if the
message interface is not available.
Signed-off-by: Andrew Brezovsky <abrezovsky@gmail.com>
=> Added send_os_command method to partition and lpar

docs/changes.rst, requirements.txt
=> Fixes #116: Increased minimum version of 'click-spinner' dependency to 0.1.7.

tests/unit/zhmcclient_mock/test_idpool.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/__init__.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_idpool.py
Details:
- Added an IdPool class that can allocate and free integer ID values. This is used for devno allocation in faked partitions.
- Added unit test cases for the new IdPool class.
- Added automatic setting of the 'device-number' property when not specified by the caller, for faked HBA, NIC and VF resources, in the value range of 0x8000 to 0xFFFF.
=> Added automatic devno setting for NIC, HBA, VF in mock support

docs/changes.rst, zhmccli/_cmd_cpc.py, zhmccli/_cmd_lpar.py, zhmccli/_helper.py, zhmccli/zhmccli.py
Details:
- Added a 'help' command that displays help for interactive mode.
- When entering interactive mode, added a one-line hint that explains how to get help and how to exit interactive mode. This required to write our own repl() function.
- Because we now have our own repl() function, we can pass arguments to the click_repl.repl() function. Used that to add support for history of interactive mode commands, and to change the prompt to 'zhmc> '.
- Fixed incorrect reformatting of text areas in CLI help text by adding `\b` where needed.
=> Fixes #197: Improved help of zhmc CLI.

.travis.yml, Makefile, appveyor.yml, dev-requirements.txt, minimum-constraints.txt, requirements.txt, tox.ini
This PR specifies minimum versions for all Python package requirements, for runtime and development, and it changes the Travis and Appveyor CI testing such that the tests are run for both the minimum versions and the latest versions of dependent Python packages.
For more details, see the commit message.
=> Test with minimum & latest  versions of dependent Python packages

design/network-errors.rst, docs/changes.rst, docs/general.rst, tests/unit/test_exceptions.py, tests/unit/test_session.py, zhmcclient/__init__.py, zhmcclient/_constants.py, zhmcclient/_cpc.py, zhmcclient/_exceptions.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_session.py
Please focus on the changes at the API, more than on the implementation code.
Good questions would be, for example:
- The new `TimeoutError` class is used for both async operation timeouts and status polling timeouts, and it does not have a machine-readable way to distinguish these cases. This affects only the `Lpar.activate/dectivate/load()` methods. Is this good enough?
- Are the default timeouts right (see the new `_constants.py` module)?
- The use of `Lpar.activate/dectivate/load()` with `wait_for_completion=False` returns a Job object that can handle the waiting for job completion, but not the waiting for deferred status update. On the one hand, this may be what you expect from an asynchronous job, on the other hand, it is not consistent with the …
=> Fixes #6, Fixes #191: Timeout support for async methods; deferred status polling for LPAR

design/network-errors.rst, docs/changes.rst, docs/general.rst, tests/unit/test_exceptions.py, zhmcclient/__init__.py, zhmcclient/_constants.py, zhmcclient/_exceptions.py, zhmcclient/_session.py
This PR is now ready for code review and merging. It includes a design document in `design/network-errors.rst`.
It attempts to handle all network-related errors in the zhmcclient layer, if possible (e.g. timeouts, retries), so that the user of the package does not need to care about retries, and consider any raising of `zhmcclient.ConnectionError` to be not resolvable by user-level retrying.
The timeouts for async operation completion and LPAR status transition completion that were in an intermediate version of this PR have been removed again, so that this PR is now independent of PR #195 and needs to go in first. PR #195 will be changed to be based on this PR.
=> Improved handling of network errors

docs/changes.rst, docs/cli.rst, zhmccli/_helper.py, zhmccli/zhmccli.py
The following output formats are supported
in the CLI now: plain, simple, psql, rst,
mediawiki, html, LaTeX.
The default output format is still 'table'.
'table' and 'psql' are the same output formats.
A new section 'output formats' are added to
to CLI documentation.
=> Add more output formats to the CLI

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py
When a HBA is created a WWPN should be
assigned in the mock framework.
This WWPN is provided from a pool.
Fixes #212
=> Fixes #212: Assign WWPN for HBA in mock framework

docs/changes.rst, tests/unit/test_logging.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_client.py, zhmcclient/_constants.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_logging.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_notification.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_session.py, zhmcclient/_timestats.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
This PR is done, but it needs review to confirm that it is what we want.
With this change, there are now only two sets of log calls made:
1. API calls made by the user. Internal calls to API functions (made by zhmcclient itself) are not logged. The logger name for that is `zhmcclient.api`.
2. HMC operations. The logger name for that is `zhmcclient.hmc`.
3. There could be error and warning logs with the usual loggers that are named after the module names, but there are no such log calls currently.
For more details, see the commit message.
=> Fixes #205: Improved zhmcclient debug log calls

docs/changes.rst, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py
Details:
- Added the missing support for the `operation_timeout` argument to `FakedSession.post()`, in order to be compatible with the `Session.post()` that was changed recently.
- Added missing attributes of `FakedBaseResource` to `FakedHmc` by initializing the superclass and by tolerating `None` for the `manager` and `properties` arguments of `FakedBaseResource()`.
- Added `__repr__()` methods for all Faked* classes, that return a representation suitable for debugging.
- The FakedPartition/Lpar/Adapter/Cpc resources now auto-set a number of additional properties, if not specified in the input properties.
=> Fixes #211: Fixes and improvements in mock support

docs/changes.rst, zhmccli/_cmd_adapter.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_info.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_port.py, zhmccli/_cmd_session.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vswitch.py
The CLI spinner is correctly stopped but still appears with one character in the output. The reason for that is that it is still spinning while the output is written, and is stopped only after that. So the printing of the spinner character and the printing of the actual output interfere.
This change stops the spinner already before the output is written, so the spinner code itself cleans up the spinner characters.
=> Fixed display of CLI spinner in output

Makefile, docs/changes.rst, docs/conf.py
This change has no customer-visible effect, hence no entry in the change log.
Details:
- Fixed indentation errors in docs/changes.rst.
- Fixed "reference start-string without end-string" warnings in docs/changes.rst.
- Migrated from using the deprecated latex_paper_size option in the Makefile, to using the latex_elements['papersize'] definition in the docs/conf.py config file.
- Created an empty docs/_extra directory (with a dummy file in it) in order to get rid of the corresponding warning.
=> Fixed minor doc build issues

docs/changes.rst, tests/unit/test_timestats.py
This fixes some recent errors in Travis, e.g.:
* In PR #230 for Python 2 on OS-X: https://travis-ci.org/zhmcclient/python-zhmcclient/jobs/217215232
* In PR #227 for Python 3 on OS-X: https://travis-ci.org/zhmcclient/python-zhmcclient/jobs/217216057
Details:
- Measured the actual sleep time instead of using the requested sleep time.
- Added unit tests for average, min and max time.
=> Improved robustness of timestats unit tests.

docs/changes.rst, docs/cli.rst, docs/general.rst, tests/unit/test_timestats.py, zhmccli/_helper.py, zhmccli/zhmccli.py, zhmcclient/_session.py
Note that we now have both ZHMC_PASSWORD and ZHMC_SESSION_ID as environment variables, and either can be used to avoid the password prompt and use of the new password option. Maybe we need to clean that up a bit.
Details:
- Added a `-p` / `--password` option to specify the HMC password.
- Changed interface to password retrieval function invoked by 'Session'; it now has host and userid as arguments. This needed to be done because host and userid were passed by closure, while now they are passed explicitly. This also helps when users start using this feature.
- Added a `__repr__()` function for `CmdContext`, for better debugging.
=> Fixes #225: CLI: Added -p/--password option

docs/changes.rst, docs/cli.rst, zhmccli/_helper.py, zhmccli/zhmccli.py
Please review and test.
So far, tested on RHEL 7.2 with stderr and syslog.
Further tests would be useful with the syslog destination on OS-X, Windows, and AIX.
The syslog must be enabled for the "debug" priority.
Example commands for testing:
```
zhmc -h 10.... -u .... --log-dest syslog --log all=debug session create
sudo tail -n 50 <your-syslog-file>
```
Verify that you got some zhmcclient debug log records in the syslog file.
Make sure your syslog configuration has the "debug" priority enabled, and use the correct syslog file for that.
=> Fixes #113: CLI: Added logging support

docs/changes.rst, tests/unit/test_session.py, zhmcclient/_session.py
This improves the `HTTPError` that is raised for a job that completed in error, by also supporting the `error` field in the `job-results` object of the response. So far, only the `message` field was supported. The HMC API book is silent as to what the fields are on the `job-results` object when a job completes in error.
For more details, see the commit message.
=> Fixes #228: Added support for 'error' field in 'job-results'

.travis.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt
Please review and merge if the test runs succeed.
Background:
There were many indirect package dependencies that were not
listed in the requirements and version constraint files.
This resulted in an install failure when testing with
PACKAGE_LEVEL=minimum, because the specified old versions of
the packages that were listed, were mixed with the latest
versions of the packages that were not listed.
Details of changes:
- Added all missing package dependencies as of 2016-12-08, with
their versions as of that date as a minimum.
- Changed the minimum versions of already existing package
dependencies to the versions as of 2016-12-08. This resulted
sometimes in increasing the minimum version, and sometimes in
decreasing it.
=> Fixed package dependencies for minimum pkg level

docs/intro.rst
The heading of the section 'Installation on a system
without Internet access' was changed in the
dococumentation.
=> Changed documentation heading

docs/changes.rst, zhmccli/_cmd_partition.py
Details:
- Fixed that the defaults for memory for the 'zhmc partition create' command were ignored (issue #246).
- Changed the default for number of IFL processors for the 'zhmc partition create' command from 0 to 1, so that now a partition can be created with the defaults for any partition property options.
=> Fixes #246: Fixed defaults for 'zhmc partition create'

docs/changes.rst, zhmcclient/_constants.py
This PR mitigates issue #249. A final fix may or may not come, so this PR should be integrated in any case.
Details:
- This change sets the default values for the retry / timeout  configuration to read_timeout=3600 and read_retries=0. This  was needed in order to help with the issue that the 'requests' module re-requests a DELETE request another time if the first request is being processed but times out on the read timeout because it takes longer. The Delete Partition operation is such a candidate, at least when the partition got many NICs added and was started and stopped.
=> Mitigated issue with read retries and DELETE

docs/changes.rst, tests/unit/test_manager.py, tests/unit/test_partition.py, tests/unit/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_constants.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_session.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
Details:
* Fixed that resource creation, deletion, and resource property updating now properly updates the resource name-to-URI cache in the zhmcclient that is maintained in the `*Manager` objects. As part of that, the `BaseManager` init function got an additional required argument `session`, but because creation of manager objects is not part of the external API, this should not affect users. See issue #253.
* The `update_properties()` method of all Python resource objects now also updates the properties of that Python resource object with the properties provided by the user (in addition to issuing the corresponding Update Properties HMC operation. This was done because that is likely the expectation of users, and we already store user-provided properties in …
=> Fixes #253: Fixed stale name-to-URI cache and other improvements

docs/changes.rst, zhmccli/_cmd_partition.py
From the commit message:
This fixes issue #258, where a previous addition to the development version of v0.13.0 has caused the ifl-processors property to always be added to the Create Partition request, if the corresponding option had not been specified in the zhmc command line. Now, a default is only added if neither CPs nor IFLs are specified on the command line.
Also, in order to simplify the logic, if the IFL or CP option is specified with 0, that is no longer handled by removing the option from the properties sent to the HMC. Instead, the HMC is now going to reject that. This is more in line with having easy to understand logic on the client side.
=> Fixes #258: Fixed unconditional addition of ifl-processors in CLI

docs/changes.rst, tests/unit/test_activation_profile.py, tests/unit/test_adapter.py, tests/unit/test_hba.py, tests/unit/test_lpar.py, tests/unit/test_nic.py, tests/unit/test_partition.py, tests/unit/test_port.py, tests/unit/test_session.py, tests/unit/test_virtual_function.py, tests/unit/test_virtual_switch.py
Details:
- Fixed incorrect assumptions about their method return values. See issue #256.
- Fixed incorrectly returned response bodies for mocked DELETE and POST (for update), and replaced that with status 204 (no content). This came up as part of fixing issue #256.
=> Fixes #256: Fixes in unit tests for update_properties() and delete()

docs/changes.rst, tests/unit/test_hba.py, tests/unit/test_nic.py, tests/unit/test_port.py, tests/unit/test_virtual_function.py, zhmcclient/_hba.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py
From the commit message:
The find(name) method on element-kind of resources raised NotFound for existing resources. This was caused by the fact that the list() method for element-kind of resources returns Python resource
objects that do not have a "name" property, so the operation that is supposed to populate the name-URI-cache does not add anything. Because of the optimization in find(name) to always use the
name-URI-cache, it relies on that cache being populated. See issue #264.
This change fixes that by introducing knowledge into the manager class about whether the list() method for a resource class populates the "name" property. If that is not the case, the refresh() method of the name-to-URI cache sets the 'full_properties' flag when calling the list() …
=> Fixes #264: Fixed find(name) on element resources.

docs/changes.rst, tests/unit/test_hba.py, tests/unit/test_nic.py, tests/unit/test_port.py, tests/unit/test_virtual_function.py, zhmcclient/_hba.py, zhmcclient/_manager.py, zhmcclient/_nic.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py
Please review and merge. Note that there is a discussion point in issue #263 that should be considered in your review.
Details from the commit message:
* Fixed that the filter arguments for find(), findall(), and list() for string properties when matched on the client side are matched using regular expressions instead of exact matching, consistent with the zhmcclient documentation, and with server-side matching on the HMC. See issue #263.
* Fixed that the filter arguments for find(), findall(), and list() when used with lists of match values incorrectly applied ANDing between the list items. They now apply ORing, consistent with the zhmcclient documentation, and with server-side matching on the HMC. See issue #267.
=> Fixes #263, #267: Fixed client-side filter matching

docs/changes.rst, zhmcclient/_cpc.py, zhmcclient/_manager.py
Details from the commit message:
- In `BaseManager`, renamed `invalidate_name_uri_cache()` to `invalidate_cache()`. This is an incompatible change, but it was not yet released.
- In `BaseManager`, deprecated `flush()` by updating its documentation and by issuing a `DeprecationWarning`, if used.
- In `Cpc`, added issuing a `DeprecationWarning` in the already deprecated `vswitches` attribute.
=> Deprecated flush() and renamed invalidate_name_uri_cache()

docs/changes.rst, docs/concepts.rst, zhmcclient/_manager.py
Details from the commit message:
* Fixed that filter arguments specifying properties that are not on each resource, resulted in raising KeyError. An example was when the card-location property was specified when finding adapters; that property does not exist for Hipersocket adapters, ubt for all other types. This situation is now handled by treating such resources as non-matching. See issue #271.
* Added a docstring to the internal method _matches_prop().
=> Fixes #271: Fixed filter args for properties that are not on every resource

docs/changes.rst, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py
Details:
- zhmc cli need additional parameters for partition
create and update.
- zhmc cli need addtional parameters for NIC create
and  update.
=> Add Secure Service Container Support

docs/changes.rst, docs/development.rst
This change removes all empty list items in the change log for all releases. It also updates the description on how to make a release, by adding an action item toremove the empty list items in the change log section of the current release.
=> Remove empty list items in change log

docs/development.rst
Details:
- The Git repo is meanwhile set up such that direct pushes to the master branch are prohibited. This change updates the description on how to make a release and how to start a new release, to reflect that.
=> Fixed docs for releasing and starting new release

docs/changes.rst, zhmcclient/_constants.py
Increased the default status timeout from 60 sec to 15 min, in order to accomodate for some large environments. The status timeout applies to waiting for reaching the desired LPAR status after the HMC operation 'Activate LPAR' or 'Deactivate LPAR' has completed.
As long as this PR is not yet merged, it can be installed via:
pip install git+https://github.com/zhmcclient/python-zhmcclient.git@andy/increase-status-timeout
=> Increased default status timeout from 60s to 15min.

docs/changes.rst, tests/unit/test_timestats.py, zhmcclient/_timestats.py
**Note: This is an incompatible change for callers of `TimeStatsKeeper.snapshot()`. Review carefully.**
Details:
- Changed the return value of TimeStatsKeeper.snapshot() from a list of key/value tuples to a dictionary. This is more flexible and reduces the number of data structure conversions in different scenarios. See issue #269.
=> Fixes #269: Changed return value of TimeStatsKeeper.snapshot() from tuple list to dict

docs/changes.rst, zhmcclient/_partition.py
Details:
- Fixed the documentation of several asynchronous `Partition` methods
that incorrectly documented a return value `None` in case of synchronous
invocation, to now document a return value of an empty dictionary.
This is only a change in the documentation to make it match the existing
code.
This was done for these methods:
- `Partition.start()`
- `Partition.stop()`
- `Partition.dump_partition()`
- `Partition.psw_restart()`
All other asynchronous methods did not have this issue.
=> Fixes #248: Doc fixes for return value of asynchronous Partition methods

docs/changes.rst, tests/unit/test_session.py, zhmcclient/_session.py
To try this change out, install zhmcclient using:
```
pip install git+https://github.com/zhmcclient/python-zhmcclient.git@andy/improve-parse-error
```
=> Fixes #298: Improved ParseError message for better diagnosing.

docs/changes.rst, zhmccli/_cmd_lpar.py, zhmcclient/_exceptions.py, zhmcclient/_lpar.py
As long as this PR is not yet merged, it can be installed via:
pip install git+https://github.com/zhmcclient/python-zhmcclient.git@andy/fix-status-timeout
This change provides some improvement for the zhmc CLI when dealing with the LPAR status "exceptions" when activating, deactivating or loading the LPAR.
The main change is to add a command line option `--allow-status-exceptions` for the `lpar activate/deactivate/load` commands. Setting this option causes the LPAR status "exceptions" to be considered an additional valid end status.
Some other changes were needed as part of that:
* Allowed `None` as a value for the `load_parameter` argument of `Lpar.load(), and changed the default to be `None` (which does not change the behavior).
* Added actual status, desired statuses and status timeout …
=> CLI: Improvements for dealing with LPAR status 'exceptions'.

requirements.txt
The `requests` 2.17.1 package introduced an issue, in that urllib3 is no longer in requests.packages:
```
python -c "import zhmcclient; print('Import: ok')"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "zhmcclient/__init__.py", line 30, in <module>
from ._session import *       # noqa: F401
File "zhmcclient/_session.py", line 29, in <module>
from requests.packages import urllib3
ImportError: cannot import name urllib3
```
The `requests` 2.17.0 package still worked fine.
This PR excludes 2.17.1 and 2.17.2 in the `requirements.txt` file.
Update: requests 2.17.3 provides a final fix.
=> Circumvented urllib3 issue with requests 2.17.1 and 2.17.2

docs/changes.rst, docs/cli.rst, examples/show_os_messages.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py, zhmccli/_helper.py, zhmccli/zhmccli.py, zhmcclient/_constants.py
This change adds support to the zhmc CLI for an interactive shell to the console of the operating system running in a partition or LPAR. The new commands are `zhmc partition console` and `zhmc lpar console`.
=> Fixes #203: CLI: Added support for an OS console into partition/LPAR.

docs/changes.rst, docs/cli.rst, docs/general.rst, tests/unit/test_exceptions.py, zhmccli/_cmd_adapter.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_info.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_port.py, zhmccli/_cmd_session.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vswitch.py, zhmccli/_helper.py, zhmccli/zhmccli.py, zhmcclient/_exceptions.py
Details:
- Added `str_def()` methods to all zhmcclient exceptions. These methods return a string that is suited for being processed by scripts that invoke the zhmc CLI.
- Added a command line option `-e` / `-error-format` to the zhmc cli, which controls the format of any error messages. The `-e def` option selects the format returned by the `str_def()` methods.
=> Added support for selecting the format of CLI error messages

docs/changes.rst, zhmcclient/_exceptions.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
Details:
- The `wait_for_status()` method for the `Lpar` class was already available
as an internal method, which was simply externalized.
- For the `Partition` class, a similar method has been added.
- The reason for these methods is that they make it much easier to ensure
a particular operational status.
=> Added wait_for_status() methods to Lpar and Partition.

docs/changes.rst, zhmccli/_cmd_partition.py
Details:
When we try to set the --ssc-dns-servers in the
zhmc partition create or update command we get
an HTTPError: 400,7 because the HMC expects
an array for this option. This change fills
the passed ssc-dns-servers separated by a comma
into an array. A maximum of two ssc-dns-servers
are accepted by the HMC.
Resolves #310
=> Fix ssc-dns-servers option handling in CLI

Makefile, docs/changes.rst
Previously, it was part of the 'check' make target. The motivation for this change is to shorten the CI runs.
=> Moved PyLint invocation into its own 'pylint' make target.

docs/changes.rst, examples/example_hmccreds.yaml, examples/mount_iso.py, tests/unit/test_partition.py, zhmcclient/_partition.py, zhmcclient/_session.py
Now ready for review and merge. It works now, if one satisfies the requirements for the image_name property which are now properly documented.
One more thing: Because this operation takes a long time, it would be nice  to be able to register a call back function for monitoring the upload progress. That is not yet in the current code, and could be added compatibly with an optional parameter.
Note, this is an incompatible change but that was unavoidable.
=> Fixes #57: Corrected parameters of Partition.mount_iso_image()

examples/example_hmccreds.yaml, examples/get_inventory.py, zhmcclient/_client.py
**Does not yet contain unit test code!**
Use the `examples/get_inventory.py` script to try it out.
=> Added support for Get Inventory operation

docs/changes.rst, tests/unit/test_adapter.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient_mock/_hmc.py
The max domains property in the Adapter class has unit test code.
The max partitions property in the Cpc class does not have unit test code because it has not yet been converted to use the zhmcclient mock support. It will be added once that happens.
=> Added properties for max partitions to Cpc and for max crypto domains to Adapter

tests/unit/common/test_utils.py, tests/unit/utils.py
This PR will be used by multiple other PRs on testcases.
At this point, the module has only one function `assert_resources()` which checks a list of resources against an expected list of (real or faked) resources.
=> Created tests/unit/utils.py with shared code between the testcases

docs/changes.rst, zhmccli/_cmd_nic.py
Today,  the vlan-id is passed as a string to
the HMC WS API by the CLI. The HMC returns a
HTTPError: 400,7 because it expects that the
vlan-id is an integer. This change reads the
vlan-id as a integer instead as a string.
=> vlan-id must be an integer

docs/changes.rst, examples/example_hmccreds.yaml, examples/list_free_crypto_domains.py, tests/unit/test_adapter.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py
This PR is now ready for being merged - the new functionality has been described as experimental.
Details:
- Added the `get_free_crypto_domains()` method to the `Cpc` class, in order to find out free domain index numbers for a given set of crypto adapters.
- Added an example script `list_free_crypto_domains.py` that demonstrates the new method.
=> Added support for listing free crypto domains

docs/changes.rst, zhmcclient/_cpc.py, zhmcclient/_lpar.py
The testcase migration changes will depend on this change.
**Note:** Unit test code will be added when migrating these resource types to py.test and zhmcclient mock support.
=> Added update_properties() to Cpc and Lpar.

tests/unit/test_activation_profile.py, tests/unit/test_adapter.py, tests/unit/test_cpc.py, tests/unit/test_partition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
This PR is on top of PRs #350 and #351 and #354.
Part1 is for the zhmcclient resources: ActivationProfile, Adapter, Cpc, Partition.
The unit tests contains some TODOs for stuff that was missing already before the migration.
=> Test: Migrated unit tests to py.test + zhmcclient mock, part 1

.travis.yml
A Travis cron job has been defined that currently runs daily. The cron job is expected to run the full job (including the build abd builddoc make targets). Travis runs triggered by GitHub (e.g. on this PR) are expected to not run these steps.
Details:
- The 'make build' and 'make builddoc' steps are now run only if the travis run is triggered by Travis cron. The runs triggered by GitHub no longer run these steps.
- Removed the multiple package levels from the OS-X runs - it is sufficient if they are run on Linux.
=> Reduced Travis CI further.

docs/changes.rst, zhmcclient/_hba.py, zhmcclient/_nic.py
Ready to be merged. Doc-only!
Details:
- Improved the description of the Nic and Hba create() method to explain how the backing adapter port is specified, and how it can be determined from adapter name and port index. This is specifically interesting for OSa and HiperSockets adapters, because the virtual switch that is needed, is not familiar to users of the HMC GUI.
=> Docs: Improved Nic/Hba.create() descriptions.

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
**Note:** This PR is on top of PRs #359 and #360.
=> Fixes #316: Mock: Added support for remaining partition ops in URI handler.

docs/changes.rst, docs/cli.rst, tests/unit/test_hba.py, tests/unit/test_manager.py, tests/unit/test_port.py, tests/unit/test_resource.py, zhmccli/__init__.py, zhmccli/_cmd_metrics.py, zhmccli/_helper.py, zhmccli/zhmccli.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_lpar.py, zhmcclient/_manager.py, zhmcclient/_metrics.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_port.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_switch.py
- Report CPC metrics: zhmc metrics cpc <CPC>
This command provides metrics returned by the
Metric Group 'cpc-usage-overview' for a not
in DPM enabled CPC and provides metrics returned
by the Metrics Group 'dpm-system-usage-overview'
for a DPM enabled CPC.
- Report metrics of Partitions of a CPC:
zhmc metrics partitions <CPC>
This command provides metrics returned by the
Metric Group 'partition-usage'.
- Report metrics of LPARs of a CPC:
zhmc metrics lpars <CPC>
This command provides metrics returned by the
Metric Group 'logical-partition-usage'.
=> CLI: Add "metrics" command group

zhmccli/_cmd_partition.py
This change enables the CLI to enable/disable
the partition controls
- 'access-global-performance-data'
- 'permit-cross-partition-commands'
- 'access-basic-counter-set'
- 'access-basic-sampling'
- 'access-coprocessor-group-set'
- 'access-crypto-activity-counter-set'
- 'access-diagnostic-sampling'
- 'access-extended-counter-set'
- 'access-problem-state-counter-set'
during 'partition create' and
'partition update'.
=> Fixes #380: CLI support for enable partition controls

docs/changes.rst, zhmccli/_cmd_partition.py
Follwing processing weights can be modified
during 'partition create' and 'partition
update':
- initial-cp-processing-weight
- initial-ifl-processing-weight
- maximum-cp-processing-weight
- maximum-ifl-processing-weight
- minimum-cp-processing-weight
- minimum-ifl-processing-weight
=> CLI support for processing weights

.codeclimate.yml
Code Climate is a fully-configurable static analysis
tool. This change will provide a .codeclimate.yml
configuration file which enables the two Code Climate
engines Radon (https://github.com/rubik/radon) and Duplication
(https://github.com/codeclimate/codeclimate-duplication).
Radon is a Python tool that computes various metrics like
cyclomatic complexity from the source code.
Duplication analyzes code for structural similarities.
=> Add config file for Code Climate tool

README.rst, docs/appendix.rst, docs/cli.rst, docs/conf.py, docs/index.rst, docs/intro.rst, setup.cfg, zhmccli/zhmccli.py, zhmcclient/__init__.py, zhmcclient/_cpc.py, zhmcclient/_metrics.py
The z Systems family was rebranded to IBM Z.
This change renames documentation and code
in the project.
=> Rename z Systems family to IBM Z

docs/changes.rst, zhmccli/_helper.py
Verified that the problem can be reproduced and that this change fixes the problem, on RHEL 7.3 with Python 3.6 and with the "zhmc partition update" command.
=> Fixes #396: CLI: Fixed AttributeError with dict.iteritems() on Python 3.

docs/changes.rst, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py
The options for the update commands (e.g. partition)
must not have any default values. Otherwise,
the default value is set and the current value is overwritten
although the option is not specified in the update command.
Resolves #405
=> CLI: Remove defaults for options for 'partition update'

.travis.yml, docs/changes.rst
The sudo requirement is not needed, and not requiring sudo has the benefit that Travis CI will deploy the test runs into containers, instead of creating virtual systems.
=> Removed sudo requirement from Travis

docs/changes.rst, zhmccli/_helper.py, zhmccli/zhmccli.py
A particular point of review might be that the "Error: " prefix added by `click.ClickException` is overwritten with a CR character in our message text, in `abort_if_false()`.
=> Fixes #418: CLI: Fixed AttributeError when aborting confirmation question

.travis.yml
For reviewing this:
* Look at the Travis results for this PR. You will see more combinations than before,  and those with a short run time are the ones that will only perform real check work in a cron-triggered Travis run. They end quickly in a PR-triggered Travis run (like this one).
* The cron-triggered Travis runs run daily but only on the master branch, so checking that the cron-triggered runs actually check something can only be done once this PR has been merged to master.
* For a comparison of the elapsed time for Travis runs, there are two data points:
* [Travis build #2258](https://travis-ci.org/zhmcclient/python-zhmcclient/builds/271590863) of this PR has an elapsed time of 11:35
* [Travis build …
=> Fixes #355: Expanded the regular cron-triggered Travis run.

Makefile, minimum-constraints.txt
This change contains a circumvention for issue #434.
Ready to be reviewed and merged.
=> Circumvented ImportError for build_clib on Travis with Py 2.7.13

tests/unit/zhmcclient_mock/test_urihandler.py
The master branch does not pass the unit tests in Travis
because the test_create_get_delete_context()
in MetricsContextHandlersTests is failing.
This change comments out test create_get_delete_context()
to pass Travis unit tests in master branch.
This change is related to issue #441.
=> Fix TypeError in zhmcclient_mock/_urihandler.py

Makefile, minimum-constraints.txt
**Note:** This PR is on top of PR #431.
This change eliminates two kinds of things that appear during Travis runs:
* Warnings that statements with environment markers in the constraints file are being ignored due to not being in that environment. A constraints file does not need environment markers at all.
* Exceptions when the makefile tries to determine the package version before the packages needed for importing zhmcclient are installed. They did not hurt because that variable was not used in make runs where this occurred.
=> Fix warnings and (unproblematic) exceptions during Travis runs

docs/changes.rst, zhmccli/_cmd_partition.py
With the new CLI command 'zhmc partition mountiso'
an user provided ISO image can be uploaded.
The uploaded ISO image is the image that gets attached
to the partition. If an ISO is attached to a partition,
it can be shown by the partition property 'boot-iso-image-name'.
To boot from this ISO image the partition property
'boot-device' must be set to 'iso-image' before starting
the partition.
With the new CLI command 'zhmc partition unmountiso'
the user unmounts the currently mounted ISO from
the partition. The partition property 'boot-iso-image-name'
is empty then.
=> Add CLI support for mount and unmount an ISO

docs/changes.rst
**Note:** The tag for 0.18.0 has not yet been set.
=> (#2) Release 0.18.0

.travis.yml, appveyor.yml, docs/changes.rst
**Note:** This PR is on top of PR #454.
Details:
- This change enables Travis and Appveyor to distinguish between quick runs and full runs. Runs from branch manual-ci-run are run as full runs (after locally rebasing to master), and all other branches are run as quick runs.
=> (#4) Enabled Travis and Appveyor for manual-ci-run.

.travis.yml, Makefile, appveyor.yml, docs/changes.rst, tests/unit/common/test_utils.py, tests/unit/test_client.py, tests/unit/test_exceptions.py, tests/unit/test_hba.py, tests/unit/test_logging.py, tests/unit/test_lpar.py, tests/unit/test_manager.py, tests/unit/test_nic.py, tests/unit/test_notification.py, tests/unit/test_port.py, tests/unit/test_resource.py, tests/unit/test_session.py, tests/unit/test_timestats.py, tests/unit/test_utils.py, tests/unit/test_virtual_function.py, tests/unit/test_virtual_switch.py, tests/unit/zhmcclient_mock/test_example.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_idpool.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_session.py
**Note:** This PR is on top of PR #452.
Note that migration from mock/requests_mock to zhmcclient_mock is left for a future PR.
=> (#7) Fixes #458: Migrated remaining test cases from unittest to py.test.

Makefile, docs/changes.rst, docs/development.rst, examples/example_hmccreds.yaml, tests/common/utils.py, tests/function/test_hmc_credentials_file.py, tests/function/test_partition_lifecycle.py, tests/unit/zhmcclient/test_logging.py, zhmcclient/_logging.py
By default (e.g. in a CI), the function tests will either be skipped, or run against a faked/mocked environment. To set up testing against a real HMC/CPC, read the respective chapters in section "Development" in the docs.
=> Fixes #470: Added function test concept

.gitignore
=> Excluded .DS_Store file (on OS-X) from git

docs/changes.rst, docs/intro.rst, tools/cpcdata, zhmcclient/_adapter.py, zhmcclient/_cpc.py
Ready for review and merge, except for this TODO:
* Clarify whether the use of HMC version 2.14.0 for the second wave of z14 machines is intentional (the zhmcclient docs make a statement about that).
=> Added z14-ZR1 and Rockhopper II support

tests/unit/zhmcclient/test_utils.py, zhmcclient/_utils.py
This PR will be used by the DPM storage group support.
=> Fixed issue with None input in _utils.repr_*()

docs/changes.rst, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient_mock/_hmc.py
This PR will be used by the DPM storage group support.
=> Direct access to the one Console object

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_cpc.py, zhmcclient/_partition.py
This PR will be used by the DPM storage group support.
**Important review point:**
* In case the feature is unknown or in case the CPC does not support features at all, should the `feature_enabled()` functions (1) raise `ValueError` as they do currently, or (2) return `False`? Returning `False`is more convenient, but does not allow distinguishing between feature available+disabled and feature unavailable (=unknown).
=> Inspection of firmware features

design/dpm-storage-model.rst, docs/appendix.rst, docs/changes.rst, docs/resources.rst, examples/example_hmccreds.yaml, examples/list_storage_groups.py, tests/end2end/test_storage_group.py, tests/unit/zhmcclient/test_storage_group.py, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_partition.py, zhmcclient/_storage_group.py, zhmcclient/_storage_volume.py, zhmcclient/_virtual_storage_resource.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
**Note: This PR is on top of PRs #526, #527, #528, #529.**
This PR provides support for DPM storage groups for FCP. The implementation is complete, but test cases and mock support are incomplete at this point and are left for a future PR.
=> Added support for DPM storage groups for FCP

docs/changes.rst, minimum-constraints.txt, requirements.txt
The Requests package through 2.19.1 before 2018-09-14
for Python sends an HTTP Authorization header to
an http URI upon receiving a same-hostname
https-to-http redirect, which makes it easier
for remote attackers to discover credentials
by sniffing the network.
Link to vulnerability in National Vulnerability
Database:
https://nvd.nist.gov/vuln/detail/CVE-2018-18074
=> Update requests package to 2.20.0 in requirements.txt

docs/changes.rst, zhmcclient/_adapter.py
Details:
* Added a mitigation for a firmware defect that causes filtering of
adapters by adapter-id to return an empty result when the specified
adapter-id contains hex digits ('a' to 'f'). See issue #549.
=> Mitigated that fIltering by adapter-id returns empty result for hex digits

tests/example_hmc_definitions.yaml, tests/faked_hmc1.yaml, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient/testutils/hmc_definitions.py
**Note:** This PR is on top of PR #556 - review only the last commit.
=> Added support for faked HMCs to end2end tests

dev-requirements.txt
=> Pinned Sphinx to below 2.0.0 also for py3.5+

docs/changes.rst, zhmcclient/_notification.py
=> Changed import of stomp module to be lazy for zhmcclient import speed

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
Following LPAR commands are added:
- psw_restart()
- scsi_dump()
=> Add more LPAR commands

docs/appendix.rst, docs/changes.rst, docs/resources.rst, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume_template.py
At this point, the support is completely implemented and documented and ready for trying it out, but tests or mock support is not implemented at this point.
To try it out, build the documentation from this branch using `make builddoc` and the starting points for reading are `Console.storage_group_templates` and `StorageGroupManager.create()`.
=> Fixes #589: Added support for Storage Templates

zhmcclient/_lpar.py
For details please take a look at the documentation for the "SCSI
Dump" HMC web services API.
Signed-off-by: Marc Hartmayer <mhartmay@linux.ibm.com>
=> lpar: scsi_dump: add missing `os-ipl-token` parameter

.travis.yml, appveyor.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt, requirements.txt, setup.cfg, tox.ini
See the manual-ci-run branch for a test on all Python versions, that one should pass before merging this PR.
=> Fixes #596: Added support for Python 3.8 and increased several minimum package versions

examples/jms_notifications.py, minimum-constraints.txt, requirements.txt, zhmcclient/_notification.py
"stomp.py" >= 5.0.0 is not compatible with our code, because in this
version the `start` method for STOMP connections has been removed (see
https://github.com/jasonrbriggs/stomp.py/commit/7648ef770b6ec4691fab552085461b96c728f487).
To fix this issue, increase the minimum version of "stomp.py" and drop
the `conn.start()` calls.
Signed-off-by: Marc Hartmayer <mhartmay@linux.ibm.com>
=> Increase the minimum version of stomp.py to >= 4.1.21

docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Increased stomp.py to 4.1.23 to address hang in NotificationReceiver.close()

.travis.yml
Note that Python 3.4 fails currently, but that is unrelated to this PR and will be fixed later.
=> Travis: Removed workarounds, changed matrix to jobs, added blank lines

docs/changes.rst
Note: The is PR also delivers change history updates to the changes since the release was actually started, that were forgotten.
=> Start 0.27.0

appveyor.yml, docs/changes.rst
Rolls back PR #656 into 0.26.2.
=> 0.26: Test: Fixed missing ffi.h file on CygWin when testing

docs/changes.rst, zhmcclient/_adapter.py
Rolls back PR #664 into 0.26.2.
=> 0.26: Fixed empty port list returned by PortManager.list() for CNA adapters

docs/changes.rst, zhmcclient/_adapter.py
=> Fixed empty port list returned by PortManager.list() for CNA adapters

docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 0.26.2.
The main trigger for this release is the CNA fix.
For the changes in this version, see https://github.com/zhmcclient/python-zhmcclient/blob/release_0.26.2/docs/changes.rst
=> Release 0.26.2

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_cpc.py, zhmcclient_mock/_urihandler.py
=> Added support for operations for managing temporary processor capacity

docs/changes.rst, zhmcclient/_partition.py
This PR integrates PR #685, with the following changes on top:
- moves the change log entry to the correct version 0.28.0 and made editorial changes to it.
=> Timeout added to allow hmc to wait for partition to stop

docs/changes.rst, zhmcclient/_session.py
=> Blanked out value of 'x-api-session' field (Session ID) in error responses

Makefile, dev-requirements.txt, minimum-constraints.txt
=> Circumvented an install failure of lazy-object-proxy on py35/minimum

docs/changes.rst, requirements.txt
=> Circumvented a missing argument in 'NotificationListener.on_message()'

docs/changes.rst, requirements.txt
Rolls back PR #764 into 0.30.1.
=> 0.30: Circumvented a missing argument in 'NotificationListener.on_message()'

docs/appendix.rst, docs/changes.rst, docs/index.rst, docs/security.rst, tests/unit/zhmcclient/test_session.py, zhmcclient/_session.py
Note that the new `verify_cert` parameter has a default of `False` in order to be backwards compatible. Thinking about that should be one review point.
Direct links for reviewers:
* New "Security" section: https://github.com/zhmcclient/python-zhmcclient/blob/andy/add-verify-cert/docs/security.rst
* New "Troublsshooting" section: https://github.com/zhmcclient/python-zhmcclient/blob/andy/add-verify-cert/docs/appendix.rst#troubleshooting
* New `verify_cert` init parameter: https://github.com/zhmcclient/python-zhmcclient/blob/andy/add-verify-cert/zhmcclient/_session.py#L357
Note that the rendered .RST files show some of the links in a strange way. The built documentation will have them right.
=> Added server cert verification, security docs, trouble shooting docs

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #773 into 0.30.2.
=> 0.30: Fixed install error for "pywinpty" on py27/windows

docs/appendix.rst, docs/changes.rst, docs/security.rst, tests/unit/zhmcclient/test_session.py, zhmcclient/_session.py
**Note: This PR changes the default for the recently added `verify_cert` parameter of `zhmcclient.Session` to True, which is an incompatible change.**
The new default value of True will cause the HMC server certificate to be validated against the CA certificates in the 'certifi' package. If you run the HMC with self-signed certificates, or if its certificate has a certificate chain not covered by the 'certifi' package, communication with the HMC will fail. 
This PR should not be merged until we have extended all zhmcclient packages to support HMC certificate validation:
- zhmccli: DONE (PR https://github.com/zhmcclient/zhmccli/pull/178)
- zhmc-prometheus-exporter: DONE (PR https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/144)
- zhmc-ansible-modules: DONE (PR …
=> Certificate verification, part 2

docs/changes.rst, docs/conf.py, minimum-constraints.txt, requirements.txt, tests/unit/zhmcclient/test_resource.py, zhmcclient/_activation_profile.py, zhmcclient/_adapter.py, zhmcclient/_capacity_group.py, zhmcclient/_cpc.py, zhmcclient/_hba.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_lpar.py, zhmcclient/_metrics.py, zhmcclient/_nic.py, zhmcclient/_partition.py, zhmcclient/_password_rule.py, zhmcclient/_port.py, zhmcclient/_resource.py, zhmcclient/_storage_group.py, zhmcclient/_storage_group_template.py, zhmcclient/_storage_volume.py, zhmcclient/_storage_volume_template.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient/_virtual_function.py, zhmcclient/_virtual_storage_resource.py, zhmcclient/_virtual_switch.py, zhmcclient_mock/_hmc.py
This is a preparation for resource caching as proposed in issue #762, since it ensures that users cannot modify the properties dictionary.
**This is for review and discussion, not yet ready to merge.**
=> Changed properties attribute to be immutable

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed install error of laxy-object-proxy on Python 3.5

docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 0.32.1.
Change log:
**Bug fixes:**
* Fixed a bug where 'Console.list_permitted_partitions()' and
'Console.list_permitted_lpars()' when run on HMC/SE version 2.14.0 failed
when accessing the 'se-version' property of the partition unconditionally.
That property was introduced only in HMC/SE version 2.14.1. (issue #816)
=> Release 0.32.1

docs/changes.rst, docs/concepts.rst, docs/general.rst, examples/show_auto_update.py, examples/show_object_notifications.py, tests/unit/zhmcclient/test_notification.py, tests/unit/zhmcclient/test_port.py, tests/unit/zhmcclient/test_resource_updater.py, tests/unit/zhmcclient/test_session.py, tests/unit/zhmcclient/test_virtual_function.py, tests/unit/zhmcclient/test_virtual_switch.py, zhmcclient/__init__.py, zhmcclient/_constants.py, zhmcclient/_logging.py, zhmcclient/_resource.py, zhmcclient/_resource_updater.py, zhmcclient/_session.py, zhmcclient_mock/_session.py
**Note: This PR is on top of PR #815 - review only the last commit**
Ready for review and for trying out, e.g. with the new `show_auto_update.py` example script.
No more open TODOs at this point.
=> Added support for auto-updating of zhmcclient resource objects

.github/workflows/test.yml, docs/changes.rst, zhmcclient/_version.py
Please approve the release of zhmcclient 1.0.0.
Change history: https://github.com/zhmcclient/python-zhmcclient/blob/release_1.0.0/docs/changes.rst#version-100
=> Release 1.0.0

zhmcclient/_lpar.py
This fixes the following problem:
$ zhmc -o json lpar stop --yes --allow-status-exceptions CPC LPAR
Error: HTTPError: 400,4: A content-length was specified but a body was not expected by this provider. [POST /api/logical-partitions/xxx/operations/stop]
According to the HMC REST API 2.15, the LPAR STOP operation doesn't expect
any body, not even an empty one.
See "Hardware Management Console Web Services API Version 2.15.0",
"Chapter 11. Core IBM Z resources", "Stop Logical Partition".
Signed-off-by: Alexander Egorenkov <egorenar@linux.ibm.com>
=> lpar: Fix body issue with STOP operation

docs/changes.rst, zhmcclient/_lpar.py
Rolls back PRs #828 and #831 into 1.0.2.
=> 1.0: lpar: Fix completion statuses for STOP operation

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Dev: Excluded more-itertools 8.11.0 on Python 3.5

Makefile, docs/changes.rst
Rolls back PR #866 into 1.1.1.
=> 1.1: Removed the ability to build the Windows executable

tests/end2end/test_ldap_server_definition.py, tests/end2end/utils.py
=> End2end tests: Took TestWarning away from pytest by renaming to End2endTestWarning

Makefile
=> Support for TESTOPTS containing blanks

docs/changes.rst, zhmcclient/_storage_volume_template.py
=> Fixed HMC field error in StorageVolumeTemplate.delete()

docs/changes.rst, zhmcclient/_storage_volume_template.py
=> 1.1: Fixed HMC field error in StorageVolumeTemplate.delete()

docs/changes.rst, minimum-constraints.txt, requirements.txt, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient/test_manager.py, tests/unit/zhmcclient/test_user.py, tests/unit/zhmcclient/test_user_pattern.py, tests/unit/zhmcclient/test_user_role.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_manager.py, zhmcclient/_password_rule.py, zhmcclient/_user.py, zhmcclient/_user_pattern.py, zhmcclient/_user_role.py, zhmcclient_mock/_hmc.py
Even though this is a bug fix, it will not be rolled back to the stable release, because it adds a new package dependency (nocasedict package).
=> Fixed case insensitive names for users/roles/patterns/rules/ldap

docs/changes.rst, zhmcclient_mock/_hmc.py
=> Mock support: Fixed error in repr() when FakedAdapter() raised InputError

docs/changes.rst, zhmcclient_mock/_hmc.py
Rolls back PR #927 into 1.1.2.
=> 1.1: Mock support: Fixed error in repr() when FakedAdapter() raised InputError

docs/changes.rst, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_urihandler.py
Rolls back PR #931 into 1.1.2.
=> 1.1: Mock support: Fixed list of properties returned by "List Adapters of CPC"

dev-requirements.txt, docs/changes.rst, docs/conf.py, docs/mocksupport.rst, minimum-constraints.txt, requirements.txt, tests/common/utils.py, tests/faked_z13_classic.yaml, tests/faked_z13_dpm.yaml, tests/unit/zhmcclient/test_metrics.py, tests/unit/zhmcclient/test_utils.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_session.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_adapter.py, zhmcclient/_client.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_manager.py, zhmcclient/_metrics.py, zhmcclient/_partition.py, zhmcclient/_resource.py, zhmcclient/_storage_group.py, zhmcclient/_utils.py, zhmcclient/testutils/hmc_definition_fixtures.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py
This is a first step towards consolidating end2end testing and mock environment testing, so that we can write testcases that run against both real and mocked environments.
=> Support for saving and restoring faked resources to enable common tests 

docs/changes.rst, zhmcclient/_lpar.py
Rolls back PR #946 into 1.2.1.
=> 1.2: Added the missing secure_boot parameter to Lpar.scsi_dump()

tests/end2end/utils.py
=> Improved error message about non-unique names in end2end test

tests/end2end/utils.py
Rolls back PR #964 into 1.2.2.
=> 1.2: Improved error message about non-unique names in end2end test

docs/changes.rst, zhmcclient/_lpar.py
=> Lpar.list() with no matching filters now returns empty result set

.github/workflows/test.yml, docs/changes.rst, docs/development.rst, tests/end2end/test_activation_profile.py, tests/end2end/test_adapter.py, tests/end2end/test_capacity_group.py, tests/end2end/test_console.py, tests/end2end/test_cpc.py, tests/end2end/test_hba.py, tests/end2end/test_hmc_definitions.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_lpar.py, tests/end2end/test_nic.py, tests/end2end/test_partition.py, tests/end2end/test_password_rule.py, tests/end2end/test_port.py, tests/end2end/test_storage_group.py, tests/end2end/test_storage_group_template.py, tests/end2end/test_storage_volume.py, tests/end2end/test_storage_volume_template.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py, tests/end2end/test_virtual_function.py, tests/end2end/test_virtual_switch.py, zhmcclient/testutils/__init__.py, zhmcclient/testutils/_cpc_fixtures.py, zhmcclient/testutils/_hmc_definition_fixtures.py, zhmcclient/testutils/_hmc_definitions.py
=> Made testutils names importable from zhmcclient.testutils

zhmcclient/testutils/_hmc_definition_fixtures.py
=> Reduced read timeout in end2end tests to 120 sec

docs/changes.rst, tests/end2end/test_console.py, tests/end2end/test_cpc.py, tests/end2end/test_ldap_server_definition.py, tests/end2end/test_password_rule.py, tests/end2end/test_task.py, tests/end2end/test_user.py, tests/end2end/test_user_pattern.py, tests/end2end/test_user_role.py
=> End2end test: Removed CPC scope from test functions for HMC-based resources

docs/changes.rst, tests/end2end/test_cpc.py
=> End2end test: Fixed volatility of CPC property 'last-energy-advice-time'

zhmcclient/testutils/_cpc_fixtures.py, zhmcclient/testutils/_hmc_definition_fixtures.py
=> Made fixtureid functions tolerant against pytest NotSetType

docs/changes.rst, zhmcclient/_constants.py
=> Made the 'JMS_LOGGER_NAME' symbol publicly available

docs/changes.rst, zhmcclient/_constants.py
Rolls back PR #1009 into 1.3.1.
=> 1.3: Made the 'JMS_LOGGER_NAME' symbol publicly available

docs/changes.rst, examples/dump_hmc_definition.py, tests/common/utils.py, zhmcclient/_console.py, zhmcclient/_partition.py, zhmcclient/_port.py
=> Fixed dumping of HMC definitions; Added dump_hmc_definition.py example

docs/changes.rst, examples/dump_hmc_definition.py, tests/common/utils.py, zhmcclient/_console.py, zhmcclient/_partition.py, zhmcclient/_port.py
Rolls back PR #1005 into 1.3.1
=> 1.3: Fixed dumping of HMC definitions; Added dump_hmc_definition.py example

docs/changes.rst, zhmcclient_mock/_urihandler.py
Needed for https://github.com/zhmcclient/zhmc-ansible-modules/pull/537
=> Improved mock support for password rules by creating default properties

docs/changes.rst, docs/concepts.rst, docs/general.rst, examples/show_auto_update.py, tests/end2end/test_resource_auto_update.py, zhmcclient/_exceptions.py, zhmcclient/_resource.py, zhmcclient/_resource_updater.py, zhmcclient/testutils/_hmc_definition_fixtures.py
* Behavior when using properties or methods of auto-updated resources that no longer exist on the HMC. Which ones should raise the `CeasedExistence` exception?
=> Extended auto-update support to cover resources that no longer exist

docs/changes.rst, tests/end2end/test_storage_volume.py, tests/end2end/utils.py
=> Added tolerance against non-unique storage volume names in HMC 2.14.0

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1053 into 1.4.1.
=> 1.4: Fixed a flake8 AttributeError by pinning importlib-metadata

zhmcclient/_adapter.py
The documentation for crypto adapters only includes CEX5S/6S generations. I added information about 7S/8S and their supported models in the Reference section.
Signed-off-by: Marcos Araque <marcos.araque.fiallos@ibm.com>
=> documentation: updated crypto adapter info

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1079 into 1.5.1.
=> 1.5: Fixed install error of pywin32-ctypes on Windows with py38+

docs/changes.rst, docs/conf.py, zhmcclient/_utils.py
This fixes the recent weekend build issue on Python 3.10
=> Fixed docs issues & missing datetime_from_timestamp/timestamp_from_datetime

docs/changes.rst, docs/conf.py, zhmcclient/_utils.py
Rolls back PR #1082 into 1.5.1.
No additional review needed - but needs to wait for PR #1082 to be merged.
=> 1.5: Fixed docs issues & missing datetime_from_timestamp/timestamp_from_datetime

docs/changes.rst, zhmcclient/_cpc.py
* Support for exporting Z16 Partition Links
Signed-off-by: Edwin Günthner <edwin.guenthner@de.ibm.com>
=> Support for exporting Z16 Partition Links

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #1089 into 1.5.1.
=> 1.5: Fixed Python versions of pylint dependents

docs/changes.rst, zhmcclient/_cpc.py
This change ensures that the lists that are part of the dpm export output are sorted meaningfully, to acquire more stable results when exporting. Fixes #1116.
=> Fixes #1116: sort lists in export data

docs/changes.rst, zhmcclient/_metrics.py
Tested the bug fix with zhmc-prometheus-exporter.
=> Fixed incorrect list of managers in MetricsResourceNotFound when CPC not found

Makefile, docs/development.rst, examples/example_hmc_inventory.yaml, examples/example_hmc_vault.yaml, zhmcclient/testutils/__init__.py, zhmcclient/testutils/_cpc_fixtures.py, zhmcclient/testutils/_hmc_definition_fixtures.py, zhmcclient/testutils/_hmc_definitions.py, zhmcclient/testutils/_hmc_inventory_file.py, zhmcclient/testutils/_hmc_vault_file.py
To read the updated documentation, run `make builddoc` with this branch checked out and read these sections:
* "Development" -> "Testing" -> "HMC inventory file"
* "Development" -> "Testing" -> "HMC vault file"
* "Development" -> "Developing tests" (new section, content was moved up from under "Testing")
=> Improved docs of HMC inventory & vault files and testutils module

docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmcclient/_session.py
Rolls back PR #1147 into 1.7.1.
=> 1.7: Changed urllib3.Retry.method_whitelist to allowed_methods

docs/changes.rst, zhmcclient/_version.py
Nothing relevant for users, just releasing it because 1.8.0 is ready for release soon.
=> Release 1.7.1

dev-requirements.txt
=> Fixed dependency confict with safety/packaging

docs/changes.rst, tests/end2end/test_console.py, zhmcclient/_partition.py
No need to roll back to 1.7, since the one error was introduced only in 1.8.0 and the other error did not surface due to missing testcases.
* The Partition.hbas property is now unconditionally set to a HbaManager object, even when on z14 or later.
=> Fixed end2end testcase errors in test_hba.py and test_console.py

tests/end2end/test_adapter.py
=> Fixed end2end testcase for list_sibling_adapters()

.safety-policy.yml, docs/changes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #1193 into 1.8.2
=> 1.8: Addressed safety issues from 6/2023

docs/development.rst, examples/example_hmc_inventory.yaml, examples/example_hmc_vault.yaml, examples/example_mocked_z16_classic.yaml, examples/example_mocked_z16_dpm.yaml
As mentioned in issue - https://github.com/zhmcclient/python-zhmcclient/issues/1133
Changed the mocked file for z13 to z16 configuration
Signed-off-by: Kavin Raj A M <rkavin78@gmail.com>
=> Upgrade mock files and their examples from z13 to z16

docs/changes.rst, tests/common/http_mocked_fixtures.py
This PR provides the basis for multiple other PRs that add testcases based on HTTP-level mocking.
=> Test: Fixtures for HTTP-level mocking

docs/changes.rst, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1235 into 1.10.1
=> 1.10: Fixed zhmcclient_mock support for LDAP Server Definitions

docs/changes.rst, tests/end2end/test_adapter.py, tests/end2end/test_auto_update.py, tests/end2end/test_group.py, tests/end2end/utils.py
Rolls back PR #1239 into 1.10.2.
=> 1.10: Fixed end2end testcases for adapters, auto-updating, and groups

docs/changes.rst, zhmcclient/_notification.py
Rolls back PR #1242 into 1.10.2
=> 1.10: Fixed SubscriptionNotFound exception message

docs/changes.rst, examples/example_hmc_inventory.yaml, examples/example_mocked_z16_classic.yaml, examples/example_mocked_z16_dpm.yaml, tests/end2end/test_auto_update.py, tests/end2end/utils.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_resource.py, zhmcclient_mock/_urihandler.py
With this PR, the set of errors when running against the example mock support has been reduced to these, which are caused by not having implemented support for the corresponding operations in the mock support. This is left for another PR to add.
```
$ TESTINVENTORY=examples/example_hmc_inventory.yaml TESTVAULT=examples/example_hmc_vault.yaml make end2end
. . .
FAILED tests/end2end/test_adapter.py::test_adapter_list_assigned_part[hmc_definition=MOCKED_Z16_DPM] - zhmcclient._exceptions.HTTPError: 404,1: Unknown resource with URI: /api/adapters/osa1/operations/get-partitions-assigned-to-adapter [GET /api/adapters/osa1/operations...
FAILED tests/end2end/test_cpc.py::test_cpc_export_dpm_config[hmc_definition=MOCKED_Z16_DPM] - …
```
=> Fixed end2end tests for example mocked environment

docs/changes.rst, docs/development.rst, zhmcclient/testutils/_cpc_fixtures.py, zhmcclient/testutils/_hmc_definition_fixtures.py, zhmcclient/testutils/_hmc_definitions.py
To look at the section that has been updated:
```
git checkout andy/testutils-docs
make builddoc
open build_doc/html/docs/development.html
```
In the browser page that opens, navigate to section 8.6 "Developing tests".
=> Docs: Improved documentation for developing tests

dev-requirements.txt, docs/changes.rst
Rolls back PR #1263 into 1.11.1
=> 1.11: Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

docs/changes.rst, zhmcclient/_manager.py
Rolls back PR #1266 into 1.11.1
=> 1.11: Fixed max number of threads in bulk ops

.github/workflows/test.yml
Rolls back PR https://github.com/zhmcclient/python-zhmcclient/pull/1280 into 1.11.3.
=> 1.11: Moved 'make safety' to the end of the test workflow

docs/changes.rst, examples/increase_crypto_config.py
The reason the new script hard codes HMC,CPC,partition etc  is that it can be used as a replacement for the not yet existing crypto mgmt support in the zhmc cli.
=> Added example script for increasing crypto config

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #1293 into 1.11.3.
=> 1.11: Bump gitpython from 3.1.34 to 3.1.37

docs/changes.rst, examples/example_mocked_z16_dpm.yaml, tests/end2end/test_partition.py, tests/unit/zhmcclient/test_partition.py
Details:
* Added some more cases in unit tests to check filter_args funtionality for list permitted partitions
* Added end2end test case to check the list permitted partitions functionality
=> Added unit tests and end2end tests for list permitted partitions

docs/changes.rst, tests/end2end/test_lpar.py, zhmcclient/_lpar.py
Main review points:
* Updated description of `activation_profile_name` parameter of `Lpar.activate()`: https://github.com/zhmcclient/python-zhmcclient/pull/1303/files#diff-e4c63071db073baddf2ce701c8101b698e12316793798a7f5e16aa95909caff3R289
=> Updated LPAR.activate description; Added end2end tests for LPAR activation

docs/changes.rst, zhmcclient/_lpar.py
Rolls back the doc fix portion of PR #1303 into 1.11.3.
=> 1.11: Updated LPAR.activate description

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
Rolls back PR #1311 into 1.11.3.
Needs to wait until that PR is approved - No further review needed on this PR.
=> 1.11: Fixed waiting for LPAR status in Lpar.activate()

docs/changes.rst, zhmcclient/_lpar.py, zhmcclient/_utils.py
I tested on M96 for all four operations where deferred status handling was removed because it is not actually needed.
=> Fixed LPAR reset methods; Deprecated deferred status parms in LPAR methods

docs/changes.rst, zhmcclient/_lpar.py, zhmcclient/_utils.py
Rolls back PR #1305 into 1.11.3.
Needs to wait until that PR is approved - No further review needed on this PR.
=> 1.11: Fixed LPAR reset methods; Deprecated deferred status parms in LPAR methods

docs/changes.rst, zhmcclient/_constants.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
=> Shortened status timeout to 60 sec; fixed status_timeout descriptions

docs/changes.rst, zhmcclient/_constants.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
Rolls back PR #1311 into 1.11.3.
Needs to wait until that PR is approved - No further review needed on this PR.
=> 1.11: Shortened status timeout to 60 sec; fixed status_timeout descriptions

docs/changes.rst, tests/unit/zhmcclient/test_lpar.py, zhmcclient/_lpar.py
Rolls back PR #1320 into 1.11.4.
Needs to wait until PR #1320 is merged.
=> 1.11: Fixed status to wait for in SSC activation

tests/end2end/test_lpar.py
=> Cleaned up end2end test for lpar.activate()

dev-requirements.txt
=> Fixed ruamel.yaml issue on Python 3.6 by pinning to <0.17.22

dev-requirements.txt
Rolls back PR #1326 into 1.11.4.
=> 1.11: Fixed ruamel.yaml issue on Python 3.6 by pinning to <0.17.22

docs/changes.rst, tests/end2end/test_activation_profile.py, zhmcclient/_activation_profile.py
I successfully ran the end2end tests for test_activation_profile.py on A65.
=> Added support for creation and deletion of activation profiles on z16

docs/changes.rst, zhmcclient/_session.py
=> Additional log entries when HTTP status 403 is received, for easier detection

docs/changes.rst, zhmcclient/_session.py
Rolls back PR #1353 into 1.12.1.
=> 1.12: Additional log entries when HTTP status 403 is received, for easier detection

docs/changes.rst, zhmcclient/_cpc.py
The PR adds support for these HMC operations:
* "CPC Install and Activate"
* "CPC Delete Retrieved Internal Code"
* The way the operation parameters are represented in Python.
* Returning the job message in `Cpc.install_and_activate()`
* Statement about not downloading updates from the IBM support site in `Cpc.install_and_activate()`
* Description of which updates are deleted when `ec_levels` is specified in `Cpc.delete_retrieved_internal_code()`
=> Added support for SE firmware upgrade related operations

docs/changes.rst, zhmcclient/_session.py
Changes:
* Some jobs like single-step-install require restarting the HMC several times. Requests for job status will return ConnectionError while HMC is restarting. This will be ignored to tolerate HMC restarts that will happen while waiting for completion of the job.
This solves #1365 
Signed-off-by: Abhiram Santhosh <abhiram.santhosh1@ibm.com>
=> Tolerate restarts while waiting for job completion

examples/install_from_ftp.py, tests/common/http_mocked_fixtures.py, tests/unit/zhmcclient/test_port.py, tests/unit/zhmcclient/test_session.py, tests/unit/zhmcclient/test_virtual_function.py, tests/unit/zhmcclient/test_virtual_switch.py, zhmcclient/_session.py
Add example to use load-from-ftp for automated LPAR installation.
The session-credential can be used to connect to the API message broker. Store it as a new property.
Tested on a z16 with API 2.26
Suggested-by: Vance Morris <vmorris@redhat.com>
Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>
=> Add example for load-from-ftp

docs/changes.rst, zhmcclient/_notification.py
=> Clarified support for session id/credential for NotificationReceiver

docs/changes.rst, tests/end2end/test_hmc_inventory.py, tests/end2end/utils.py
=> Fixed end2end test function test_hmcdef_cpcs() to tolerate 'loadable_lpars' etc

docs/changes.rst, tests/end2end/test_hmc_inventory.py, tests/end2end/utils.py
Rolls back PR #1378 into 1.12.3.
No additional review needed.
=> 1.12: Fixed end2end test function test_hmcdef_cpcs() to tolerate 'loadable_lpars' etc

docs/changes.rst, tests/end2end/test_activation_profile.py, tests/end2end/utils.py
Rolls back PR #1375 into 1.12.3.
No additional review needed.
=> 1.12: Fixed end2end testcase 'test_actprof_crud()'

docs/changes.rst, docs/concepts.rst, docs/development.rst, tests/common/http_mocked_fixtures.py, tests/unit/zhmcclient/test_port.py, tests/unit/zhmcclient/test_session.py, tests/unit/zhmcclient/test_virtual_function.py, tests/unit/zhmcclient/test_virtual_switch.py, tests/unit/zhmcclient_mock/test_session.py, zhmcclient/_auto_updater.py, zhmcclient/_session.py, zhmcclient/testutils/_hmc_definition.py, zhmcclient/testutils/_hmc_definitions.py, zhmcclient/testutils/_hmc_inventory_file.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
Has been successfully end2end tested with M12 and its two redundant HMCs, using the following test cases:
* a single one of its redundant HMCs
* both of its redundant HMCs
* a non-existing HMC and its two redundant HMCs
* a non-existing HMC
* two non-existing HMCs
In all cases, the first one in the specified list that worked was actually used, and the same error as before was raised when none of them worked.
On cross-checking whether the ibm_zhmc collection works with this extension:
* I verified an HMC inventory file that specifies a list of HMC hosts with the end2end testcases of the ibm_zhmc collection which worked immediately (no surprise, since they use the python-zhmcclient testutils support).
* The ibm_zhmc collection sample playbooks though did …
=> Support for redundant HMCs

docs/changes.rst, zhmcclient/_console.py
=> Clarified the HMC version requirements for Console.list_permitted_adapters()

docs/changes.rst, zhmcclient/_storage_group.py
Related to issue https://github.com/zhmcclient/zhmc-ansible-modules/issues/864
=> Docs: Clarified that list_candidate_adapter_ports() is for FCP SGs only

docs/changes.rst, zhmcclient/_storage_group.py
Rolls back PR #1383 into 1.12.3
=> 1.12: Docs: Clarified that list_candidate_adapter_ports() is for FCP SGs only

zhmcclient/testutils/_hmc_definitions.py
Rolls back PR #1388 into 1.12.3
=> 1.12: Fixed make end2end_show when specifying multiple HMCs in inv.file

zhmcclient/_session.py
=> Docs: Fixed Sphinx warning in Job.query_status()

docs/changes.rst, tests/unit/zhmcclient/test_manager.py, zhmcclient/_manager.py, zhmcclient/_utils.py
Rolls back PR #1395 to 1.12.4.
=> 1.12: Undo regexp matching of name in find(); Fixed case insensitive regexp matching

docs/changes.rst, tests/unit/zhmcclient/test_manager.py, zhmcclient/_manager.py, zhmcclient/_utils.py
* Keeps the regexp matching for the resource name in `findall()`.
* Uses string comparison for the resource name in `find()`.
* Ignores any other filter arguments if resource name is specified as a filter in `find()`.
Will be rolled back to 1.13.1 and 1.12.4 (since the regexp change was released in 1.12.3 and 1.13.0)
=> Undo regexp matching of name in find(); Fixed case insensitive regexp matching

Makefile, dev-requirements.txt
Rolls back PR #1413 into 1.13.2.
=> 1.13: Fixed dependency issue with safety; Added minimum-constraints to targets

docs/changes.rst, zhmcclient/_console.py
End2end tests:
* Classic mode: `TESTHMC=M96 make end2end` passed, except for the usual 7 known testcase failures.
* DPM mode: `TESTHMC=T224 TESTCASES='test_console_list_permitted_partitions' make end2end`passed.
=> Fixed performance issue in list_permitted_lpars/partitions()

AUTHORS.md, Makefile, docs/changes.rst, docs/development.rst
* Added support for a new make target 'authors' that generates an AUTHORS.md file from the git commit history.
* Added the invocation of 'make authors' to the description of how to release a version in the development documentation.
=> Support for creating AUTHORS.md file

.github/workflows/test.yml, docs/changes.rst
Rolls back PR #1426 into 1.13.3.
=> 1.13: Fixed pipdeptree call in test workflow

.github/workflows/test.yml, docs/changes.rst
* Fixed the call to pipdeptree in the test workflow to use 'python -m' because otherwise it does not show the correct packages of the virtual env.
=> Fixed pipdeptree call in test workflow

docs/changes.rst, tests/end2end/test_lpar.py, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_console.py, zhmcclient/_resource.py
End2end tests (after last commit 95cd8d7):
* Classic mode: `TESTHMC=A01 TESTCASES='test_console_list_permitted_lpars' make end2end` passed.
* DPM mode: `TESTHMC=T224 TESTCASES='test_console_list_permitted_partitions' make end2end` passed.
=> Added CPC related properties to list_permitted_lpars/partitions(); improved pull

docs/changes.rst, tests/unit/zhmcclient/test_cpc.py, zhmcclient/_cpc.py
Rolls back PR #1433 into 1.13.4.
=> 1.13: Fixed the 'Cpc.delete_retrieved_internal_code()' method ec_level

dev-requirements.txt, minimum-constraints.txt
=> Fixed check_reqs SyntaxWarning on tox by increasing tox to 3.1.0

design/fakedsession.md, tests/unit/zhmcclient_mock/test_hmc.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
Note: Removal of session IDs in the mocked Logoff operation and validation of session IDs in any mocked operations that require to be logged on has not been implemented in this change. That would require passing the HTTP header fields to the mock support, which is not the case today and would require larger changes.
However, since addition/removal/validation of session IDs is implemented for the FakedHmc class, this should be sufficient to provide the session ID support required for zhmcclient/zhmccli#413.
=> Mock: Added partial support for session IDs

.github/workflows/test.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
=> Fixed macos version used in test workflow for py35/36/37; Fixed pyzmq

.github/workflows/test.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #1471 into 1.14.1.
=> 1.14: Fixed macos version used in test workflow for py35/36/37; Fixed pyzmq install

.github/workflows/test.yml
Rolls back PR #1479 into 1.14.1.
=> 1.14: Improved circumvention for pip cert issue on Python 3.5

.github/workflows/test.yml, Makefile, changes/.gitignore, changes/1451.feature.rst, changes/1473.fix.rst, changes/1485.feature.rst, changes/changes.rst.j2, changes/noissue.1.feature.rst, changes/noissue.1.fix.rst, changes/noissue.2.feature.rst, changes/noissue.2.fix.rst, changes/noissue.3.feature.rst, changes/noissue.3.fix.rst, changes/noissue.4.fix.rst, changes/noissue.5.fix.rst, dev-requirements.txt, docs/changes.rst, docs/conf.py, docs/development.rst, minimum-constraints.txt, towncrier.toml
This is a first step for simplifying the procedures for releasing a version and starting a new version. For the complete proposal, see issue #1485
=> Migrated changelog to use towncrier

changes/1490.incompatible.rst, zhmcclient/_user.py
Changes:
- User object(python object, not HMC) does not need to store password. Filter and remove 'password' from the propertied before updating the local object during user create and update.
Fixes https://github.com/zhmcclient/zhmc-ansible-modules/issues/967
=> Remove password property before updating local user object

changes/1459.fix.rst, docs/appendix.rst, docs/intro.rst
The PR has been updated with the final links, according to the HMC docs lead.
=> Docs: Fixed and remove broken links to HMC books

docs/appendix.rst, docs/changes.rst, docs/intro.rst
Rolls back PR #1459 into 1.14.1.
The PR has been updated with the final links, according to the HMC docs lead.
=> 1.14: Docs: Fixed and remove broken links to HMC books

.github/workflows/publish.yml, .github/workflows/test.yml, changes/1503.cleanup.rst
=> Upgraded Actions plugins to no longer use deprecated node 16

.safety-policy-install.yml, changes/1499.cleanup.rst, minimum-constraints-install.txt, requirements.txt, tests/unit/zhmcclient/test_notification.py, zhmcclient/_auto_updater.py, zhmcclient/_notification.py, zhmcclient/_utils.py
=> Removed the pinning of stomp.py to <7.0.0 to pick up fixes

changes/1498.feature.rst, zhmcclient/_auto_updater.py, zhmcclient/_constants.py, zhmcclient/_notification.py, zhmcclient/_session.py
=> Changed STOMP retry/timeout config defaults for keepalive/heartbeating

changes/noissue.1.feature.rst, tests/unit/zhmcclient/test_auto_updater.py
Background: Since PR #1474 adds a number of log entries, I wanted to be able to specify the testcases only with the relevant subset of log messages, instead of adding all of them also as expected log messages to the tests.
I tested the verification logic with several failure cases.
=> Test: Relaxed the verification of log messages in test_auto_updater.py

changes/1502.feature.rst, changes/1502.incompatible.rst, examples/async_operation_notification.py, examples/install_from_ftp.py, examples/show_os_messages.py, tests/unit/zhmcclient/test_notification.py, zhmcclient/_constants.py, zhmcclient/_exceptions.py, zhmcclient/_notification.py
This change was tested with:
* The example script "show_os_messages.py"
* The zhmc-log-forwarder (as of its PR https://github.com/zhmcclient/zhmc-log-forwarder/pull/14)
In both cases, the default STOMP retry/timeout config was used (i.e. with STOMP heartbeating enabled), the network was disconnected and connected again, and the notification receiver detected the disconnect properly and also reconnected properly.
=> Used Queue for STOMP listener handover; Improved connection loss recovery

changes/1511.feature.rst, examples/get_sustainability_data.py, tests/end2end/test_cpc.py, tests/end2end/test_lpar.py, tests/end2end/test_partition.py, zhmcclient/_cpc.py, zhmcclient/_lpar.py, zhmcclient/_partition.py
The PR passes the new end2end tests it adds (with some warnings on time deltas in the returned data points):
* for CPC and Partition on A224 (DPM mode machine).
* for CPC on A217 (classic mode machine).
Did not have a machine with LPARs for testing it for LPARs, but the code is basically the same as for partitions on DPM mode machines.
=> Added new z16 get sustainability data methods

.safety-policy-install.yml, changes/1516.bugfix.rst, docs/intro.rst, docs/security.rst, minimum-constraints-install.txt, requirements.txt, zhmcclient/_utils.py
Rolls back PR #1516 into 1.16.1.
No additional review needed.
=> 1.16: Install: Changed dependent package 'stomp.py' to use 'stomp-py' name

changes/noissue.1.cleanup.rst, tests/unit/zhmcclient/test_utils.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1524 into 1.16.2.
=> 1.16: Fixed new issues reported by new flake8 7.0.0

changes/noissue.4.notshown.rst, tests/end2end/mocked_hmc_z16.yaml, tests/end2end/mocked_inventory.yaml
For the prior errors that are now fixed, see https://github.com/zhmcclient/python-zhmcclient/actions/runs/9581883161/job/26419661424#step:18:26
=> Mock: Fixed the incorrect YAML syntax and swapped CPCs in z16 mock files

changes/1567.cleanup.rst
No review needed - merging it in order to get RTD updated.
The actual change is in the RTD version settings:
- set "latest" to be hidden
- activated "master"
=> Changed RTD versions shown in docs to be master instead of latest

changes/1567.cleanup.rst, docs/development.rst
This PR updates the release instructions in the "Development" section of the documentation to hide the previous fix version if a new fix version is released, in order to keep the number of versions show in the RTD documentation to be only the latest fix version of each minor version.
The reduction of the previously released versions on RTD has already been done in PR #1568 and can be seen at https://python-zhmcclient.readthedocs.io/ (which should redirect to https://python-zhmcclient.readthedocs.io/en/master/) by clicking on "v:master" at the bottom of the left hand pane.
=> Updated release instructions for reduced versions on RTD

changes/1560.fix.rst, changes/noissue.7.notshown.rst, docs/appendix.rst
This implements one of the options listed in issue #1560 - please consider both options when reviewing this PR.
=> Added bibliography entries for HMC API books 2.11 - 2.12 back in

changes/1583.fix.rst, zhmcclient_mock/_urihandler.py
This change was tested locally with PR https://github.com/zhmcclient/zhmc-ansible-modules/pull/1027.
This PR is needed for PR https://github.com/zhmcclient/zhmc-ansible-modules/pull/1027 and has therefore been set to priority.
=> Mock: Fixed that resource properties were not independent of internal state

.github/workflows/test.yml, changes/1573.notshown.rst, docs/development.rst
* With this approach, the label needs to be set while creating the PR. If that is forgotten, the check fails and then after adding the label, a dummy push is needed to trigger the test workflow again. The question is, is that too cumbersome in the handling.
=> Test: Transitioned to label 'no change log' for PRs without need for change log

.readthedocs.yaml
For the RTD build failure this fixes, see https://readthedocs.org/projects/python-zhmcclient/builds/25209635/
=> Fixed RTD build requirements by adding base-requirements.txt

.readthedocs.yaml
Rolls back PR #1599 into 1.17.1.
=> 1.17: Fixed RTD build requirements by adding base-requirements.txt

Makefile
Rolls back PR #1622 into 1.17.1 (with future revert of starting 1.17.2)
=> 1.17: Fixed unintended authors update during release workflow

.github/workflows/test.yml, changes/1505.feature.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
A separate issue #1506 exists to use the final Python 3.13.0 version, once released, so this PR can be merged.
=> Test: Added tests for Python 3.13 (rc.1)

changes/618.feature.rst, docs/general.rst, tests/end2end/test_partition.py, tests/unit/zhmcclient/test_partition.py, zhmcclient/_partition.py
This PR contains only the support for a new method that invokes the "Get ASCII Console WebSocket URI" HMC operation. The higher level support for making the interactions with the OS console easier, will be in the separate PR #1648 .
=> Support for "Get ASCII Console WebSocket URI" operation

.github/workflows/release_pr.yml
Following the recommendation in https://github.com/actions/github-script/issues/484.
=> release_pr: changed to use github-token parameter

changes/1660.fix.rst, dev-requirements.txt, requirements.txt
=> Circumvented an issue with pytz by excluding pytz version 2024.2

changes/1660.fix.rst, dev-requirements.txt, requirements.txt
Rolls back PR #1659 into 1.17.2.
=> 1.17: Circumvented an issue with pytz by excluding pytz version 2024.2

.github/workflows/test.yml, Makefile, changes/1665.fix.rst
For the attempt to debug this, see PR #1663.
If any of the reviewers has an idea why the login shell was specified for invoking coveralls, please comment on that during your review.
=> Fixed coveralls not found on MacOS with py39-311

.github/workflows/test.yml, Makefile, changes/1665.fix.rst
Rolls back PR #1664 into 1.17.2.
=> 1.17: Fixed coveralls not found on MacOS with py39-311

.github/workflows/test.yml, changes/1506.feature.rst, dev-requirements.txt, minimum-constraints-develop.txt
Will be restarted daily until Python 3.13.0 GA becomes available.
Status:
* Python 3.13.0 has been released
* GitHub Actions has a PR for picking it up: https://github.com/actions/python-versions/pull/312
=> Test: Added tests for Python 3.13 (final version)

Makefile, changes/1689.fix.rst
Rolls back PR #1691 into 1.18.1.
=> 1.18: Fixed incorrect check for start branch in 'make start_tag'

Makefile
It had been removed in PR #1622 because it was updated in the publish workflow. PR #1694 provided a better circumvention by making the AUTHORS.md file creation check for whether the git shortlog command returned any authors.
With the better circumvention in place, the previous circumvention is now removed.
=> Dev: Added AUTHORS.md to build dependencies again

Makefile
Rolls back PR #1702 into 1.18.1.
=> 1.18: Dev: Added AUTHORS.md to build dependencies again

Makefile
Rolls back PR #1704 into 1.18.1.
=> 1.18: Document git shortlog issue in Makefile

Makefile, changes/noissue.2.fix.rst
Rolls back PR #1706 into 1.18.1.
=> 1.18: Fix issue that without terminal the AUTHORS.md file was emptied

.github/workflows/publish.yml
Rolls back PR #1708 into 1.18.1.
=> 1.18: Resolved packages_dir warning in publish workflow

changes/noissue.1.feature.rst, changes/noissue.4.fix.rst, tests/common/utils.py, tests/unit/zhmcclient/test_activation_profile.py, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient/test_logging.py, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient/test_user.py, zhmcclient/_activation_profile.py, zhmcclient/_constants.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_logging.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_session.py, zhmcclient/_user.py
Tested in addition, using this version of zhmcclient:
* with "make end2end" against A218 - raises the same failures as with master branch
* with "make test" in zhmccli repo - passed without issues
* with "make test" in zhmc-ansible-modules repo - passed without issues
=> Fixed clear-text logging of all password-like properties in API/HMC log

changes/noissue.1.feature.rst, changes/noissue.4.fix.rst, tests/common/utils.py, tests/unit/zhmcclient/test_activation_profile.py, tests/unit/zhmcclient/test_ldap_server_definition.py, tests/unit/zhmcclient/test_logging.py, tests/unit/zhmcclient/test_lpar.py, tests/unit/zhmcclient/test_partition.py, tests/unit/zhmcclient/test_user.py, zhmcclient/_activation_profile.py, zhmcclient/_constants.py, zhmcclient/_ldap_server_definition.py, zhmcclient/_logging.py, zhmcclient/_lpar.py, zhmcclient/_partition.py, zhmcclient/_session.py, zhmcclient/_user.py
Rolls back PR #1714 into 1.18.1.
=> 1.18: Fixed clear-text logging of all password-like properties in API/HMC log

changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1716 into 1.18.1.
=> 1.18: Fixed safety issues up to 2024-11-28

changes/noissue.5.fix.rst, zhmcclient/_logging.py, zhmcclient/_session.py
=> Fixed incorrect blanked-out password-like properties

changes/noissue.5.fix.rst, zhmcclient/_logging.py, zhmcclient/_session.py
Rolls back PR #1721 into 1.18.2.
=> 1.18: Fixed incorrect blanked-out password-like properties

.github/workflows/test.yml, changes/noissue.1.cleanup.rst
Rolls back PR #1726 into 1.18.3.
=> 1.18: Accomodated rollout of Ubuntu 24.04 on GitHub Actions

.github/workflows/test.yml
Rolls back PR #1729 into 1.18.3.
=> 1.18: Pinned Python 3.13 to 3.13.0 to work around pylint issue

.github/workflows/test.yml, changes/noissue.6.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1730 into 1.18.3.
=> 1.18: Circumvented issue with installing pywinpty on py38; Added py38/win/latest

changes/1728.fix.rst
The change entry was missing in PR #1729.
=> Pinned Python 3.13 to 3.13.0 - change entry

changes/1728.fix.rst
The change entry was missing in PR #1732.
=> 1.18: Pinned Python 3.13 to 3.13.0 - change entry

changes/noissue.3.feature.rst, zhmcclient/testutils/_hmc_definition_fixtures.py
=> Increased end2end operations timeout

changes/1668.feature.2.rst, changes/1668.feature.rst, docs/appendix.rst, docs/resources.rst, tests/end2end/test_mfa_server_definition.py, tests/unit/zhmcclient/test_mfa_server_definition.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_mfa_server_definition.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_urihandler.py
=> Support for MFA Server Definitions

changes/1678.feature.2.rst, changes/1678.feature.rst, docs/appendix.rst, docs/resources.rst, examples/list_attached_partition_links.py, examples/list_partition_links.py, tests/end2end/test_partition.py, tests/end2end/test_partition_link.py, tests/end2end/utils.py, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_exceptions.py, zhmcclient/_partition.py, zhmcclient/_partition_link.py, zhmcclient/_session.py, zhmcclient/_utils.py
=> Support for Partition Links

tests/end2end/test_partition_link.py
This fixes an error in the end2end tests added in PR #1685 
=> Fixed check of input properties in partition link end2end test

tests/end2end/test_partition_link.py
=> Fixed expected properties in partition link end2end tests

tests/end2end/test_partition_link.py
=> Fixed partitionlink end2end tests by waiting for completion

changes/fix.1755.rst, dev-requirements.txt, requirements.txt
=> Fixed a datetime conversion error by excluding pytz 2025.1

changes/fix.1755.rst, dev-requirements.txt, requirements.txt
Rolls back PR #1756 into 1.19.1.
=> 1.19: Fixed a datetime conversion error by excluding pytz 2025.1

tests/end2end/test_virtual_storage_resource.py
The test otherwise fails with a 404.1 if the system has non-FCP storage groups.
=> Filter out non-FCP storage groups in test_virtual_storage_resource.

AUTHORS.md, changes/1760.fix.rst, zhmcclient/_cpc.py
When inventory errors are encountered and logged to the user during "Export DPM configurtion", the field "inventory-error-details" is only be present if "inventory-error-code" is 5. This change adds a corresponding check to avoid failing with a corresponding TypeError.
=> Fix broken inventory error handling

minimum-constraints-develop.txt
Rolls back PR #1766 into 1.19. No review needed.
=> 1.19: Fixed missing package dependencies for development (nltk)

changes/1764.fix.1.rst, changes/1764.fix.rst, zhmcclient/_cpc.py
Rolls back PRs #1765 and #1770 into 1.19.
=> 1.19: Fix broken adapter removal; Drop storage/network ports for removed adapters

changes/noissue.1.fix.rst, zhmcclient/_partition_link.py, zhmcclient/_session.py, zhmcclient_mock/_session.py
=> Added retries when HMC returns busy (HTTP 409)

changes/1755.fix.rst, changes/fix.1755.rst
Rolls back PR #1777 into 1.19.
=> 1.19: Fixed name of change log file

changes/1775.feature.1.rst, changes/1775.feature.2.rst, changes/1775.fix.1.rst, changes/1775.fix.2.rst, zhmcclient/_console.py, zhmcclient/_metrics.py
I tested the performance improvement using the zhmc prometheus exporter: On the HMC of T28 which manages 7 CPCs all in classic mode with a total of 44 LPARs, the elapsed time for the first data collection (where the resource lookup is performed) went down from 59 sec to 12 sec.
=> Improved performance of LPAR/adapter lookup during metrics; Fixed exception msg

.github/workflows/publish.yml, changes/1738.feature.rst
When trusted publishing was enabled for the exporter, the upload to Pypi worked, but the subsequent step in the publish.yml workflow to create a release failed. GitHub ticket https://support.github.com/ticket/personal/0/3042595 has been opened for that. Need to wait for clarity on that.
The trust of GitHub has already been established on the Pypi side for all zhmcclient repos.
Once trusted publishing works, the PYPI_API_KEY secrets can be removed in GitHub and the corresponding keys in Pypi.
=> Dev: Started using the trusted publisher concept of Pypi

changes/1738.feature.rst, changes/1755.fix.rst, changes/1760.fix.rst, changes/1764.fix.1.rst, changes/1764.fix.rst, changes/1775.feature.1.rst, changes/1775.feature.2.rst, changes/1775.fix.1.rst, changes/1775.fix.2.rst, changes/noissue.1.20.0.notshown.rst, changes/noissue.1.fix.rst, changes/noissue.4.feature.rst, changes/noissue.checkreqs-dev.fix.rst, changes/noissue.safety.fix.rst, changes/noissue.tc.feature.rst, docs/changes.rst
This reverts PR #1783 which was used to test the release process using Pypi trusted publishing.
=> Revert "Release 1.20.0"

tests/end2end/test_virtual_storage_resource.py
Rolls back PR #1759 into 1.19.
=> 1.19: Filter out non-FCP storage groups in test_virtual_storage_resource.

.github/workflows/publish.yml, changes/noissue.2.fix.rst
Rolls back PR #1798 into 1.20.
=> 1.20: Dev: Fixed permissions for creating GitHub release when releasing a version

changes/1800.fix.rst, dev-requirements.txt, requirements.txt
Fixed a datetime conversion error by excluding pytz 2025.2
Signed-off-by: Anil Kumar Dakarapu <anil.kumar.dakarapu@ibm.com>
=> Fixed a datetime conversion error by excluding pytz 2025.2

changes/1800.fix.rst, dev-requirements.txt, requirements.txt
Rolls back PR #1801 into 1.20.
=> 1.20: Fixed a datetime conversion error by excluding pytz 2025.2

changes/1803.feature.rst, changes/1803.fix.rst, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_metrics.py
Rolls back PR #1803 into 1.20.
=> 1.20: Fixed use of list_permitted_adapters(); Added caching for list_api_features()

changes/1821.fix.rst, zhmcclient/_cpc.py
Ensure dpm-export doesn't fail on unknown dict keys
during final 'reduction' phase.
=> bugfix: dpm-export fails on unknown keys

changes/1821.fix.rst, zhmcclient/_cpc.py
Rolls back PR #1822 into 1.20.
=> 1.20: Ensure dpm-export doesn't fail on unknown dict keys during

changes/1820.feature.rst, zhmcclient/_session.py
=> Handled the presence of the @@implementation-errors property in HMC responses

changes/1713.fix.rst, zhmcclient/_cpc.py
Other than suggested in the corresponding issue, this PR does not implement the `Cpc.get_wwpns()` method with a loop through attached storage groups and their VSRs, but instead just clarifies that the method was only supported for SE version 2.13.1. It seems to me that the design of the function (being on the CPC, supporting a set of partitions) does not make it worthwhile to support with an inefficient implementation (loop through partitions, loop through their attached storage groups eliminating duplicates, loop through their VSRs).
=> Clarified that Cpc.get_wwpns() is no longer supported

changes/1713.fix.rst, zhmcclient/_cpc.py
Rolls back PR #1832 into 1.20.
=> 1.20: Clarified that Cpc.get_wwpns() is no longer supported

changes/noissue.marshmallow.fix.rst, changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> Dev: Pinned marshmallow to <4.0 because it breaks safety; Fixed safety issues

changes/noissue.marshmallow.fix.rst, changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1839 into 1.20.
=> 1.20: Dev: Pinned marshmallow to <4.0 because it breaks safety; Fixed safety issues

changes/1836.feature.rst, zhmcclient/_manager.py
I tested the PR with end2end tests for test_cpc.py and test_adapter.py on T224. These resources do not exceed the bulk request limit, but this verifies that it works as before.
Together with PR #1834, I tested this PR with end2end tests for test_hw_message.py on T224. This test exceeded the bulk request limit for the console hardware messages and caused two bulk operations to be sent.
This PR is not rolled back into the fix stream, because before the introduction of HW messages, there is no resource type that can possibly exceed the bulk request maximum: The maximum number of the kind GET requests we use in bulk operations is between 1500 and 3000 (dependent on the length of the resource URIs), and there is no resource type that can have such a large …
=> Split 'Submit Requests' operation when request body limit is exceeded

changes/noissue.marshmallow.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
Rolls back PR #1841 into 1.20.
=> 1.20: Increased safety to 3.4.0 and updated its dependencies

changes/1672.feature.1.rst, changes/1672.feature.2.rst, docs/appendix.rst, docs/resources.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml, tests/end2end/test_hw_message.py, tests/unit/zhmcclient/test_hw_message.py, zhmcclient/__init__.py, zhmcclient/_console.py, zhmcclient/_cpc.py, zhmcclient/_hw_message.py, zhmcclient/_manager.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py, zhmcclient_mock/_session.py, zhmcclient_mock/_urihandler.py
I tested it with the new end2end test test_hw_message.py on T224, and verified that the console hardware messages exceed the request limit for "Submit Requests" and are properly split into two operations.
=> Support for Console / CPC Hardware Messages (using resource class)

dev-requirements.txt, minimum-constraints-develop.txt
Addresses a Mend issue from the internal repo: https://github.ibm.com/zhmcclient/python-zhmcclient/issues/83
=> Increased minimum versions of zipp,importlib-metadata,importlib-resources

minimum-constraints-develop.txt
Addresses a Mend issue from the internal repo: https://github.ibm.com/zhmcclient/python-zhmcclient/issues/84
=> Added cryptography as a dev dependency to ensure minimum version

changes/noissue.2.fix.rst, requirements.txt
Addresses a Mend issue from the internal repo: https://github.ibm.com/zhmcclient/python-zhmcclient/issues/87
=> Added dependency to idna>=3.7

changes/noissue.safety.fix.rst, minimum-constraints-develop.txt
Rolls back PR #1864 into 1.21.
=> 1.21: Safety issues up to 2025-05-11

renovate.json
This is described in https://docs.renovatebot.com/key-concepts/dashboard/ .
I assume this causes the "Dependency Dashboard" issue to be created and updated. However, we already got this issue created without doing anything for it: https://github.com/zhmcclient/python-zhmcclient/issues/1861.
So it is not really clear what this change does.
=> Enabled Renovate dependency dashboard

changes/1888.2.fix.rst, minimum-constraints-install.txt, requirements.txt
=> Increased minimum version of urllib3 to 2.2.3

changes/1888.2.fix.rst, minimum-constraints-install.txt, requirements.txt
Rolls back PR #1893 into 1.21.
=> 1.21: Increased minimum version of urllib3 to 2.2.3

AUTHORS.md, Makefile, changes/1897.fix.rst
=> Made order of names in AUTHORS.md reliable

Makefile, base-requirements.txt, changes/noissue.1.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, pyproject.toml
Rolls back PR #1926 into 1.22.
=> 1.22: Fixed incorrect package version in build; Increased pipdeptree version

changes/noissue.123.feature.rst, zhmcclient/_console.py
The Report a Console Problem operation may be used by a customer via WSAPI to report a "health", "hmc", or "test" problem that will create a hardware message and may optionally be called-home.
=> console: add support for Report a Console Problem

Makefile, changes/noissue.2.fix.rst
Rolls back PR #1941 into 1.22.
=> 1.22: Fixed quoting for TESTCASES env var in Makefile

changes/1929.fix.rst, tests/end2end/test_adapter.py, tests/end2end/test_nic.py, zhmcclient/_adapter.py, zhmcclient/_nic.py, zhmcclient/_virtual_switch.py, zhmcclient_mock/_urihandler.py
Rolls back PR #1929 into 1.22.
=> 1.22: Support removal of vswitches and addition of network express adapters on z17

changes/noissue.45.fix.rst, zhmcclient/_adapter.py
=> Fixed the exception handling of the 'Adapter.delete()' method on z16 or later

changes/noissue.68.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
* typer version was pinned to 0.17.0 due to https://github.com/pyupio/safety/issues/778...and this is fixed with 3.6.1 safety version
* so we no longer need to pin that version
=> Removed the pinning on typer version <0.17.0 with the release of safety 3.6.1

changes/1975.cleanup.rst, docs/conf.py, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt, tests/common/utils.py, tests/unit/zhmcclient/test_utils.py, tests/unit/zhmcclient_mock/test_hmc.py, tests/unit/zhmcclient_mock/test_urihandler.py, zhmcclient/_utils.py, zhmcclient_mock/_hmc.py
Rolls back PR #1976 into 1.23.
=> 1.23: Removed dependency on python-dateutil

changes/noissue.39.rst, docs/general.rst
Rolls back PR #1994 into 1.23.
=> 1.23: Added missing zhmcclient exceptions to the documentation

.github/workflows/test.yml, changes/noissue.coveralls.cleanup.rst
=> Added retries for sending coverage data to the coveralls.io site
